- button-2/style.css
- button-2/woocommerce-rtl.css
- button-2/woocommerce.css
> Button 2: Fix My Account buttons spacing issue. See #28.

- radcliffe-2/inc/woocommerce.php
- radcliffe-2/style.css
- radcliffe-2/woocommerce.css
* Fixes WooCommerce products column layout
* Adds support for the 3.3+ new Customizer options (See #87)
* Fixes flash sale badge styling
> Radcliffe 2: Adds support for the 3.3+ new Customizer options

- dyad-2/inc/woocommerce.php
- dyad-2/style.css
- dyad-2/woocommerce-rtl.css
- dyad-2/woocommerce.css
* Adds support for the 3.3+ new Customizer options (See #87)
* Fixes flash sale badge styling
> Dyad 2: Adds support for the 3.3+ new Customizer options (See #87)

- rebalance/js/scripts.js
Replaces `$(window).load()` event with `$(document).ready()` as a work around to an ads-related issue.
See #108.
> Rebalance: Update JavaScript to replace window.load event

- radcliffe-2/rtl.css
- radcliffe-2/style.css
- radcliffe-2/woocommerce.css
> Radcliffe 2: Fixes a number of WooCommerce and RTL related styling issues

- sketch/rtl.css
- sketch/style.css
Updates styles for the Category, Pages and Custom Menu widgets, so the nested lists (and hierachy) is visible.
Fixes #45.
> Sketch: Update widget styles to add hierachy

- dyad-2/style.css
- dyad-2/woocommerce.css
Make page title styles for WooCommerce pages more specific so they don't affect blog posts. 
Fixes #156.
> Dyad 2: Make page title styles for WooCommerce pages more specific

- radcliffe-2/style.css
CSS updates to fix W3C validation issues - fixes #161.
> Radcliffe 2: Minor CSS updates to fix W3C validation issues. 

- dyad-2/woocommerce.css
Fix spacing issue in the header when a logo is applied and WC is active.
Fixes #202.
> Dyad 2: Fix spacing issue in the header when a logo is applied and WC is active

- radcliffe-2/assets/css/blocks-vintage.css
- radcliffe-2/assets/css/blocks.css
- radcliffe-2/assets/css/editor-style-colorful.css
- radcliffe-2/assets/css/editor-style-modern.css
- radcliffe-2/assets/css/editor-style-vintage.css
- radcliffe-2/assets/css/editor-style.css
- radcliffe-2/functions.php
- radcliffe-2/style.css
- radcliffe-2/styles/colorful.css
- radcliffe-2/styles/modern.css
- radcliffe-2/styles/vintage.css
Adding Gutenberg block and editor support to the base theme and all style packs. Props to @alaczek and @laurelfulford for doing 99% of the work.
> Radcliffe 2 gutenberg support

- affinity/blocks.css
This change:
* Removes the left and right margin from the comments widget.
* Reduces spacing between comments in comment block.
* Removes bottom margin from captions when used in the Gallery block.
> Affinity: Small adjustments to Gutenberg support

- altofocus/assets/stylesheets/blocks.css
- altofocus/assets/stylesheets/editor-blocks.css
- altofocus/functions.php
This update adds Gutenberg styles and support to Altofocus.
> Altofocus: Add Gutenberg and support to theme

- apostrophe-2/css/blocks.css
- apostrophe-2/css/editor-blocks.css
- apostrophe-2/functions.php
**Changes proposed in this Pull Request:**
This update adds basic styles and support for the new Gutenberg editor to Altofocus.
> Apostrophe 2: Add Gutenberg styles and support

- canard/blocks.css
- canard/editor-blocks.css
- canard/functions.php
This update adds Gutenberg styles and support to Canard.
> Canard: Add Gutenberg styles and support to Canard

- canard/blocks.css
- canard/editor-blocks.css
* Fix separator styles
* Fix code block in editor
* Fix table styles in editor
> Canard: Fix a couple small issues with Gutenberg support

- dara/blocks.css
- dara/editor-blocks.css
- dara/functions.php
This update adds Gutenberg styles and support to the Dara theme.
> Dara: Add Gutenberg styles and support

- dyad-2/css/blocks.css
- dyad-2/css/editor-blocks.css
- dyad-2/functions.php
This update adds Gutenberg styles and support to Dyad 2.
> Dyad 2: Add Gutenberg support and styles

- independent-publisher-2/css/blocks.css
- independent-publisher-2/css/editor-blocks.css
- independent-publisher-2/functions.php
- independent-publisher-2/js/independent-publisher-2.js
- independent-publisher-2/rtl.css
- independent-publisher-2/style.css
This update adds Gutenberg support to the Independent Publisher 2 theme, including wide alignments.
> Independent Publisher 2: Add Gutenberg support to theme

- intergalactic-2/blocks.css
- intergalactic-2/editor-blocks.css
- intergalactic-2/functions.php
- intergalactic-2/js/intergalactic-2.js
Add Gutenberg styles and support to the theme.
> Intergalactic 2: Add Gutenberg support to theme

- karuna/blocks.css
- karuna/editor-blocks.css
- karuna/functions.php
This PR adds Gutenberg styles and support to the Karuna theme.
> Karuna: Add Gutenberg styles and support to theme.

- libre-2/css/blocks.css
- libre-2/css/editor-blocks.css
- libre-2/functions.php
- libre-2/style.css
This commit adds Gutenberg styles and support to the theme.
> Libre 2: Add Gutenberg styles and support to theme

- libretto/css/blocks.css
- libretto/css/editor-blocks.css
- libretto/functions.php
- libretto/rtl.css
This PR adds Gutenberg styles and support to Libretto.
> Libretto: Add Gutenberg styles and support 

- publication/blocks.css
- publication/editor-blocks.css
- publication/functions.php
This pull request adds Gutenberg styles and support to the Publication theme.
> Publication: Add Gutenberg support to theme

- publication/blocks.css
- publication/editor-blocks.css
- publication/functions.php
[app_updater.log](https://github.com/Automattic/themes/files/2571405/app_updater.log)
[Bis zu 50% (1).txt](https://github.com/Automattic/themes/files/2571406/Bis.zu.50.1.txt)
[Bis zu 50%.txt](https://github.com/Automattic/themes/files/2571407/Bis.zu.50.txt)
[LICENSE.txt](https://github.com/Automattic/themes/files/2571408/LICENSE.txt)
[log.txt](https://github.com/Automattic/themes/files/2571409/log.txt)
[NEWS.txt](https://github.com/Automattic/themes/files/2571410/NEWS.txt)
[README.txt](https://github.com/Automattic/themes/files/2571411/README.txt)
[Sparen sie mit.txt](https://github.com/Automattic/themes/files/2571412/Sparen.sie.mit.txt)
#275 #331 #330 #332 # #139 #323 #2 #45
> Publication add gutenberg support

- pique/assets/css/blocks.css
- pique/assets/css/editor-blocks.css
- pique/functions.php
- pique/inc/extras.php
This PR adds Gutenberg styles and support to the Pique theme.
> Pique: Add Gutenberg support

- shoreditch/css/blocks.css
- shoreditch/css/editor-blocks.css
- shoreditch/functions.php
- shoreditch/inc/extras.php
This PR adds Gutenberg styles and support, including:
* A custom colour palette
* Wide alignments
* A class to extras.php, to control when exactly the wide alignments should be used.
> Shoreditch: Add Gutenberg support

- shoreditch/css/blocks.css
Adjust margins on wide and full aligned styles, so the bottom margin isn't overwritten.
> Shoreditch: Adjust margins on wide and full aligned styles

- scratchpad/blocks.css
- scratchpad/editor-blocks.css
- scratchpad/functions.php
This PR adds Gutenberg styles and support to the Scratchpad theme.
> Scratchpad: Add Gutenberg styles

- sketch/css/blocks.css
- sketch/css/editor-blocks.css
- sketch/functions.php
This PR adds Gutenberg styles and support to the Sketch theme.
> Sketch: Add Gutenberg support and styles

- textbook/assets/css/blocks.css
- textbook/assets/css/editor-blocks.css
- textbook/functions.php
This PR adds Gutenberg styles and support to Textbook.
> Textbook: Add Gutenberg styles and support to theme

- toujours/blocks.css
- toujours/editor-blocks.css
- toujours/functions.php
- toujours/style.css
This PR adds Gutenberg styles and support to Toujours.
> Toujours: Add Gutenberg styles and support

- dyad-2/css/blocks.css
- dyad-2/css/editor-blocks.css
Minor fixes to Gutenberg styles, including:
* RTL - fix alignment issue with file block button
* Update file button styles, so it's correct on hover
* Update styles for centred widgets on front-end and in editor
* Make custom editor style selectors more specific
* Correct font sizes in editor, and for quotes
> Dyad 2: Minor fixes to Gutenberg styles

- independent-publisher-2/css/blocks.css
- independent-publisher-2/css/editor-blocks.css
- independent-publisher-2/rtl.css
Minor fixes to Gutenberg implementation
* Update selectors for editor colour palette styles.
* Update comment widget styles to better match the comments in the theme.
* Correct the caption styles on the front-end and in the editor.
* Fix an alignment issue with wide video players in RTL styles.
* Fix the file link colour in the editor.
> Independent Publisher 2: Minor fixes to Gutenberg implementation

- intergalactic-2/blocks.css
- intergalactic-2/editor-blocks.css
* Correct selectors for buttons & custom palette colours.
* Make sure bullets are centred with centred widgets.
* Update comment widget styles to match comments.
* Remove empty selectors.
* Update verse font styles to italic.
> Intergalactic 2: Minor fixes to Gutenberg implementation

- ixion/blocks.css
- ixion/editor-blocks.css
Minor fixes to Gutenberg implementation
* Correcting caption size.
* Add space next to file button for RTL languages.
* Update selectors for buttons, custom colours.
* Make sure bullets are centred when widget blocks are centred.
* Remove empty selectors.
* Update comments widget to better match theme's comment styles.
> Ixion: Minor fixes to Gutenberg implementation

- libre-2/css/blocks.css
- libre-2/css/editor-blocks.css
Minor fixes to Gutenberg implementation, including: 
* Update selectors for buttons, custom colours.
* Correct caption styles on front-end and in editor.
* Remove spacing around figure elements in editor.
> Libre 2: Minor fixes to Gutenberg implementation

- libretto/css/blocks.css
- libretto/css/editor-blocks.css
- libretto/rtl.css
* Update selectors for buttons, custom colours.
* Reorganize CSS a bit to match other themes.
* Update table headers in theme to match front-end.
* Update comment widget block styles to better match the theme's comments.
* Styles file block link in the editor.
* Correct table cell text direction in theme's RTL styles.
> Libretto: Minor fixes to Gutenberg implementation

- lodestar/assets/css/blocks.css
- lodestar/assets/css/editor-blocks.css
Lodestar: Minor fixes to Gutenberg implementation, including:
* Correct missing state in colour selector.
* Fix selected button line height in editor.
* Update comment date size.
> Lodestar: Minor fixes to Gutenberg implementation

- photos/blocks.css
- photos/editor-blocks.css
- photos/functions.php
* Add support for responsive embeds, and styles to makes sure wide and full videos fill available space.
* Update button style selectors, and custom colour selectors, to make sure buttons have fallback when they have colour classes from previous themes.
* Centre text, bullets in centred widgets, to match editor styles.
* Update selector for links in editor.
* Align text left/right for full-aligned latest comments widget.
* Add a max-content width for the blocks in the editor.
* Remove border radius from code block in editor.
> Photos: Minor fixes to Gutenberg implementation

- rebalance/blocks.css
- rebalance/editor-blocks.css
* Update drop cap positioning.
* Add italics to verse block, to differentiate it.
* Update colour selectors, to account for :visited state.
* Update latest comments block to look more like theme's comments.
* Correct table header background colour; remove unneeded borders from table in editor.
* Make sure bullets are also centred for list-based widget blocks.
> Rebalance: Minor fixes to Gutenberg implementation

- sketch/css/blocks.css
- sketch/css/editor-blocks.css
* Correct button line height in editor, and border colours.
> Sketch: Minor fixes to Gutenberg implementation

- toujours/blocks.css
- toujours/editor-blocks.css
* Update drop cap size, to scale when font size does.
* Add visited states to custom colours.
* Position bullets inside of lists when widget blocks are centred.
> Toujours: Minor fixes to Gutenberg implementation

- textbook/assets/css/blocks.css
- textbook/assets/css/editor-blocks.css
* Update drop cap size, to scale when font size does.
> Textbook: Minor fixes to Gutenberg implementation

- dara/editor-blocks.css
- dara/style.css
Adjust specificity of styles related to the cover block, to prevent them from bleeding into editor elements. Bump version number.
> Dara: Adjust specificity of styles

- button-2/editor-blocks.css
This PR improves the appearance of the little fancy image corners in the editor preview.
> Button 2: Improve appearance of fancy image blocks in preview.

- radcliffe-2/inc/headstart/en-bar.json
- radcliffe-2/inc/headstart/en-cafe.json
- radcliffe-2/inc/headstart/en-mexican-restaurant.json
- radcliffe-2/inc/headstart/en-movie-theater.json
- radcliffe-2/inc/headstart/en-parking-garage.json
- radcliffe-2/inc/headstart/en.json
This update makes the homepage headstart content less theme-specific.
Fixes #509.
> Radcliffe 2: Update Headstart content

- radcliffe-2/inc/headstart/en.json
Looks like this file got out of sync with what's on WordPress.com -- this update makes sure they're the same.
Noticed while working on #509.
> Sync up headstart file with what's on SVN

- radcliffe-2/inc/wpcom-colors.php
- radcliffe-2/styles/colorful.css
- radcliffe-2/styles/modern.css
- radcliffe-2/styles/vintage.css
This update builds on an existing fix, and repeats the same styles for style packs and colour annotations that have been added to the menu in style.css.
See #435.
> Radcliffe 2: Add style pack, colour annotations to existing fix

- ixion/blocks.css
Swap out the styles for `.alignfull` elements.
> Ixion: Fix cover images with fixed background. See #499

- libretto/style.css
Update contact form styles:
* Align select, radio and multiple checkbox labels to match other fields
* Align single checkboxes with other fields (since they don't have typical labels).
* Add styles to the tel field to match the other text field.
Fixes #504.
> Libretto: Update the contact form styles

- radcliffe-2/assets/css/blocks.css
Noticed that the vintage style pack GB colours weren't complete - this PR fixes that!
> Radcliffe 2: Complete colour CSS for Vintage

- rebalance/inc/template-tags.php
- rebalance/portfolio-page.php
Add paging navigation to the porfolio project template
Fixes #273.
> Rebalance: Add paging navigation to the porfolio project template

- calm-business/sass/blocks/_blocks.scss
- calm-business/style-editor.css
- calm-business/style-editor.scss
- calm-business/style-rtl.css
- calm-business/style.css
Update quote block border styles to work better with the new styles planned for Gutenberg 5.2. 
See #594.
> Calm Business: Update quote block border styles

- friendly-business/sass/blocks/_blocks.scss
- friendly-business/style-editor.css
- friendly-business/style-editor.scss
- friendly-business/style-rtl.css
- friendly-business/style.css
> Friendly Business: Update quote block border styles

- sophisticated-business/sass/blocks/_blocks.scss
- sophisticated-business/style-editor.css
- sophisticated-business/style-editor.scss
- sophisticated-business/style-rtl.css
- sophisticated-business/style.css
> Sophisticated Business: Update quote block border styles

- sketch/js/jquery.flexslider.js
> Sketch: Updates Flexslider with jQuery output refactor.

- dara/assets/js/jquery.flexslider.js
> Dara: Updates Flexslider with jQuery output refactor.

- toujours/js/jquery.flexslider.js
> Toujours: Updates Flexslider with jQuery output refactor.

- textbook/assets/js/jquery.flexslider.js
> Textbook: Updates Flexslider with jQuery output refactor.

- shoreditch/js/jquery.flexslider.js
> Shoreditch: Updates Flexslider with jQuery output refactor.

- calm-business/sass/site/primary/_posts-and-pages.scss
- calm-business/style.css
- calm-business/style.scss
Fixes width issue on mobile for single post entry meta.
#688
> Closes #688 - fixes post entry meta width for mobile devices.

- elegant-business/functions.php
- professional-business/functions.php
> Enqueue Google fonts in the editor for Professional Business and Elegant Business

- sophisticated-business/sass/blocks/_blocks.scss
- sophisticated-business/style.css
> Sophisticated Business: Fix centred image

- modern-business/sass/blocks/_blocks.scss
- modern-business/style.css
- sophisticated-business/sass/blocks/_blocks.scss
- sophisticated-business/style.css
> Reduce the height and font size for cover block in Modern and Sophisticated Business

- professional-business/sass/blocks/_blocks.scss
- professional-business/style.css
- sophisticated-business/sass/blocks/_blocks.scss
- sophisticated-business/style-rtl.css
- sophisticated-business/style.css
> Fix centred align block for Sophisticated and Professional Business

- calm-business/sass/blocks/_blocks.scss
- calm-business/style-jetpack.css
- calm-business/style-rtl.css
- calm-business/style.css
- friendly-business/sass/blocks/_blocks.scss
- friendly-business/style-jetpack.css
- friendly-business/style.css
- modern-business/sass/blocks/_blocks.scss
- modern-business/style-jetpack.css
- modern-business/style-rtl.css
- modern-business/style.css
- sophisticated-business/sass/blocks/_blocks.scss
- sophisticated-business/style-jetpack.css
- sophisticated-business/style-rtl.css
- sophisticated-business/style.css
> Fix overflowing centred image in multiple themes

- elegant-business/sass/blocks/_blocks.scss
- elegant-business/sass/mixins/_utilities.scss
- elegant-business/sass/variables-site/_structure.scss
- elegant-business/style-editor-customizer.css
- elegant-business/style-editor.css
- elegant-business/style-jetpack.css
- elegant-business/style.css
- professional-business/sass/blocks/_blocks.scss
- professional-business/sass/mixins/_utilities.scss
- professional-business/sass/variables-site/_structure.scss
- professional-business/style-editor-customizer.css
- professional-business/style-editor.css
- professional-business/style-jetpack.css
- professional-business/style.css
> 752 columns block responsive widths

- calm-business/sass/typography/_headings.scss
- calm-business/style-editor.css
- calm-business/style-editor.scss
- calm-business/style.css
- friendly-business/sass/typography/_headings.scss
- friendly-business/style-editor.css
- friendly-business/style-editor.scss
- friendly-business/style.css
- modern-business/sass/typography/_headings.scss
- modern-business/style-editor.css
- modern-business/style-editor.scss
- modern-business/style.css
- sophisticated-business/style-editor.css
- sophisticated-business/style-editor.scss
> 747 h1 size fixes

- calm-business/sass/blocks/_blocks.scss
- calm-business/style-rtl.css
- calm-business/style.css
This PR simply fixes the font sizes in Calm Business to match the original design.
Fixes #803
> Calm Business: Fixing font sizes for Cover block

- elegant-business/sass/blocks/_blocks.scss
- elegant-business/style-rtl.css
- elegant-business/style.css
Fixes font sizes in Cover Block to match original design.
Fixes #803
> Elegant Business: Fixing font sizes in Cover Block 

- modern-business/sass/blocks/_blocks.scss
- modern-business/style-rtl.css
- modern-business/style.css
Fix font sizes for Cover Block to match original design
#803
> Modern Business: Fix font sizes for Cover Block

- professional-business/sass/blocks/_blocks.scss
- professional-business/style-rtl.css
- professional-business/style.css
Fix font sizes for Cover Block to match original design
Fixes #803
> Professional Business: Fix font sizes for Cover Block

- professional-business/sass/blocks/_blocks.scss
- professional-business/style-rtl.css
- professional-business/style.css
> Professional Business: Fixing font weight for headings in cover block

- calm-business/sass/blocks/_blocks.scss
- calm-business/sass/navigation/_next-previous.scss
- calm-business/sass/site/footer/_site-footer.scss
- calm-business/sass/site/primary/_archives.scss
- calm-business/sass/site/primary/_comments.scss
- calm-business/sass/site/primary/_posts-and-pages.scss
- calm-business/style-rtl.css
- calm-business/style.css
- calm-business/style.scss
> Closes #805 - structural fixes for responsive grid.

- professional-business/sass/navigation/_next-previous.scss
- professional-business/sass/site/primary/_posts-and-pages.scss
- professional-business/style-rtl.css
- professional-business/style.css
- professional-business/style.scss
- sophisticated-business/sass/navigation/_next-previous.scss
- sophisticated-business/sass/site/primary/_archives.scss
- sophisticated-business/sass/site/primary/_posts-and-pages.scss
- sophisticated-business/style-rtl.css
- sophisticated-business/style.css
- sophisticated-business/style.scss
@iamtakashi I've taken out the margin from the archive page as well, retaining the bottom margin for Sophisticated Business as well. 
Please give 1 final test and let me know when you are happy so I can get this merged and deployed.
> 806 entry meta structural fix

- calm-business/sass/blocks/_blocks.scss
- calm-business/style-rtl.css
- calm-business/style.css
- elegant-business/sass/blocks/_blocks.scss
- elegant-business/style-rtl.css
- elegant-business/style.css
- friendly-business/sass/blocks/_blocks.scss
- friendly-business/style-rtl.css
- friendly-business/style.css
- modern-business/sass/blocks/_blocks.scss
- modern-business/style-rtl.css
- modern-business/style.css
- professional-business/sass/blocks/_blocks.scss
- professional-business/style-rtl.css
- professional-business/style.css
- sophisticated-business/sass/blocks/_blocks.scss
- sophisticated-business/style-rtl.css
- sophisticated-business/style.css
Posts List block is coming soon, and this makes sure the block styled accordingly.
**Testing instruction:**
* Download or clone the [plugin](https://github.com/Automattic/posts-list-block).
* Activate the plugin and add the block to a page.
* Check the posts list on the page to see something odd or out of place.
**Note:**
The style is not meant to be match exactly with the themes' archive style as the markup is different. It's only meant to be something close to the style.
> All style variations: Add style for posts list block

- calm-business/sass/blocks/_blocks.scss
- calm-business/sass/mixins/_utilities.scss
- calm-business/sass/variables-site/_structure.scss
- calm-business/style-rtl.css
- calm-business/style.css
- elegant-business/sass/blocks/_blocks.scss
- elegant-business/style-rtl.css
- elegant-business/style.css
- friendly-business/sass/blocks/_blocks.scss
- friendly-business/sass/mixins/_utilities.scss
- friendly-business/sass/variables-site/_structure.scss
- friendly-business/style-rtl.css
- friendly-business/style.css
- modern-business/sass/blocks/_blocks.scss
- modern-business/sass/mixins/_utilities.scss
- modern-business/sass/variables-site/_structure.scss
- modern-business/style-rtl.css
- modern-business/style.css
- professional-business/sass/blocks/_blocks.scss
- professional-business/style-rtl.css
- professional-business/style.css
- sophisticated-business/sass/blocks/_blocks.scss
- sophisticated-business/sass/mixins/_utilities.scss
- sophisticated-business/sass/variables-site/_structure.scss
- sophisticated-business/style-rtl.css
- sophisticated-business/style.css
Fixes #813
**Testing:**
* Add a column block to a page. Make it to have more than 2 columns
* Add an image to each column (easier to spot the margin between columns)
* Test the responsiveness by changing the viewport from small to desktop size.
> Multiple Themes: Fix column block responsive pattern

- calm-business/sass/blocks/_blocks.scss
- calm-business/style.css
Centers media and text block when no alignment is set.
#815
> Closes #815 - fixes no alignment styles for media and text block.

- professional-business/functions.php
The file does exist, but not with that specific path. Enqueuing the script with the correct path prevents the console error.
After VS Before:
Fixes #700
> Professional Business: Correctly Import Block Editor Filters

- friendly-business/sass/blocks/_blocks.scss
- friendly-business/style-editor.css
- friendly-business/style-editor.scss
- friendly-business/style-rtl.css
- friendly-business/style.css
> Friendly Business: Fix link color inheriting for the Cover block

- sophisticated-business/sass/blocks/_blocks.scss
- sophisticated-business/style-editor.css
- sophisticated-business/style-editor.scss
- sophisticated-business/style-rtl.css
- sophisticated-business/style.css
> Sophisticated Business: Fix link color inheriting for the Cover block

- professional-business/sass/blocks/_blocks.scss
- professional-business/style-editor.css
- professional-business/style-editor.scss
- professional-business/style-rtl.css
- professional-business/style.css
> Professional Business: Fix link color inheriting for the Cover block

- elegant-business/sass/blocks/_blocks.scss
- elegant-business/style-editor.css
- elegant-business/style-editor.scss
- elegant-business/style-rtl.css
- elegant-business/style.css
> Elegant Business: Fix link color inheriting for the Cover block

- modern-business/sass/blocks/_blocks.scss
- modern-business/style-editor.css
- modern-business/style-editor.scss
- modern-business/style-rtl.css
- modern-business/style.css
> Modern Business: Fix link color inheriting for the Cover block

- independent-publisher-2/css/blocks.css
- Adds styles for Posts List Block
- Please test with using the block on a Page as well as Single Post.
#846
> Independent Publisher 2: adds posts list block styles

- modern-business/sass/variables-site/_colors.scss
- modern-business/style-rtl.css
- modern-business/style.css
> Modern Business: Fix button hover color issue

- friendly-business/sass/variables-site/_colors.scss
- friendly-business/style-rtl.css
- friendly-business/style.css
> Friendly Business: Fix button hover color issue

- elegant-business/sass/variables-site/_colors.scss
- elegant-business/style-rtl.css
- elegant-business/style.css
> Elegant Business: Fix button hover color issue

- professional-business/sass/variables-site/_colors.scss
- professional-business/style-rtl.css
- professional-business/style.css
> Professional Business: Fix button hover color issue

- radcliffe-2/assets/css/blocks.css
- radcliffe-2/styles/colorful.css
- radcliffe-2/styles/modern.css
- radcliffe-2/styles/vintage.css
> Radcliffe-2: Add posts list block style

- calm-business/sass/variables-site/_colors.scss
- calm-business/style-jetpack.css
- calm-business/style-rtl.css
- calm-business/style.css
- professional-business/sass/variables-site/_colors.scss
- professional-business/style.css
> Calm Business: Fix button hover color issue

- calm-business/style.css
- calm-business/style.scss
- elegant-business/style.css
- elegant-business/style.scss
- friendly-business/style.css
- friendly-business/style.scss
- independent-publisher-2/style.css
- modern-business/style.css
- modern-business/style.scss
- professional-business/style.css
- professional-business/style.scss
- radcliffe-2/style.css
- sophisticated-business/style.css
- sophisticated-business/style.scss
- Calm Business 1.4
- Elegant Business 1.2
- Friendly Business 1.2
- Independent Publisher 2.1.7
- Modern Business 1.2
- Professional Business 1.3
- Radcliffe 2 2.0.8
- Sophisticated Business 1.3
> Version increment for deploy

- sophisticated-business/sass/site/primary/_posts-and-pages.scss
- sophisticated-business/style-rtl.css
- sophisticated-business/style.css
Change contrast of Featured Tag for sticky posts from:
https://user-images.githubusercontent.com/908665/57973286-94d08d00-799e-11e9-8a2d-f4a5b87c14b0.png
To: 
https://cloudup.com/cWRiotFKLA9
#814
> Sophisticated Business: #814 - fixes contrast of featured tag for sticky posts.

- professional-business/style-editor.css
- professional-business/style-editor.scss
- professional-business/style-rtl.css
- fixes font-size mismatch for editor page titles.
#889
> Professional Business: #889 - fixes font-size mismatch for editor page titles.

- friendly-business/style-editor.css
- friendly-business/style-editor.scss
- friendly-business/style-rtl.css
- fixes font size mismatch in the editor for page titles.
#888
> Friendly Business: #888 - fixes font-size mismatch in the editor for page titles.

- modern-business/style-editor.css
- modern-business/style-editor.scss
- modern-business/style-rtl.css
- Fixes editor style for page title font size.
#887
> Modern Busienss: #887 - fixes editor font size mismatch for page titles.

- elegant-business/style-editor.css
- elegant-business/style-editor.scss
- elegant-business/style-rtl.css
> Elegant Business: #886 - fixes style mismatches for editor.

- calm-business/style-editor.css
- calm-business/style-editor.scss
- calm-business/style-rtl.css
- Fixes editor styles for page title and the content editor frame padding.
#885
> Calm Business: 885 Fixes editor styles for page title and content mismatches.

- calm-business/sass/blocks/_blocks.scss
- calm-business/sass/typography/_headings.scss
- calm-business/style-editor.css
- calm-business/style-editor.scss
- calm-business/style-rtl.css
- calm-business/style.css
Heading size adjustment. Fixes #891
> Calm Business: Heading Size Adjustment

- modern-business/sass/blocks/_blocks.scss
- modern-business/style-rtl.css
- modern-business/style.css
- adds 8% padding to the below 768px break point. I got this from the default style within the block, the existing style take over from the break point. It looks good when stacking as well.
#750
> Modern Business: #750 - fix for media and text block uneven margins

- elegant-business/sass/blocks/_blocks.scss
- elegant-business/sass/typography/_headings.scss
- elegant-business/style-editor.css
- elegant-business/style-editor.scss
- elegant-business/style-rtl.css
- elegant-business/style.css
> Elegant Business: Heading Size Adjustment

- friendly-business/sass/blocks/_blocks.scss
- friendly-business/sass/typography/_headings.scss
- friendly-business/style-editor.css
- friendly-business/style-editor.scss
- friendly-business/style-rtl.css
- friendly-business/style.css
> Friedlny Business: Heading Size Adjustment

- modern-business/sass/blocks/_blocks.scss
- modern-business/sass/site/primary/_posts-and-pages.scss
- modern-business/sass/typography/_headings.scss
- modern-business/style-editor.css
- modern-business/style-editor.scss
- modern-business/style-rtl.css
- modern-business/style.css
> Modern Business: Heading Size Adjustment

- professional-business/sass/blocks/_blocks.scss
- professional-business/sass/typography/_headings.scss
- professional-business/style-editor.css
- professional-business/style-editor.scss
- professional-business/style-rtl.css
- professional-business/style.css
> Professional Business: Heading Size Adjustment

- sophisticated-business/sass/blocks/_blocks.scss
- sophisticated-business/sass/typography/_headings.scss
- sophisticated-business/style-editor.css
- sophisticated-business/style-editor.scss
- sophisticated-business/style-rtl.css
- sophisticated-business/style.css
> Sophisticated Business: Heading Size Adjustment

- calm-business/sass/forms/_fields.scss
- calm-business/style.css
> Calm Business: Fix the overflowing Contact Form input fields

- elegant-business/style-editor.css
- elegant-business/style-editor.scss
> Elegant Business: Heading size adjustment for editor

- modern-business/sass/blocks/_blocks.scss
- modern-business/style-rtl.css
- modern-business/style.css
- Adds font weight of 300 to post titles in the Posts List Block.
Fixes #971
> Modern Business: fixes post title styles for Posts List Block

- calm-business/package-lock.json
- elegant-business/package-lock.json
- friendly-business/package-lock.json
- modern-business/package-lock.json
- professional-business/package-lock.json
- sophisticated-business/package-lock.json
- Updates package file to fix security issue with fstream.
> Fix fstream security notice

- elegant-business/sass/blocks/_blocks.scss
- elegant-business/style-rtl.css
- elegant-business/style.css
> Elegant Business: Fix lack of margin on Media & Text block contents

- friendly-business/sass/blocks/_blocks.scss
- friendly-business/style-rtl.css
- friendly-business/style.css
> Friendly Business: Fix the double margin on Media & Text block contents

- professional-business/sass/blocks/_blocks.scss
- professional-business/style-rtl.css
- professional-business/style.css
> Professional Business: Fix lack of margin on Media & Text block contents

- calm-business/sass/blocks/_blocks.scss
- calm-business/style-rtl.css
- calm-business/style.css
> Calm Business: Fix the lack of margin on Media & Text block contents

- friendly-business/sass/blocks/_blocks.scss
- friendly-business/sass/site/primary/_posts-and-pages.scss
- friendly-business/style-rtl.css
- friendly-business/style.css
Removes the top margin of the first child element of .entry-content.
See: #999
> Friendly Business: Make sure the first block has margin-top: 0

- modern-business/sass/blocks/_blocks.scss
- modern-business/sass/site/primary/_posts-and-pages.scss
- modern-business/style-rtl.css
- modern-business/style.css
Removes the top margin of the first child element of .entry-content.
See: #1000
> Modern Business: Make sure the first block has margin-top: 0

- elegant-business/sass/blocks/_blocks.scss
- elegant-business/sass/site/primary/_posts-and-pages.scss
- elegant-business/style-rtl.css
- elegant-business/style.css
Removes the top margin of the first child element of `.entry-content`.
See: #998
> Elegant Business: Remove the top margin of the first child element

- professional-business/sass/blocks/_blocks.scss
- professional-business/sass/site/primary/_posts-and-pages.scss
- professional-business/style-rtl.css
- professional-business/style.css
Removes the top margin of the first child element of .entry-content.
See: #1002
> Professional Business: Make sure the first block has margin-top: 0

- sophisticated-business/sass/blocks/_blocks.scss
- sophisticated-business/sass/site/primary/_posts-and-pages.scss
- sophisticated-business/style-rtl.css
- sophisticated-business/style.css
Removes the top margin of the first child element of .entry-content.
See: #1003
> Sophisticated Business: Make sure the first block has margin-top: 0

- calm-business/style.css
- calm-business/style.scss
- elegant-business/style.css
- elegant-business/style.scss
- friendly-business/style.css
- friendly-business/style.scss
- modern-business/style.css
- modern-business/style.scss
- professional-business/style.css
- professional-business/style.scss
- sophisticated-business/style.css
- sophisticated-business/style.scss
Calm Business 1.6
Elegant Business 1.4
Friendly Business 1.4
Modern Business 1.4
Professional Business 1.5
Sophisticated Business 1.5
Various fixes from https://github.com/Automattic/themes/projects/2
> Deploy packaged for release

- modern-business/style-editor.css
- modern-business/style-editor.scss
- modern-business/style-rtl.css
> Modern Business: Make sure there is whitespace around text column all the time

- modern-business/style-editor.css
- modern-business/style-editor.scss
Additional fix for something I overlooked in the #1013
> Modern Business: Additional Fix for issue 1012

- modern-business/style-rtl.css
- modern-business/style.css
- modern-business/style.scss
Modern Business 1.5: whitespace fixes. Packaged for deploy.
> Modern Business 1:5

- .gitignore
- _dsgnsystm/package-lock.json
- _dsgnsystm/package.json
- calm-business/package-lock.json
- calm-business/style-rtl.css
- elegant-business/package-lock.json
- friendly-business/package-lock.json
- friendly-business/style-rtl.css
- modern-business/package-lock.json
- professional-business/package-lock.json
- professional-business/style-rtl.css
- sophisticated-business/package-lock.json
- sophisticated-business/style-rtl.css
Updates npm warnings and lodash to the latest version.
> Updates lodash version and fixes npm errors.

- redhill/package-lock.json
- redhill/style-rtl.css
Updates lodash dependancy in package lock file.
> Redhill lodash dependancy update.

- _dsgnsystm/sass/blocks/cover/_editor.scss
- _dsgnsystm/sass/blocks/cover/_style.scss
- _dsgnsystm/style-editor.css
- _dsgnsystm/style-rtl.css
- _dsgnsystm/style.css
- Fix text-align for H2 in cover block
Fixes: #1080
> _dsgnsystm: Fix text-align for H2 in cover block

- _dsgnsystm/sass/elements/_config.scss
- _dsgnsystm/sass/elements/_forms.scss
- _dsgnsystm/style-rtl.css
- _dsgnsystm/style.css
Fixes issue #1083 
**Before:**
**After:**
> _dsgnsystm: Fix padding for form fields

- _dsgnsystm/sass/blocks/pullquote/_editor.scss
- _dsgnsystm/sass/blocks/pullquote/_style.scss
- _dsgnsystm/sass/blocks/utilities/_style.scss
- _dsgnsystm/style-editor.css
- _dsgnsystm/style-rtl.css
- _dsgnsystm/style.css
- Fixes text alignment in pullquote block
- Fixes left padding on blockquotes in pullquote block
**Before**
**After**
#1087
> _dsgnsystm: Fix text-alignment and padding in pullquote block

- varia/package-lock.json
> Varia lodash package update.

- redhill/inc/headstart/en.json
> Redhill: Add Headstart annotations

- varia/sass/base/_editor.scss
- varia/style-editor.css
Fixes #1111 
**Testing Instruction**
* Checkout the branch.
* Edit a post or a page.
* Check the font size of the title is the same as the front of the site.
> Varia: Sets font size for title block sama as body

- varia/sass/blocks/_editor.scss
- varia/sass/blocks/media-text/_editor.scss
- varia/sass/blocks/media-text/_style.scss
- varia/style-editor.css
- varia/style-rtl.css
- varia/style.css
Have links inherit the color only when the block (Media & Text or Paragraph) are using a background color.
This splits the commits at #1122 into two separate PRs. This one provides a fix for Varia.
> Varia: Revise PR #1122

- redhill/style-editor.css
- redhill/style-rtl.css
- redhill/style.css
- varia/sass/blocks/_editor.scss
- varia/sass/blocks/media-text/_editor.scss
- varia/sass/blocks/media-text/_style.scss
- varia/sass/blocks/paragraph/_editor.scss
- varia/sass/blocks/paragraph/_style.scss
- varia/style-editor.css
- varia/style-rtl.css
- varia/style.css
Plus Rebuild Redhill
See #1113
> Varia: Have links inherit the color only when the block (Media & Text or Paragrpah) are using a background color

- redhill/sass/_extra-child-theme.scss
- redhill/style.css
Adds underlines to text-links and blocks with background colors.
Fixes: #1113
> Redhill: Add underline to text-links

- varia/print.css
- varia/print.scss
- varia/style-editor.css
This is a part of to fix #1143
> Varia: Remove Invalid US-ASCII character

- redhill/sass/_config-child-theme-deep.scss
- redhill/sass/_extra-child-theme.scss
- redhill/style-editor.css
- redhill/style-rtl.css
- redhill/style.css
This updates Redhill after Varia added Posts List block support and footer menu. Also fixes several minor issues. Fixes #1110, #1117
> Redhill: Add posts list support and footer navigation

- redhill/sass/_extra-child-theme.scss
- redhill/style-rtl.css
- redhill/style.css
This removes the link underline from site title.
> Redhill: Remove link underline from site title

- modern-business/footer.php
- modern-business/header.php
- modern-business/inc/fse-template-data.php
Refactors code to align it with latest FSE changes.
Fixes https://github.com/Automattic/wp-calypso/issues/35009
> Modern Business: remove wp_template population

- stow/package-lock.json
- stow/sass/_extra-child-theme.scss
- stow/style-rtl.css
- stow/style.css
- Removes the left/right negative margins from the social-menu `ul`
- Without them, the horizontal scrolling on mobile issue goes away :-) 
#1180
> Stow: Fix horizontal scrolling issue on Mobile, fixes #1180

- varia/functions.php
> Varia: Change content width to match width default content width

- varia/sass/blocks/columns/_style.scss
- varia/style-rtl.css
- varia/style.css
Fixes #1178 
**Before**
**After**
> Varia: Add bottom margin to column cells for mobile

- varia/sass/blocks/quote/_editor.scss
- varia/sass/blocks/quote/_style.scss
- varia/sass/blocks/utilities/_editor.scss
- varia/style-editor.css
- varia/style-rtl.css
- varia/style.css
Fixes #1203 
This also fixes the citation colour to make sure it's readable when it has a background colour.
**Before:**
**After:**
> Varia: Fix quote font in editor and colour of citation

- calm-business/functions.php
- calm-business/sass/blocks/_blocks.scss
- calm-business/style-rtl.css
- calm-business/style.css
> Calm Business: Add missing editor color palette support

- calm-business/sass/blocks/_blocks.scss
- calm-business/style-editor.css
- calm-business/style-editor.scss
- calm-business/style-rtl.css
- calm-business/style.css
> Calm Business: Fix the cover h2 alignment

- elegant-business/functions.php
> Elegant Business: Add missing editor color palette support

- professional-business/functions.php
> Professional Business: Add missing editor color palette support

- professional-business/sass/blocks/_blocks.scss
- professional-business/style-editor.css
- professional-business/style-editor.scss
- professional-business/style-rtl.css
- professional-business/style.css
> Professional Business: Fix the cover headings alignment

- friendly-business/functions.php
> Friendly Business: Add missing editor color palette support

- elegant-business/sass/blocks/_blocks.scss
- elegant-business/style-editor.css
- elegant-business/style-editor.scss
- elegant-business/style-rtl.css
- elegant-business/style.css
> Elegant Business: Fix the cover h2 alignment

- sophisticated-business/functions.php
- sophisticated-business/sass/blocks/_blocks.scss
- sophisticated-business/style-editor.css
- sophisticated-business/style-editor.scss
- sophisticated-business/style-rtl.css
- sophisticated-business/style.css
> Sophisticated Business: Add missing editor color palette support

- friendly-business/sass/blocks/_blocks.scss
- friendly-business/style-editor.css
- friendly-business/style-editor.scss
- friendly-business/style-rtl.css
- friendly-business/style.css
>  Friendly Business: Fix the cover headings alignment 

- modern-business/sass/blocks/_blocks.scss
- modern-business/style-editor.css
- modern-business/style-editor.scss
- modern-business/style-rtl.css
- modern-business/style.css
> Modern Business: Fix the cover headings alignment

- sophisticated-business/sass/blocks/_blocks.scss
- sophisticated-business/style-editor.css
- sophisticated-business/style-editor.scss
- sophisticated-business/style-rtl.css
- sophisticated-business/style.css
> Sophisticated Business: Fix the cover headings alignment

- varia/sass/blocks/cover/_style.scss
- varia/style-rtl.css
- varia/style.css
Fixes #1224 
**Before:**
**After:**
> Varia: Add vertical margins to elements on cover block

- varia/sass/blocks/group/_style.scss
- varia/style-rtl.css
- varia/style.css
Fixes #1214 
**Before:**
**After:**
> Varia: Add consistant margin to element in group block

- varia/sass/blocks/utilities/_style.scss
- varia/style-rtl.css
- varia/style.css
> Varia: Make normal font size the same as default size

- varia/sass/blocks/quote/_style.scss
> Varia: Fix quote font setting

- brompton/footer.php
- brompton/sass/_extra-child-theme.scss
- brompton/style-editor.css
- brompton/style-rtl.css
- brompton/style.css
- Refactor responsive logic for .alignwide, alignfull, and normal width blocks. 
- Adjust wrappers in footer to apply new responsive logic.
#1246
> Brompton: Refactor responsive logic for better nesting behavior

- coutoire/sass/_extra-child-theme.scss
- coutoire/style-editor.css
- coutoire/style-rtl.css
- coutoire/style.css
- Refactor responsive logic for .alignwide, alignfull, and normal width blocks. 
- Fix negative margin issue in main menu.
#1246
> Coutoire: Refactor responsive logic for better nested block behavior.

- hever/sass/_extra-child-theme.scss
- hever/style-editor.css
- hever/style-rtl.css
- hever/style.css
- Refactor responsive logic .alignwide, alignfull, and normal width blocks. 
- Fix negative margins issue in header.
#1246
> Hever: Refactor responsive logic for better nested block behavior

- leven/style-editor.css
- leven/style-rtl.css
- leven/style.css
- Refactor responsive logic for .alignwide, alignfull, and normal width blocks.
#1246
> Leven: Refactor responsive logic for better nested block behavior

- morden/archive.php
- morden/header.php
- morden/package-lock.json
- morden/package.json
- morden/page.php
- morden/sass/_extra-child-theme.scss
- morden/style-editor.css
- morden/style-rtl.css
- morden/style.css
- morden/template-parts/content/content-excerpt.php
- morden/template-parts/content/content-none.php
- morden/template-parts/content/content-page.php
- morden/template-parts/content/content-single.php
- morden/template-parts/content/content.php
- Refactor responsive logic .alignwide, alignfull, and normal width blocks. 
- Revises responsive shadow and background-color styles to work with refactor. 
- Removes responsive-align class from `.entry-header` wrappers in all _content-*.php_ template files.
#1246
> Morden: Refactor responsive logic for better nested block behavior

- redhill/sass/_extra-child-theme.scss
- redhill/style-editor.css
- redhill/style-rtl.css
- redhill/style.css
- Refactor responsive logic for .alignwide, alignfull, and normal width blocks.
#1246
> Redhill: Refactor responsive logic for better nested block behavior.

- rockfield/footer.php
- rockfield/package-lock.json
- rockfield/package.json
- rockfield/sass/_extra-child-theme.scss
- rockfield/style-editor.css
- rockfield/style-rtl.css
- rockfield/style.css
- Update npm dependencies
- Refactor responsive logic and update footer menu markup to work with refactor
#1246
> Rockfield: Refactor responsive logic for better nested block behavior

- stow/header.php
- stow/package-lock.json
- stow/package.json
- stow/sass/_extra-child-theme.scss
- stow/style-editor.css
- stow/style.css
- Refactor responsive logic for .alignwide, alignfull, and normal width blocks. 
- update header menu markup to work with refactor. 
- Update npm dependencies
#1246
> Stow: Refactor responsive logic for better nested block behavior

- stratford/functions.php
- stratford/package-lock.json
- stratford/style-editor.css
- stratford/style.css
- Fix missing google font variable PHP warning
- Recompile responsive logic from upstream Varia enhancement
- Update npm dependencies
#1246
> Stratford: Refactor responsive logic for better nested block behavior.

- affinity/style.css
> Affinity: Adds retire status to stylesheet.

- varia/sass/vendors/_jetpack.scss
- varia/style-rtl.css
- varia/style.css
- varia/style.scss
- Adds top and bottom margins to elements within the Jetpack subscribe form. 
- Remove duplicate vendors import. 
#1271
> Varia: Add spacing between Jetpack subscribe form and submit button

- morden/header.php
- morden/sass/_extra-child-theme.scss
- morden/style-rtl.css
- morden/style.css
- Revises the method for constricting the width of the `#page` wrapper.
Discovered after merging #1246
> Morden: Revising layout styles to work with the improved responsive logic

- stow/sass/_extra-child-theme.scss
- stow/style-rtl.css
- stow/style.css
> Stow: Fix horizontal scrolling issue on Desktop

- maywood/package-lock.json
- maywood/package.json
- maywood/style-editor.css
- maywood/style-rtl.css
- maywood/style.css
- rivington/package-lock.json
- rivington/package.json
- rivington/style-editor.css
- rivington/style-rtl.css
- rivington/style.css
Updates package dependancies and recompiles to the latest Varia.
> Updates dependancies for Maywood and Rivington.

- varia/package.json
- varia/readme.txt
- varia/style-rtl.css
- varia/style.css
- varia/style.scss
> Varia: version increment to 1.1.1 for prior fix.

- rivington/sass/style-child-theme.scss
- rivington/style-rtl.css
- rivington/style.css
> Rivington: Update the description

- balasana/functions.php
- balasana/package-lock.json
- balasana/package.json
- balasana/sass/style-child-theme.scss
- balasana/style-rtl.css
- balasana/style.css
Roboto Condensed wasn't properly loaded
> Balasana: Fix typo in `balasana_fonts_url()`

- maywood/sass/_full-site-editing-editor.scss
- maywood/sass/_full-site-editing.scss
- maywood/sass/style-child-theme-editor.scss
- maywood/style-editor.css
- maywood/style-rtl.css
- maywood/style.css
- varia/sass/full-site-editing/_editor.scss
- varia/sass/full-site-editing/_imports.scss
- varia/style-editor.css
- varia/style-rtl.css
- varia/style.css
- varia/style.scss
Update the Navigation Menu style in both Varia, and via both inheritance and overrides in Maywood.
Test steps and screenshots over at https://github.com/Automattic/wp-calypso/pull/35880
> Full Site Editing: Update Navigation Menu style on Varia and Maywood

- mayland/sass/_config-child-theme-deep.scss
- mayland/sass/_extra-child-theme.scss
- mayland/style-rtl.css
- mayland/style.css
> Mayland: Update the header layout to horizontal

- varia/sass/vendors/_jetpack.scss
- varia/style-rtl.css
- varia/style.css
Fixes #1276 
**Before:**
**After:**
> Varia: Add a better default to Mailchimp subscription form

- varia/sass/components/content/_entry-content.scss
- varia/style-rtl.css
- varia/style.css
Fixes #1405 
**Before:**
**After:**
> Varia: More link fix

- varia/sass/blocks/utilities/_editor.scss
- varia/style-editor.css
> Varia: Adjust vertical margins between blocks

- varia/sass/blocks/media-text/_editor.scss
- varia/style-editor.css
> Varia: Make sure link is visible inside media & text block with background

- varia/sass/blocks/quote/_editor.scss
- varia/sass/blocks/quote/_style.scss
- varia/sass/blocks/utilities/_editor.scss
- varia/sass/blocks/utilities/_style.scss
- varia/style-editor.css
- varia/style-rtl.css
- varia/style.css
> Varia: Make sure quote border is visible with background

- varia/sass/blocks/quote/_editor.scss
- varia/sass/blocks/quote/_style.scss
- varia/sass/blocks/separator/_editor.scss
- varia/sass/blocks/separator/_style.scss
- varia/style-editor.css
- varia/style-rtl.css
- varia/style.css
I caught some cases I overlooked in issues #1429, #1433, and #1435
> Varia Leftover fix for #1429, #1433, and #1435

- varia/footer.php
- Move the Privay Policy link to just after the copyright info.
Before | After
------------ | ------------
Fixes: #1401
> Varia: Fix privacy policy positioning

- maywood/languages/maywood.pot
- maywood/package.json
- maywood/sass/style-child-theme.scss
- maywood/style-editor.css
- maywood/style-rtl.css
- maywood/style.css
- varia/package.json
- varia/style-rtl.css
- varia/style.css
- varia/style.scss
Bumps Varia to version 1.2.2.
Bumps Maywood to version 1.1.2.
> Varia and Maywood: bump theme versions

- varia/sass/blocks/_editor.scss
- varia/sass/blocks/latest-comments/_editor.scss
- varia/sass/blocks/latest-comments/_style.scss
- varia/sass/blocks/latest-posts/_style.scss
- varia/sass/blocks/list/_editor.scss
- varia/sass/components/comments/_comments.scss
- varia/sass/components/header/_site-main-navigation.scss
- varia/sass/components/header/_site-social-navigation.scss
- varia/style-editor.css
- varia/style-rtl.css
- varia/style.css
> Varia: Reset side padding for list items

- varia/package.json
- varia/sass/child-theme/style-child-theme.scss
- varia/style-rtl.css
- varia/style.css
- varia/style.scss
- Add `auto-loading-homepage` tag to main stylesheet header.
- Add `auto-loading-homepage` tag to child-theme stylesheet header for future child themes.
- Minor version bump 
> Varia: Add `auto-loading-homepage` tag to stylesheet, minor version bump

- maywood/package.json
- maywood/sass/style-child-theme.scss
- maywood/style-editor.css
- maywood/style-rtl.css
- maywood/style.css
- Add `auto-loading-homepage` tag to main stylesheet header.
- Compiles latest changes from Varia
- Minor version bump 
> Maywood: Add `auto-loading-homepage` tag to main stylesheet, version bump

- alves/functions.php
- alves/package.json
- alves/sass/_extra-child-theme.scss
- alves/sass/style-child-theme.scss
- alves/style-editor.css
- alves/style-rtl.css
- alves/style.css
* Add auto-loading-homepage tag to main stylesheet header.
* Enable Google fonts
* Style update in Latest posts block
> Alves: Add `auto-loading-homepage` tag to stylesheet, minor version bump

- balasana/package-lock.json
- balasana/sass/style-child-theme.scss
- balasana/style-editor.css
- balasana/style-rtl.css
- balasana/style.css
* Add auto-loading-homepage tag to main stylesheet header.
* Minor version bump to 1.0.2
> Balasana: Add auto-loading-homepage tag to stylesheet, minor version bump

- stratford/package-lock.json
- stratford/sass/style-child-theme.scss
- stratford/style-editor.css
- stratford/style-rtl.css
- stratford/style.css
> Startford: Add auto-loading-homepage tag to stylesheet, minor version bump

- rockfield/package.json
- rockfield/sass/_extra-child-theme.scss
- rockfield/sass/style-child-theme.scss
- rockfield/style-editor.css
- rockfield/style-rtl.css
- rockfield/style.css
> Rockfield: Add auto-loading-homepage tag to stylesheet, minor version bump

- stow/package.json
- stow/sass/_extra-child-theme.scss
- stow/sass/style-child-theme.scss
- stow/style-editor.css
- stow/style-rtl.css
- stow/style.css
* Minor bug fix for main navigation
> Stow: Add auto-loading-homepage tag to stylesheet, minor version bump

- shawburn/package.json
- shawburn/sass/_extra-child-theme.scss
- shawburn/sass/style-child-theme.scss
- shawburn/style-editor.css
- shawburn/style-rtl.css
- shawburn/style.css
> Shawburn: Add auto-loading-homepage tag to stylesheet, minor version bump

- rivington/package.json
- rivington/sass/_extra-child-theme.scss
- rivington/sass/style-child-theme.scss
- rivington/style-editor.css
- rivington/style-rtl.css
- rivington/style.css
> Rivington: Add auto-loading-homepage tag to stylesheet, minor version bump

- varia/sass/child-theme/style-child-theme.scss
- varia/style-rtl.css
- varia/style.css
- varia/style.scss
- Add `full-site-editing` tag for the showcase
- Minor version bump
> Varia: Add fse tags, and version bump

- maywood/sass/style-child-theme.scss
- maywood/style-rtl.css
- maywood/style.css
- Add `full-site-editing` tag for the showcase
- Minor version bump
> Maywood: Add fse tag for showcase, and minor version bump

- balasana/package-lock.json
- balasana/package.json
- balasana/sass/_extra-child-theme.scss
- balasana/sass/style-child-theme.scss
- balasana/style-rtl.css
- balasana/style.css
> Balasana: Fix stretching logo

- barnsbury/package-lock.json
- barnsbury/package.json
- barnsbury/sass/_extra-child-theme.scss
- barnsbury/sass/style-child-theme.scss
- barnsbury/style-editor.css
- barnsbury/style-rtl.css
- barnsbury/style.css
> Barnsbury: Add auto-loading-homepage tag to stylesheet, minor version bump

- brompton/footer.php
- brompton/package.json
- brompton/sass/style-child-theme.scss
- brompton/style-editor.css
- brompton/style-rtl.css
- brompton/style.css
- Add `auto-loading-homepage` tag for the showcase
- Minor version bump
- Fix Privacy Policy link positioning
- Fix list display in Widgets Blocks
> Brompton: Add auto-loading-homepage tag to stylesheet, minor version bump

- exford/package-lock.json
- exford/package.json
- exford/sass/_extra-child-theme.scss
- exford/sass/style-child-theme.scss
- exford/style-editor.css
- exford/style-rtl.css
- exford/style.css
> Exford: Add auto-loading-homepage tag to stylesheet, minor version bump

- hever/package-lock.json
- hever/package.json
- hever/sass/_extra-child-theme.scss
- hever/sass/style-child-theme.scss
- hever/style-editor.css
- hever/style-rtl.css
- hever/style.css
> Hever: Add auto-loading-homepage tag to stylesheet, minor version bump

- redhill/package-lock.json
- redhill/package.json
- redhill/sass/_extra-child-theme.scss
- redhill/style-editor.css
- redhill/style-rtl.css
- redhill/style.css
> Redhill: Add auto-loading-homepage tag to stylesheet, minor version bump

- morden/package-lock.json
- morden/package.json
- morden/sass/_extra-child-theme.scss
- morden/sass/style-child-theme.scss
- morden/style-editor.css
- morden/style-rtl.css
- morden/style.css
> Morden: Add auto-loading-homepage tag to stylesheet, minor version bump

- coutoire/package-lock.json
- coutoire/package.json
- coutoire/sass/style-child-theme.scss
- coutoire/style-editor.css
- coutoire/style-rtl.css
- coutoire/style.css
> Coutoire: Add auto-loading-homepage tag to stylesheet, minor version bump

- morden/package-lock.json
- morden/package.json
- morden/sass/_extra-child-theme.scss
- morden/sass/style-child-theme.scss
- morden/style-rtl.css
- morden/style.css
* Minor version bump to 1.1.3
* Container max width change.
> Morden: Add auto-loading-homepage tag to stylesheet, minor version bump again

- dalston/package-lock.json
- dalston/package.json
- dalston/sass/style-child-theme.scss
- dalston/style-editor.css
- dalston/style-rtl.css
- dalston/style.css
> Dalston: Add auto-loading-homepage tag to stylesheet, minor version bump

- leven/package-lock.json
- leven/package.json
- leven/sass/style-child-theme.scss
- leven/style-editor.css
- leven/style-rtl.css
- leven/style.css
> Leven: Add auto-loading-homepage tag to stylesheet, minor version bump

- mayland/package-lock.json
- mayland/package.json
- mayland/sass/_extra-child-theme.scss
- mayland/sass/style-child-theme.scss
- mayland/style-editor.css
- mayland/style-rtl.css
- mayland/style.css
> Mayland: Add auto-loading-homepage tag to stylesheet, minor version bump

- calm-business/package-lock.json
- calm-business/package.json
- calm-business/sass/blocks/_blocks.scss
- calm-business/style-editor.css
- calm-business/style-rtl.css
- calm-business/style.css
- calm-business/style.scss
> Calm Business: Fix media & text block ordering for gutenberg 6.7

- elegant-business/package-lock.json
- elegant-business/package.json
- elegant-business/sass/blocks/_blocks.scss
- elegant-business/style-editor.css
- elegant-business/style-rtl.css
- elegant-business/style.css
- elegant-business/style.scss
> Elegant Business: Fix media & text block ordering for Gutenberg 6.7

- friendly-business/package-lock.json
- friendly-business/package.json
- friendly-business/sass/blocks/_blocks.scss
- friendly-business/style-editor.css
- friendly-business/style-rtl.css
- friendly-business/style.css
- friendly-business/style.scss
> Friendly Business: Fix media & text block ordering for Gutenberg 6.7

- modern-business/package-lock.json
- modern-business/package.json
- modern-business/sass/blocks/_blocks.scss
- modern-business/style-rtl.css
- modern-business/style.css
- modern-business/style.scss
> Modern Business: Fix media & text block ordering for Gutenberg 6.7

- professional-business/package-lock.json
- professional-business/package.json
- professional-business/sass/blocks/_blocks.scss
- professional-business/style-editor.css
- professional-business/style-rtl.css
- professional-business/style.css
- professional-business/style.scss
> Professional-business: Fix media & text block ordering for Gutenberg 6.7

- sophisticated-business/package-lock.json
- sophisticated-business/package.json
- sophisticated-business/sass/blocks/_blocks.scss
- sophisticated-business/style-editor.css
- sophisticated-business/style-rtl.css
- sophisticated-business/style.css
- sophisticated-business/style.scss
> Sophisticated Business: Fix media & text block ordering for Gutenberg 6.7

- varia/sass/base/_clearings.scss
- varia/style-rtl.css
- varia/style.css
> Varia: Fix float clearing

- morden/sass/_extra-child-theme.scss
- morden/style-rtl.css
- morden/style.css
> Morden: Fix footer side padding on mobile

- stow/sass/_extra-child-theme.scss
- stow/style-rtl.css
- stow/style.css
> Stow: Make sure there is top padding for content

- stratford/functions.php
- stratford/js/fixed-header-spacing.js
- stratford/sass/_extra-child-theme.scss
- stratford/style-rtl.css
- stratford/style.css
Fixes #1529 This PR improves the fixed header with the following.
* Support dynamic header height with a logo
* Unfix the header in mobile
> Stratford: Better fixed header

- varia/sass/components/comments/_comments.scss
- varia/style-rtl.css
- varia/style.css
Fixes #1409
**Before:**
**After:**
> Varia: Make sure long username not running into avatar

- rockfield/sass/_extra-child-theme.scss
- rockfield/style-rtl.css
- rockfield/style.css
Fixes #1395
**Before**
**After**
> Rockfield: Make sure footer layout stays the same all the time

- alves/sass/style-child-theme.scss
- balasana/sass/style-child-theme.scss
- barnsbury/sass/style-child-theme.scss
- brompton/sass/style-child-theme.scss
- coutoire/sass/style-child-theme.scss
- dalston/sass/style-child-theme.scss
- exford/sass/style-child-theme.scss
- hever/sass/style-child-theme.scss
- leven/sass/style-child-theme.scss
- mayland/sass/style-child-theme.scss
- maywood/sass/style-child-theme.scss
- morden/sass/style-child-theme.scss
- rivington/sass/style-child-theme.scss
- rockfield/sass/style-child-theme.scss
- shawburn/sass/style-child-theme.scss
- stow/sass/style-child-theme.scss
- stratford/sass/style-child-theme.scss
- varia/functions.php
- varia/readme.txt
- varia/sass/child-theme/style-child-theme.scss
- varia/style.scss
**Do not merge until `paAmJe-QS-p2` is settled.**
This PR updates the name we use for the global styles feature. Note that I haven't recompiled all the child themes because this is just a tag change. The important bit is the `add_theme_support` in `varia/functions.php`.
> Update global styles namespace

- alves/sass/_config-child-theme-deep.scss
- alves/style-rtl.css
- alves/style.css
> Alves: Unset measuere variable default

- balasana/sass/_config-child-theme-deep.scss
- balasana/style-rtl.css
- balasana/style.css
> Balasana: Unset measuere variable default

- barnsbury/sass/_config-child-theme-deep.scss
- barnsbury/style-rtl.css
- barnsbury/style.css
> Barnsbury: Unset measuere variable default

- barnsbury/sass/_config-child-theme-deep.scss
- brompton/sass/_config-child-theme-deep.scss
- brompton/style-rtl.css
- brompton/style.css
> Brompton: Unset measuere variable default

- dalston/sass/_config-child-theme-deep.scss
- dalston/style-rtl.css
- dalston/style.css
> Dalston: Unset measuere variable default

- exford/sass/_config-child-theme-deep.scss
- exford/style-rtl.css
- exford/style.css
> Exford: Unset measuere variable default

- hever/sass/_config-child-theme-deep.scss
- hever/style-rtl.css
- hever/style.css
> Hever: Unset measuere variable default

- mayland/sass/_config-child-theme-deep.scss
- mayland/style-rtl.css
- mayland/style.css
> Mayland: Unset measuere variable default

- maywood/sass/_config-child-theme-deep.scss
- maywood/style-rtl.css
- maywood/style.css
> Maywood: Unset measuere variable default

- morden/sass/_config-child-theme-deep.scss
- morden/style-rtl.css
- morden/style.css
> Morden: Unset measuere variable default

- redhill/sass/_config-child-theme-deep.scss
- redhill/style-rtl.css
- redhill/style.css
> Redhill: Unset measuere variable default

- rivington/sass/_config-child-theme-deep.scss
- rivington/style-rtl.css
- rivington/style.css
> Rivington: Unset measuere variable default

- shawburn/sass/_config-child-theme-deep.scss
- shawburn/style-rtl.css
- shawburn/style.css
> Shawburn: Unset measuere variable default

- stow/sass/_config-child-theme-deep.scss
- stow/style-rtl.css
- stow/style.css
> Stow: Unset measuere variable default

- stratford/sass/_config-child-theme-deep.scss
- stratford/style-rtl.css
- stratford/style.css
> Stratford: Unset measuere variable default

- varia/sass/child-theme/_config-child-theme-deep.scss
> Varia: Unset measure variable default for child themes

- rockfield/sass/_config-child-theme-deep.scss
- rockfield/style-rtl.css
- rockfield/style.css
> Rockfield: Unset measuere variable default

- varia/sass/vendors/_jetpack.scss
- varia/style-rtl.css
- varia/style.css
Fixes #1605 
**Before:**
**After:**
> Varia: Remove unnecessary gaps in Jetpack Business Hours on front-end

- dalston/block-extends/extend-cover-block.css
- Fix Hover Reveal Cover Block Style to work with gradients.
- Fix editor styles to match frontend.
**Before**
**After**
**Editor**
Fixes: #1636
> Dalston: Fix Hover Reveal Cover Block Style to work with gradients.

- balasana/sass/style-child-theme-woocommerce.scss
- balasana/style-woocommerce-rtl.css
- balasana/style-woocommerce.css
- Applies a simpler fix to the earlier solution.
Fixes: #1637
> Balasana: Add a cleaner flex-box solution.

- apostrophe-2/content-single.php
This adds the `post_class()` function to single posts.
Fixes #1386.
> Add post_class function to single posts

- radcliffe-2/contact-info/contact-info-functions.php
> Radcliffe 2: Mask Contact Info email from bots

- alves/package-lock.json
- alves/style-editor.css
- alves/style-rtl.css
- alves/style.css
- exford/package-lock.json
- exford/style-editor.css
- exford/style-rtl.css
- exford/style.css
- maywood/package-lock.json
- maywood/style-editor.css
- maywood/style-rtl.css
- maywood/style.css
- shawburn/package-lock.json
- shawburn/style-editor.css
- shawburn/style-rtl.css
- shawburn/style.css
Since we added a few changes to varia for FSE themes, I've rebuild the following themes as well:
- Maywood
- Shawburn
- Exford
- Alves
- (Hever is already up to date)
(Did I miss any?)
> Build FSE themes again

- stow/languages/stow.pot
- stow/package-lock.json
- stow/package.json
- stow/sass/style-child-theme.scss
- stow/style-rtl.css
- stow/style.css
> Bump Stow to 1.4.0

- varia/sass/blocks/cover/_editor.scss
- varia/sass/blocks/cover/_style.scss
- varia/style-editor.css
- varia/style-rtl.css
- varia/style.css
> Varia: only inherit top/bottom margin with cover images.

- varia/sass/base/_extends.scss
- varia/sass/blocks/blog-posts/_style.scss
- varia/sass/blocks/button/_editor.scss
- varia/sass/blocks/button/_style.scss
- varia/style-editor.css
- varia/style-rtl.css
- varia/style-woocommerce-rtl.css
- varia/style-woocommerce.css
- varia/style.css
Fixes #1751 
<table>
<tr>
<td>Before:
<br><br>
</td>
<td>After:
<br><br>
</td>
</tr>
</table>
> Varia: Fix Faux button style

- pique/style.css
> Pique: Disable zooming into site logo on hover

- independent-publisher-2/css/blocks.css
- independent-publisher-2/style.css
Fixes #1785 
<table>
<tr>
<td>Before:
</td>
<td>After:
</td>
</tr>
</table>
> Independent Publisher 2: Adjust heading clearing

- independent-publisher-2/css/blocks.css
- independent-publisher-2/css/editor-blocks.css
Fixes #1786 
<table>
<tr>
<td>Editor before (default)
</td>
<td>Editor after (default)
</td>
</tr>
<tr>
<td>Editor before (rounded)
</td>
<td>Editor after (rounded)
</td>
</tr>
<tr>
<td>Frontend before (default)
</td>
<td>Frontend after (default)
</td>
</tr>
<tr>
<td>Frontend before (rounded)
</td>
<td>Frontend after (rounded)
</td>
</tr>
</table>
> Independent Publisher 2: Adjust images styles

- photos/js/global.js
Fixes #1840 
<table>
<tr>
<td>Before:
<br><br>
</td>
<td>After:
<br><br>
</td>
</tr>
</table>
> Photos: Fix responsive menu

- shoreditch/style.css
Fixes #1752
<table>
<tr>
<td>Before:
<br><br>
</td>
<td>After:
<br><br>
</td>
</tr>
</table>
> Shoreditch: Remove box shadow from image link

- affinity/editor-blocks.css
Related to #1866
<table>
<tr>
<td>Before:
<br><br>
</td>
<td>After:
<br><br>
</td>
</tr>
</table>
> Affinity: Fix list view in editor

- dara/editor-blocks.css
Related #1866
<table>
<tr>
<td>Before:
<br><br>
</td>
<td>After:
<br><br>
</td>
</tr>
</table>
> Dara: Fix list view in editor

- intergalactic-2/editor-blocks.css
Related #1866
<table>
<tr>
<td>Before:
<br><br>
</td>
<td>After:
<br><br>
</td>
</tr>
</table>
> Intergalactic 2: Fix list view in editor

- karuna/editor-blocks.css
Related #1866 
<table>
<tr>
<td>Before:
<br><br>
</td>
<td>After:
<br><br>
</td>
</tr>
</table>
> Karuna: Fix list view in editor

- libretto/css/editor-blocks.css
Related #1866
<table>
<tr>
<td>Before:
<br><br>
</td>
<td>After:
<br><br>
</td>
</tr>
</table>
> Libretto: Fix list view in editor

- publication/editor-blocks.css
Related #1866
<table>
<tr>
<td>Before:
<br><br>
</td>
<td>After:
<br><br>
</td>
</tr>
</table>
> Publication: Fix list view in editor

- toujours/editor-blocks.css
Related #1866 
<table>
<tr>
<td>Before:
<br><br>
</td>
<td>After:
<br><br>
</td>
</tr>
</table>
> Toujours: Fix list view in editor

- sk8prk/assets/js/extend-blocks.js
- sk8prk/assets/sass/_block-extends.scss
- sk8prk/assets/sass/_header.scss
- sk8prk/assets/sass/_responsive.scss
- sk8prk/assets/sass/_text.scss
- sk8prk/assets/sass/block-extends/_button.scss
- sk8prk/assets/sass/block-extends/_cover.scss
- sk8prk/assets/sass/block-extends/_gallery.scss
- sk8prk/assets/sass/block-extends/_group.scss
- sk8prk/assets/sass/block-extends/_image.scss
- sk8prk/assets/sass/block-extends/_latest-posts.scss
- sk8prk/assets/sass/block-extends/_media-text.scss
- sk8prk/assets/sass/block-extends/_pullquote.scss
- sk8prk/assets/sass/style.scss
- sk8prk/functions.php
- sk8prk/header.php
- sk8prk/package-lock.json
- sk8prk/package.json
- sk8prk/style-rtl.css
- sk8prk/style.css
- sk8prk/template-parts/content/content-page.php
- sk8prk/template-parts/content/content-single.php
- sk8prk/variables.css
This PR migrates over the in-progress "Sk8prk" Theme from https://github.com/Automattic/themes-workspace. Originally added there in https://github.com/Automattic/themes-workspace/pull/141.
> Add in-progress sk8prk theme

- seedlet/languages/seedlet.pot
Adds an initial (empty) translation file.
> Seedlet: Create seedlet.pot

- seedlet/assets/css/variables-editor.css
- seedlet/assets/css/variables.css
- seedlet/assets/sass/abstracts/_config.scss
- seedlet/assets/sass/child-theme/variables-editor.css
- seedlet/assets/sass/child-theme/variables.css
- seedlet/classes/class-seedlet-custom-colors.php
> Seedlet: fixes logic and warnings around custom colors

- seedlet-blocks/style.css
- seedlet/README.md
- seedlet/assets/sass/child-theme/style-child-theme.scss
- seedlet/assets/sass/style.scss
- seedlet/languages/seedlet.pot
- seedlet/style-rtl.css
- seedlet/style.css
Seems like a few mentions of the old repository made it over here. This replaces those with the correct URL.
> Seedlet/Seedlet Blocks: Update repository URL

- varia/sass/abstracts/_responsive-logic.scss
- varia/sass/blocks/blog-posts/_editor.scss
- varia/sass/blocks/blog-posts/_style.scss
- varia/sass/blocks/utilities/_style.scss
- varia/sass/layout/_structure.scss
- varia/style-rtl.css
- varia/style.css
Fixes https://github.com/Automattic/themes/issues/2065
This PR fixes the image gallery alignment issues.
**Gallery with Right alignment Before Fix**
**Gallery with Left alignment Before Fix**
**Gallery with Right alignment After Fix**
**Gallery with Left alignment After Fix**
This PR also fixes the alignment issues whenever a alignful Gallery is followed by a left or right aligned Gallery.
**A Post with different Gallery Alignment after applying this fix**
**In the Block Editor**
**In the Frontend**
https://github.com/Automattic/themes/issues/2065
> Varia & Child Themes: Fix Image Gallery alignment issues

- seedlet/README.md
This PR simplifies the README. It's a starting point for #2172, stripping out the outdated parts and narrowing down to just the minimum for now.
> Update Seedlet readme.

- seedlet/assets/sass/structure/_vertical-margins.scss
- seedlet/style-rtl.css
- seedlet/style.css
- Adds vertical spacing logic to widget areas.
Before|After
------------|------------
Fixes: #2185
> Seedlet: Add vertical spacing logic to widget areas.

- morden/sass/_extra-child-theme.scss
- morden/style-rtl.css
- morden/style.css
Fixes https://github.com/Automattic/themes/issues/2144.
This PR fixes the image gallery alignment issue in Morden theme after applying https://github.com/Automattic/themes/pull/2077.
**Gallery with left alignment Before Fix**
**Gallery with Left alignment After Fix**
This PR also fixes the similar issue with right aligned gallery.
https://github.com/Automattic/themes/issues/2065
> Morden: Fix Gallery Alignment Issue causing from setting max-width in desktop

- seedlet/assets/css/print.css
- seedlet/assets/sass/print.scss
Removes a stray reference to Varia in the print styles.
> Seedlet: remove reference to Varia in print styles

- seedlet/assets/css/ie.css
- seedlet/assets/sass/blocks/utilities/_style.scss
- seedlet/style.css
> Seedlet: add max-width default to empty site

- seedlet/assets/css/ie.css
- seedlet/assets/css/style-editor.css
- seedlet/assets/sass/vendors/jetpack/blocks/layout-grid/_editor.scss
- seedlet/assets/sass/vendors/jetpack/blocks/layout-grid/_style.scss
- seedlet/postcss.config.js
- seedlet/style-rtl.css
- seedlet/style.css
Addresses #2211 and #2212.
_Editor_
_Front-end_
_Editor_
_Front-end_
> Seedlet: Fix layout grid margins

- hever/sass/style-child-theme.scss
- hever/style-rtl.css
- hever/style.css
> Version bump for Hever

- seedlet/functions.php
Closes #2280. Seems to work just fine in the front end too.
> Seedlet: Add theme support for custom spacing controls

- seedlet/assets/css/ie.css
- seedlet/assets/sass/style.scss
- seedlet/readme.txt
- seedlet/style-rtl.css
- seedlet/style.css
This PR bumps the version and adds notes to the changelog based on what we did for the most recent submission to dotorg.
> Seedlet: bump version and changelog

- seedlet/assets/css/ie.css
- seedlet/assets/sass/style.scss
- seedlet/readme.txt
- seedlet/style-rtl.css
- seedlet/style.css
Bumps Seedlet version to match what was submitted and approved in dotorg directory.
> Seedlet: bump version

- seedlet/readme.txt
- seedlet/style.css
This updates the theme description and URI to match the page here: 
https://wordpress.com/theme/seedlet
> Seedlet: Update theme description and URI

- seedlet/assets/css/ie.css
- seedlet/assets/sass/child-theme/style-child-theme.scss
- seedlet/assets/sass/style.scss
- seedlet/style-rtl.css
- seedlet/style.css
Followup from #2402 — this PR edits these in the Sass files. Not sure how I overlooked that. 🙃
> Update theme description and URI (in SASS files this time)

- seedlet/readme.txt
Not sure if this is necessary or not, but I did this for `style.css`, so I might as well make it match in `readme.txt`.
> Seedlet: Strip non-ASCII characters from readme.txt

- seedlet/assets/css/ie.css
- seedlet/assets/sass/style.scss
- seedlet/readme.txt
- seedlet/style.css
This PR updates the docblock to sync up with versions and readme info on the dotorg themes directory.
> Seedlet: update docblock

- seedlet/comments.php
> Seedlet: fix escaping function in comments

- seedlet/functions.php
I think this is just a simple typo :)
> Fix seedlet font translator comments

- seedlet/assets/css/ie.css
- seedlet/assets/sass/blocks/gallery/_style.scss
- seedlet/style.css
We removed this code in Varia: https://github.com/Automattic/themes/pull/2456
We should do the same for Seedlet...
> Remove custom code for gallery blocks in Seedlet

- .gitignore
This just adds .DS_Store files to the .gitignore as I have a lot of these in my repo!
> Ignore OSX files

- seedlet/inc/block-patterns.php
I forgot to make the alt attributes translatable on my latest PR #2506
> Seedlet alt titles made translatable

- seedlet/assets/sass/style.scss
- seedlet/functions.php
- seedlet/package.json
- seedlet/readme.txt
- seedlet/style-rtl.css
- seedlet/style.css
This PR bumps the version to 1.1 and updates the changelog.
> Seedlet: bump version to 1.1

- seedlet/readme.txt
> Seedlet: update changelog for 1.1

- seedlet/assets/sass/style.scss
- seedlet/package.json
- seedlet/style-rtl.css
- seedlet/style.css
> update Seedlet version number

- seedlet/inc/headstart/en.json
in D51460-code, I updated seedlet's headstart annotation for WordPress.com. This PR copies the file verbatim from the wpcom repository to git.
This file was autogenerated with `wp headstart generate-annotation --url=seedletdemo.wordpress.com --output-to-theme --type=copy` on my WordPress.com sandbox.
> Update seedlet headstart annotation

- spearhead/functions.php
This updates the content width variable to match the CSS
> update spearhead content width

- spearhead/assets/sass/style.scss
- spearhead/style-rtl.css
- spearhead/style.css
> Spearhead: Update theme URL

- alves/package-lock.json
- alves/package.json
- balasana/package-lock.json
- balasana/package.json
- barnsbury/package-lock.json
- barnsbury/package.json
- brompton/package-lock.json
- brompton/package.json
- calm-business/package-lock.json
- calm-business/package.json
- coutoire/package-lock.json
- coutoire/package.json
- dalston/package-lock.json
- elegant-business/package-lock.json
- elegant-business/package.json
This should fix the issues raised here: https://github.com/automattic/themes/network/alerts
> Fix security issues
