radcliffe-2/inc/template-tags.php

Sometimes WordPress returns a `WP_Error` object and not a string when querying for terms like tags and categories. The PHP fatal error in the server logs looks like this:
```
Catchable fatal error for wp-content/themes/pub/radcliffe-2/inc/template-tags.php:78 - Object of class WP_Error could not be converted to string #theme
```
This change applies a safety check to both `get_the_tag_list()` and `get_the_category_list()` for Radcliffe 2 — checking for the error before attempting to display the result as a string.

Radcliffe 2: fix fatal error when query categories and tags

---

altofocus/assets/js/scripts.js

This update replaces $(window).load() with $(document).ready() to work around an issue with the ads JavaScript.
See #108.

Altofocus: Replace window.load event with document.ready

---

textbook/assets/js/functions.js
textbook/style.css

This update replaces `$(window).load()` with `$(document).ready()` to work around an issue with the ads JavaScript.
I also removed the styles/function that hides then show the theme's `body` once the page is finished loading, since it doesn't seem like the page changes a lot as it loads (unlike, say, a page that uses masonry/isotope for layout). I'm open to going without that change, though.
See #108.

Textbook: Update JavaScript to replace window.load event

---

illustratr/js/portfolio.js

Replace `$(window).load()` event with `$(document).ready()` for functions that show hidden elements on the page, to help work around ads issue. 
See #108

Illustratr: Replace window.load event with document.ready

---

shoreditch/inc/wpcom-colors.php
shoreditch/style.css

The select dropdowns in the Top Widget area have a semi-transparent white background, with white text, which works well against the widget area's blue background. On a few Windows browsers, these styles carry over to the open select dropdown as well, leading to white text on a white background. This update applies a text colour to the options when the dropdown is open.
See #58.

Shoreditch: Add colour to select dropdowns in widget area

---

radcliffe-2/inc/wpcom-colors.php
radcliffe-2/style.css

This update makes the hover transparency on posts on the blog, archive and search pages more consistent.
Also syncs up padding on form inputs with how they display in SVN. 
Fixes #140

Radcliffe 2: Make hover transparency more consistent

---

apostrophe-2/inc/template-tags.php

Add check for is_paged for "Featured" on sticky posts so it's only output when they're "stuck" on the front page, not when they appear on other pages. 
See #170.

Apostrophe 2: Add check for is_paged for "Featured" on sticky posts

---

apostrophe-2/css/blocks.css

This update adjusts the following styles:
* Make sure full alignments don't cause side scrolling.
* Update separator block to look the same in the editor and on the front-end.
* Making File block buttons more consistent with other blocks.
* Add 'image' variations of cover block classes.

Apostrophe 2: Minor updates to Gutenberg styles

---

illustratr/blocks.css
illustratr/editor-blocks.css

When testing on WP.com before merging this update, I noticed two small issues that are fixed in this PR:
* The Code block had a light border and rounded corners in the editor, which doesn't match the front end.
* The Gallery block had some unneeded margins that were interfering with the wide alignment.

Illustratr: Fix two small issues in Gutenberg support

---

independent-publisher-2/js/independent-publisher-2.js

This update fixes a JavaScript error I introduced in the theme's Gutenberg support.

Independent Publisher 2: Correct JavaScript error

---

lodestar/assets/css/blocks.css

Make sure the wide and full alignments aren't applied to the two-column panels on the static front page, because they really don't look good.

Lodestar: Make sure wide and full alignments can't be applied to two-column panels

---

pique/assets/css/blocks.css

This update makes the selectors for wide and full alignments more specific, so they work on all the appropriate pages (like blog, when it's not the home page, and the archives).

Pique: Make wide and full alignments more specific

---

radcliffe-2/inc/style-packs-core.php

Right now Radcliffe 2 attempts to load a default.css file when you're using the default style pack.
There isn't such a file -- all the default styles live in the style.css.
This PR adds a check for whether the site is using the default style pack before attempting to enqueue the style pack files; if the site is using the default style pack, it will skip this step. 
Related discussion: p1542402289609400-slack-themes.
Related ticket: 1567702-zen

Radcliffe 2: Fix 404 error coming from default.css

---

radcliffe-2/assets/css/blocks-vintage.css
radcliffe-2/assets/css/blocks.css
radcliffe-2/assets/css/editor-style-colorful.css
radcliffe-2/assets/css/editor-style-modern.css
radcliffe-2/assets/css/editor-style-vintage.css
radcliffe-2/assets/css/editor-style.css
radcliffe-2/functions.php

* Reorders checks for which editor colour palette to load; with the original set up, the default palette was never loaded. 
* Reorders stylesheets to match other themes.
* Removes unneeded editor styles.
* Makes Cover block only wide when the wide and full alignments are applied.
* Fix issues with table full and wide widths. 
* Add updated versions of Gutenberg CSS selectors.

Radcliffe 2: Clean up Gutenberg support

---

dara/blocks.css
dara/editor-blocks.css
dara/rtl.css

Minor fixes to Gutenberg styles, including:
* Remove empty CSS selectors.
* Fix RTL styles for large quote blocks.
* Remove incorrect file button hover styles.
* Add overflow auto to preformatted and code blocks.
* Correct centred styles for widgets.
* Increase font size of comment widget.
* Remove margins from recent posts widget when displayed as grid.
* In themes RTL styles, remove border from block quote.

Dara: Minor fixes to Gutenberg styles

---

illustratr/blocks.css
illustratr/editor-blocks.css

This PR includes some minor fixes to the theme's Gutenberg support, including:
* Adding some unique verse styles (italicized)
* Reorganizing the editor CSS to match other themes; consolidating some styles.
* Correcting some quote RTL issues with borders.
* Update comments widget block to better match theme's comment styles.

Illustratr: Fixes to theme's Gutenberg support

---

gazette/css/blocks.css
gazette/css/editor-blocks.css

A few small fixes for Gazette's Gutenberg styles, including:
* Updating button styles to account for the border.
* Making colour style selectors more specific.
* Fix comment widget styles in the editor.

Gazette: Minor fixes to Gutenberg styles

---

dara/blocks.css

When images in image blocks are smaller than the available space, they are aligned left, even when they are styled as centred. This update makes these images centred, so they display like they do in the editor.
See #376.

Dara: Make centred images aligned centred are centred

---

penscratch-2/css/blocks.css
penscratch-2/css/editor-blocks.css

* Add missing styles for pre tag in classic editor.
* Update button styles, to make sure shine is only applied to buttons without a background, but that the background colour still applies as a fallback.

Penscratch 2: Minor fixes to Gutenberg implementation

---

pique/assets/css/blocks.css
pique/assets/css/editor-blocks.css

* Remove bottom margin styles from lists in editor.
* Update colour for pre tags in editor.
* Adjust top margin on drop caps.
* Update comment widget styles to better match theme's comment styles.

Pique: Minor fixes to Gutenberg implementation

---

shoreditch/css/blocks.css
shoreditch/css/editor-blocks.css
shoreditch/inc/extras.php

* Update colour selectors, to account for :visited state.
* Remove bottom border from buttons.
* Make sure wide class is applied when blog page isn't the front page, too.

Shoreditch: Minor fixes to Gutenberg implementation

---

libre-2/footer.php
libre-2/header.php
libre-2/style.css

There was still some side-scrolling on Libre 2, possibly related to ads. This PR adds a new element to add the `overflow-x` styles to, rather than relying on the body or html (which don't seem to work on sites with ads).
See #361, #407.

Libre 2: Add container to help make sure header pseudo element doesn't cause side scrolling.

---

sketch/css/editor-blocks.css

Remove uppercase styles for post title in editor.
This does reflect how the theme looks on the front-end, but it obscures what's actually being typed into the post title field - there's no way to know if you're actually using the case you want to use. 
Fixes #413.

Sketch: Remove uppercase on post titles in editor

---

button-2/assets/js/block-variations.js
button-2/assets/js/main.js
button-2/blocks.css
button-2/editor-blocks.css
button-2/functions.php

This is to address the issue in #421, but also a fun excuse play with block variations.
This update adds the option of a 'fancy' image block variation to the image block, to match behaviour already available in the Button 2 theme. 
It also updates the related CSS and JavaScript, so although these blocks will have different classes than when this style is used in the old editor, they will still behave the same. 
The previews aren't 100% percent (it would be nice to scale down the corners in the thumbnail), but that can be enhanced in a v2. 
Options:
Preview when hovering over the 'Fancy' option (you can't really tell from my screenshot):
With 'Fancy' selected:

Button 2: Add block variation for 'fancy' class for the image block

---

button-2/assets/js/block-variations.js

Adds `name` for default image block styles, so it doesn't use class `is-style-undefined`.

Button 2: Add name for default image block styles, so it doesn't say 'null'

---

dara/assets/js/slider.js
dara/components/post/content-featured.php
dara/style.css

Use CSS and a temporary class to prop up the flexslider slideshow while the page is loading, to prevent the slideshow overlapping other content while loading.
It doesn't look like removing the padding is actually necessary, but opted to take it out when flexslider initiates anyway, just in case there's some weird stress case I'm missing.
Fixes #169.

Dara: Use CSS and a temporary class to prop up the flexslider slideshow

---

libre-2/css/blocks.css
libre-2/editor-style.css
libre-2/style.css

This PR builds off of @torres126's work in #411. 
I removed some super-confusing figure styles in the blocks.css that were meant to override the themes default figure styles... but the easiest fix was actually just removing them from the style and editor-styles.css. 
I also set the captions back to aligned left, simply because with them centred for centred blocks, we'd probably need to look at centring them for wide or full blocks, and that might be too noticeable a change :) 
Fixes #404.

Libre 2: Fix image block centring 

---

libre-2/css/blocks.css

#408 doesn't seem to work like intended, and it seems I can't modify that PR as captions aren't shown when trying to do so. Therefore, after trying to look for an alternative, I've created a new PR to try and solve the issue of images not aligning when using the Image Block on the Libre 2 theme. 
I'm not too sure if this is the most effective way at solving this problem, but I'm hoping it does work. 
**Before:**
**After:**
(cc @laurelfulford)

Libre 2: Fix Centre Alignment of Images & Captions

---

illustratr/editor-blocks.css
intergalactic-2/editor-blocks.css
lodestar/assets/css/editor-blocks.css

As mentioned in #413, Illustratr, Intergalactic 2 and Lodestar all has themes which transform the post title in the Editor with intent to make the editor and front-end match, but this can cause confusion. So, this PR intends to stop that from happening so the user can decide to use capital letters.

Lodestar, Illustratr & Galactic 2: Remove Uppercase in Post Titles

---

libretto/css/editor-blocks.css

Remove drop cap, first line styles from first paragraph in editor when it's being focussed on (when the text is getting edited), as it causes the text to get cut off in Safari. 
Also clean up a work around in the editor styles, to actually use the correct selectors for the editor. 
Fixes #458.

Libretto: Remove drop cap, first line styles from first paragraph in editor

---

penscratch-2/style.css

Adds `margin-right (and left): auto` to the site when there isn't a sidebar. Though `margin: 14px auto` works well when the issue occurs, it results in the content being higher on larger screens because it overrides the margin [here](https://github.com/Automattic/themes/blob/master/penscratch-2/style.css#L1911). This approach doesn't cause that effect. 
**Before:**
**After:**
Fixes #371

Penscratch 2: Fix No-Sidebar Layout

---

dara/assets/js/slider.js
dara/functions.php
dara/style.css

Use imagesLoaded to refresh slideshow after it loads, as an alternative fix for the Firefox overlap issue. See #169.
I need to do some final testing on this, to make sure it doesn't introduce more issues, then look at committing.

Dara: Use imagesLoaded to refresh slideshow after it loads

---

independent-publisher-2/style.css

Strongly based on #277:
This update adjusts the styles for the mobile menu, so when viewing the children of the current page in the mobile menu, you don't get white text on white background.
Fixes #276.

Independent Publisher 2: Adjust menu styles to prevent white on white text

---

affinity/style.css

This PR intends to fix the overlap with long site titles on mobile with sites using the Affinity theme by setting a margin of 30%, however adding `width: 100%` to desktop viewing. 
**Current:**
**Proposed:**
(cc @laurelfulford) 
Fixes #412

Affinity: Fix Overlap with "Menu" Button on Mobile

---

lodestar/style.css

For some reason, the Customizer aligns the menu in the centre until Header Text is added. It shouldn't, because it's aligned left on the live site in all cases, so this PR intends to fix that. 
**Before:**
**After:**
(cc @laurelfulford) 
Fixes #327

Lodestar: Align Menu Left in the Customiser

---

.gitignore
radcliffe-2/style.css

Change transparent background appearing for dropdown menu items linking to same page / page jumps. Added red hover background to these as well. 
#435

Radcliffe-2: CSS fix for background of Dropdown menu items leading to same page / page jumps

---

apostrophe-2/inc/wpcom-colors.php
apostrophe-2/style.css

Update Apostrophe 2's styles to make sure the subscribe button has sufficient contrast, including updates to the custom colour annotations.
Also includes a fix for the grey title text with the default colour scheme.
See #496.

Apostrophe: Update subscribe button styles 

---

canard/blocks.css
gazette/css/blocks.css
independent-publisher-2/css/blocks.css
intergalactic-2/blocks.css
rebalance/blocks.css

Inherits the caption colour for five themes: Canard, Gazette, Independent Publisher 2, Intergalactic 2 and Rebalance 
Other themes may have a set caption colour, but even though you can change the colour of the background of the site, you can't change the background colour behind the caption. Examples of these themes include Libretto, Textbook and Toujours. The only theme where there's still an issue which this PR won't help with is Photos, the caption issue is present but setting the colour to inherit only makes it worse for some reason. 
The effect of this change is to make the colour of the caption far more readable on darker coloured backgrounds, since they currently fail the accessibility [guidelines](https://dotcombrand.wordpress.com/colors/) of a colour ratio. 
**Before:** …

Several themes: Inherit Caption Colours with Gutenberg Blocks

---

affinity/blocks.css
photos/blocks.css

Update the caption colours for Affinity and Photos, so they inherit the text colour used elsewhere in the theme.
#459

Multiple Themes: Update caption colours

---

affinity/blocks.css

This change adds an `overflow: hidden;` setting to the wrapping `<a>` markup to prevent linked images from overflowing and breaking.
Fixes #473 
**Mobile:**
**Desktop:**
**Mobile:**
**Desktop:**

Affinity: Fix Gutenberg gallery block when images link to media files

---

affinity/blocks.css
affinity/editor-blocks.css

This update corrects Affinity's button block styles, so you can actually use the default rounded, and assign the outline and square options.
See #434.

Affinity: Fix button styles

---

apostrophe-2/css/blocks.css
apostrophe-2/css/editor-blocks.css

This update corrects Apostrophe 2's button block styles, so you can actually use the default rounded, and assign the outline and square options.
See #434.

Apostrophe 2: Fix button styles

---

button-2/blocks.css

This update corrects Button 2's button block styles, so you can actually use the default rounded, and assign the outline and square options.
See #434.

Button 2: Fix button styles

---

dara/blocks.css
dara/editor-blocks.css

This update corrects Dara's button block styles, so you can actually use the default rounded, and assign the outline and square options.
See #434.

Dara: Correct button styles

---

dyad-2/css/blocks.css
dyad-2/css/editor-blocks.css

This update corrects Dyad 2's button block styles, so you can actually use the default rounded, and assign the outline and square options.
See #434.

Dyad 2: Update styles for buttons.

---

gazette/css/blocks.css
gazette/css/editor-blocks.css

This update corrects Gazette's button block styles, so you can actually use the default rounded, and assign the outline and square options.
See #434.

Gazette: Update styles for buttons

---

illustratr/blocks.css
illustratr/editor-blocks.css

This update corrects Illustratr's button block styles, so you can actually use the default rounded, and assign the outline and square options.
See #434.

Illustratr: Update styles for buttons

---

independent-publisher-2/css/blocks.css
independent-publisher-2/css/editor-blocks.css

This update corrects Independent Publisher 2's button block styles, so you can actually use the default rounded, and assign the outline and square options.
See #434.

Independent Publisher 2: Update styles for buttons

---

intergalactic-2/blocks.css
intergalactic-2/editor-blocks.css

This update corrects Intergalactic 2's button block styles, so you can actually use the default rounded, and assign the outline and square options.
See #434.

Intergalactic 2: Update styles for buttons

---

ixion/blocks.css
ixion/editor-blocks.css

This update corrects Ixion's button block styles, so you can actually use the default rounded, and assign the outline and square options.
See #434.

Ixion: Update styles for buttons

---

karuna/blocks.css
karuna/editor-blocks.css

This update corrects Karuna's button block styles, so you can actually use the default rounded, and assign the outline and square options.
See #434.

Karuna: Update styles for buttons

---

libre-2/css/blocks.css
libre-2/css/editor-blocks.css

This update corrects Libre 2's button block styles, so you can actually use the default rounded, and assign the outline and square options.
See #434.

Libre 2: Update styles for buttons

---

libretto/css/blocks.css
libretto/css/editor-blocks.css

This update corrects Libretto's button block styles, so you can actually use the default rounded, and assign the outline and square options.
See #434.

Libretto: Update styles for buttons

---

lodestar/assets/css/blocks.css
lodestar/assets/css/editor-blocks.css

This update corrects Lodestar's button block styles, so you can actually use the default rounded, and assign the outline and square options.
See #434.

Lodestar: Update styles for buttons

---

penscratch-2/css/blocks.css
penscratch-2/css/editor-blocks.css

This update corrects Penscratch 2's button block styles, so you can actually use the default rounded, and assign the outline and square options.
See #434.

Penscratch 2: Update styles for buttons

---

photos/blocks.css
photos/editor-blocks.css

This update corrects Photos' button block styles, so you can actually use the default rounded, and assign the outline and square options.
See #434.

Photos: Update styles for buttons

---

pique/assets/css/blocks.css
pique/assets/css/editor-blocks.css

This update corrects Pique's button block styles, so you can actually use the default rounded, and assign the outline and square options.
See #434.

Pique: Update styles for buttons

---

publication/blocks.css
publication/editor-blocks.css

This update corrects Publication's button block styles, so you can actually use the default rounded, and assign the outline and square options.
See #434.

Publication:  Update styles for buttons

---

rebalance/blocks.css
rebalance/editor-blocks.css

This update corrects Rebalance's button block styles, so you can actually use the default rounded, and assign the outline and square options.
See #434.

Rebalance: Update styles for buttons

---

scratchpad/blocks.css
scratchpad/editor-blocks.css

This update corrects Scratchpad's button block styles, so you can actually use the default rounded, and assign the outline and square options.
See #434.

Scratchpad: Update styles for buttons

---

sketch/css/blocks.css
sketch/css/editor-blocks.css

This update corrects Sketch's button block styles, so you can actually use the default rounded, and assign the outline and square options.
See #434.

Sketch: Update styles for buttons

---

textbook/assets/css/blocks.css
textbook/assets/css/editor-blocks.css

This update corrects Textbook's button block styles, so you can actually use the default rounded, and assign the outline and square options.
See #434.

Textbook: Update styles for buttons

---

toujours/blocks.css
toujours/editor-blocks.css

This update corrects Toujours's button block styles, so you can actually use the default rounded, and assign the outline and square options.
See #434.

Toujours: Update styles for buttons

---

altofocus/assets/stylesheets/blocks.css
altofocus/assets/stylesheets/editor-blocks.css

This update corrects Altofocus's button block styles, so you can actually use the default rounded, and assign the outline and square options.
See #434.

Altofocus: Update styles for buttons

---

radcliffe-2/assets/css/blocks-vintage.css
radcliffe-2/assets/css/blocks.css
radcliffe-2/assets/css/editor-style-modern.css
radcliffe-2/assets/css/editor-style-vintage.css
radcliffe-2/assets/css/editor-style.css
radcliffe-2/functions.php
radcliffe-2/styles/colorful.css
radcliffe-2/styles/modern.css
radcliffe-2/styles/vintage.css

This update corrects Radcliffe 2's button block styles, so you can actually use the default rounded, and assign the outline and square options.
See #434.

Radcliffe 2: Update styles for buttons

---

intergalactic-2/inc/wpcom-colors.php

• Adds a `:not(.singular)` selector to page views so that the site-title can respect the colors set in the customizer
Fixes: #225

Intergalactic 2: Fixes color annotations so that site title doesn’t disappear

---

libretto/style.css

This change should mean that only the image and the site title will redirect, allowing for the users to visit the intended pages by clicking their names on the menu. I've tried to explain it in this image here: https://prnt.sc/lkvaj0
#369

Libretto: Prevent Title Block Link Overlap with Menu

---

independent-publisher-2/inc/wpcom-colors.php

Improve contrast for visited 'more' link buttons (plus a couple more), when a site is using one of the theme's darker colour palettes.
Fixes #486.

Independent Publisher 2: Fix contrast issue with visited button style

---

button-2/style.css

Make the infinite scroll button styles more specific, to override the styles coming from jetpack.css.
Fixes #518.

Button 2: Make infinite scroll button styles more specific

---

dyad-2/functions.php

Update how widgets are counted, to exclude the non visible ones (Cookies and Mailchimp). This count is used to determine how many columns the widgets should be displayed in.
Fixes #287.

Dyad 2: Update how widgets are counted

---

ixion/style.css

Remove `visibility: hidden` from search -- it was making the search inaccessible via keyboard, and not having it there doesn't appear to cause any adverse effects.
Fixes: #498

Ixion: Remove 'visibility: hidden' from search

---

ixion/style.css

Since the `visibility: hidden` isn't needed for the search, neither is the `visibility: visible`. :)
See #498.

Ixion: Remove unneeded style

---

lodestar/inc/jetpack.php
lodestar/taxonomy-jetpack-portfolio-tag.php
lodestar/taxonomy-jetpack-portfolio-type.php

Update Lodestar's Jetpack infinite scroll logic, so the correct template part is used in the Portfolio tag and type taxonomy archives.
Fixes: #444.

Lodestar: Fix issue with portfolio archive pagination

---

radcliffe-2/inc/headstart/en-bar.json
radcliffe-2/inc/headstart/en-cafe.json
radcliffe-2/inc/headstart/en-mexican-restaurant.json
radcliffe-2/inc/headstart/en-movie-theater.json
radcliffe-2/inc/headstart/en-parking-garage.json
radcliffe-2/inc/headstart/en.json

Update headstart content to remove the 'below' when referring to the edit link. 
Fixes #509.

Radcliffe 2: Update headstart annotations

---

radcliffe-2/contact-info/contact-info-customize-preview.js
radcliffe-2/contact-info/contact-info-customizer.php
radcliffe-2/contact-info/contact-info-functions.php

This update syncs up the copies of the contact info files on WP.com with GitHub, as they've gotten ahead in r52410-wpcom-themes.
Noticed while investigating #492.

Radcliffe 2: This update syncs up the copies of the contact info files

---

dyad-2/functions.php

Correct how footer widget count was calculated -- my original fix broke things in a different way. Fixes #589, #287.

Dyad 2: Correct how footer widget count was calculated

---

photos/functions.php
photos/inc/custom-header.php

Make sure new custom header file is being loaded, and the styles to hide site title and description are being added via callback. 
Fixes #591; see #319.

Photos: Fix issues introduced to custom header

---

radcliffe-2/assets/js/radcliffe-2.js

The JS looks at the size of each `.entry-header` and compares it to the default `.entry-thumbnail` height ( Window.width * 1.33 ), and sets the image to the larger of the two. Resolves an issue when the Customizer header fonts are set to Large, AND when there are really long post titles on mobile views.
#284

Updated JS to changed the featured image height

---

radcliffe-2/contact-info/contact-info-customizer.php

Since r52410-wpcom-themes, we're saving Contact info values in blog options rather than theme_mods.
For blogs created prior to this change, we created at patch to make sure we fall back on the value from theme_mod, where available, in the Customizer.
#492  brought to our attention a situation in which a user wished to empty Contact info values via the Customizer. Because of the fall back check, if the theme_mod value is present it will always display and never update.
This update introduces custom sanitize methods, which serve as a way for us to remove these theme_mod values altogether.
Fixes #492.

Radcliffe 2: Update contact info behaviour to allow deleting of old theme_mods

---

elegant-business/sass/blocks/_blocks.scss
elegant-business/style-editor.css
elegant-business/style-editor.scss
elegant-business/style-rtl.css
elegant-business/style.css

Also looks like it syncs up some other CSS changes that are already on WP.com.
See #594.

Elegant Business: Update quote block border styles

---

modern-business/sass/blocks/_blocks.scss
modern-business/style-editor.css
modern-business/style-editor.scss
modern-business/style-rtl.css
modern-business/style.css

Modern Business:  Update quote block border styles

---

professional-business/sass/blocks/_blocks.scss
professional-business/style-editor.css
professional-business/style-editor.scss
professional-business/style-rtl.css
professional-business/style.css

Professional Business: Update quote block border styles

---

affinity/editor-blocks.css

Affinity: Update quote block border styles

---

apostrophe-2/css/blocks.css
apostrophe-2/css/editor-blocks.css

Apostrophe 2: Update quote block border styles

---

canard/editor-blocks.css

Canard: Update quote block border styles

---

dyad-2/css/blocks.css
dyad-2/css/editor-blocks.css

Dyad 2: Update quote block border styles

---

independent-publisher-2/css/blocks.css
independent-publisher-2/css/editor-blocks.css

Independent Publisher 2: Update quote block border styles

---

lodestar/assets/css/blocks.css
lodestar/assets/css/editor-blocks.css

Lodestar: Update quote block border styles

---

photos/blocks.css
photos/editor-blocks.css

Photos: Update quote block border styles

---

rebalance/blocks.css
rebalance/editor-blocks.css

Rebalance: Update quote block border styles

---

shoreditch/css/blocks.css
shoreditch/css/editor-blocks.css

Shoreditch: Update quote block border styles

---

sketch/css/blocks.css
sketch/css/editor-blocks.css

Sketch: Update quote block border styles

---

toujours/blocks.css
toujours/editor-blocks.css

Toujours: Update quote block border styles

---

dara/blocks.css
dara/editor-blocks.css

Dara: Align quote icon to right when text is right aligned

---

gazette/css/blocks.css
gazette/css/editor-blocks.css

Gazette: Align quote icon to right when text is right aligned

---

illustratr/blocks.css
illustratr/editor-blocks.css

Illustratr: Update quote block border styles

---

libre-2/css/blocks.css
libre-2/css/editor-blocks.css

Libre 2: Align quote icon to right when text is right aligned

---

libretto/css/blocks.css
libretto/css/editor-blocks.css

Libretto:  Align quote icon to right when text is right aligned

---

penscratch-2/css/blocks.css
penscratch-2/css/editor-blocks.css

Penscratch 2: Align quote icon to right when text is right aligned

---

pique/assets/css/blocks.css

Pique: Align quote icon to center when text is right aligned

---

scratchpad/blocks.css
scratchpad/editor-blocks.css

Scratchpad: Align quote icon to right when text is right aligned

---

friendly-business/sass/blocks/_blocks.scss
friendly-business/style-rtl.css
friendly-business/style.css
modern-business/style-editor.css
modern-business/style-editor.scss
professional-business/sass/blocks/_blocks.scss
professional-business/style-editor.css
professional-business/style-editor.scss
professional-business/style-rtl.css
professional-business/style.css
sophisticated-business/sass/blocks/_blocks.scss
sophisticated-business/style-editor.css
sophisticated-business/style-editor.scss
sophisticated-business/style-rtl.css
sophisticated-business/style.css

- Removes the hard coded 60% widths in the Media & Text block so that users can override this setting with the Block editor.
- Also removes some unnecessary menu styles for `[focus-within]` in Friendly Business. This appears to be a separate issue with the Sass compiler. 
See #644 
To test pull in this PR and make sure that the Media & Text block displays with 50% / 50% proportions and make sure that the proportions are flexible (like the _after_ screenshot above).

Multiple themes: Fixes hard coded column width for Media & Text Block

---

calm-business/style-editor.css
calm-business/style-editor.scss
calm-business/style-jetpack.css
calm-business/style-jetpack.scss
elegant-business/style-editor.css
elegant-business/style-editor.scss
elegant-business/style-jetpack.css
elegant-business/style-jetpack.scss
friendly-business/style-editor.css
friendly-business/style-editor.scss
friendly-business/style-jetpack.css
friendly-business/style-jetpack.scss
modern-business/style-editor.css
modern-business/style-editor.scss
modern-business/style-jetpack.css
modern-business/style-jetpack.scss
professional-business/style-editor.css
professional-business/style-editor.scss
professional-business/style-jetpack.css
professional-business/style-jetpack.scss
sophisticated-business/style-editor.css
sophisticated-business/style-editor.scss
sophisticated-business/style-jetpack.css
sophisticated-business/style-jetpack.scss

Ideally, this simple style fix should be added to the block itself, but we can't wait for the fix to land in WP.com for Onboarding.
We should remove this when the style is added in the block and becomes available in WP.com.
Fixes: #757

Temp. fix for Jetpack Business Hours Block style for all 6 style variations

---

calm-business/style-editor.css
calm-business/style-editor.scss
calm-business/style-jetpack.css
calm-business/style-jetpack.scss
elegant-business/style-editor.css
elegant-business/style-editor.scss
elegant-business/style-jetpack.css
elegant-business/style-jetpack.scss
friendly-business/style-editor.css
friendly-business/style-editor.scss
friendly-business/style-jetpack.css
friendly-business/style-jetpack.scss
modern-business/style-editor.css
modern-business/style-editor.scss
modern-business/style-jetpack.css
modern-business/style-jetpack.scss
professional-business/style-editor.css
professional-business/style-editor.scss
professional-business/style-jetpack.css
professional-business/style-jetpack.scss
sophisticated-business/style-editor.css
sophisticated-business/style-editor.scss
sophisticated-business/style-jetpack.css
sophisticated-business/style-jetpack.scss

Ideally, this should be fixed in the block itself and the Twenty Nineteen compat file in Jetpack, but we can't wait for those for Onboarding.
* 100% width input field
* Smaller consent text
See #760

Temp style enhancements for Mailchimp block for all 6 style variations

---

sophisticated-business/sass/blocks/_blocks.scss
sophisticated-business/style-rtl.css
sophisticated-business/style.css

Fixes font weight for legacy Cover block classes: `.wp-block-cover-text` and `.wp-block-cover-image-text`.
#803

Sophisticated Business: Fixing font-weight for legacy cover block

---

calm-business/sass/blocks/_blocks.scss
calm-business/style-rtl.css
calm-business/style.css
elegant-business/sass/blocks/_blocks.scss
elegant-business/style-rtl.css
elegant-business/style.css
friendly-business/sass/blocks/_blocks.scss
friendly-business/style-rtl.css
friendly-business/style.css
modern-business/sass/blocks/_blocks.scss
modern-business/style-rtl.css
modern-business/style.css
professional-business/sass/blocks/_blocks.scss
professional-business/style-rtl.css
professional-business/style.css
sophisticated-business/sass/blocks/_blocks.scss
sophisticated-business/style-rtl.css
sophisticated-business/style.css

Fixes #746 
It might not ideal to add our own utility class for a space block, but until when we have wpcom stylesheet, we can leave it here.
Testing:
* Add a spacer block to a page.
* Add a css class`desktop-only` to the block.
* View it with under 786px viewport.

All style variations: Add a utility css class for spacer block

---

calm-business/sass/blocks/_blocks.scss
calm-business/sass/site/primary/_posts-and-pages.scss
calm-business/style-rtl.css
calm-business/style.css

Removes the top margin of the first child element of `.entry-content`.
@iamtakashi, I didn’t see an original issue for this theme, but I figured it needed the fix any way. If we don’t need it fixed in this theme, you can go ahead and close/reject this PR. See #999 for similar issue.

Calm Business: Make sure the first block has margin-top: 0

---

modern-business/sass/site/header/_site-header.scss
modern-business/sass/typography/_headings.scss
modern-business/style-editor.css
modern-business/style-editor.scss
modern-business/style-rtl.css
modern-business/style.css

This change will update the modern business theme to pull in the header styles into the editor through the style-editor.scss file. This means that when using the full site editing plugin, you will see almost a one to one representation of the header design in the editor vs the front end.
To test this:
* Install the modern business theme locally
* Confirm that the contents and design of the header match the front end closely (there will be some difference in spacing between the blocks)
* Confirm that with the full site editing plugin disabled, the old template file based header works as expected.
* https://github.com/Automattic/wp-calypso/issues/34387 
* …

Update modern business to support the full site editing plugin header

---

elegant-business/sass/site/header/_site-header.scss
elegant-business/sass/typography/_headings.scss
elegant-business/style-editor.css
elegant-business/style-editor.scss
elegant-business/style-rtl.css
elegant-business/style.css

This change will update the elegant business theme to pull in the header styles into the editor through the style-editor.scss file. This means that when using the full site editing plugin, you will see almost a one to one representation of the header design in the editor vs the front end:
To test this:
* Install the elegant business theme locally
* Paste the following into the editor: https://codepen.io/apeatling/pen/rEbvMN and update/publish the header template.
* Confirm that you see a header that matches the screenshot above, and this looks identical on the front end of the site.
* Confirm that with the full site editing plugin …

Update the Elegant Business theme to support FSE header

---

_dsgnsystm/package.json

Adds the ability to use the theme dev utils scripts. Specifically adds support for `npm run child-theme` to create a new child theme based on the _dsgnsystm parent theme.
Closes #1037

Adds Child Theme commands to npm run commands

---

friendly-business/sass/site/header/_site-header.scss
friendly-business/sass/typography/_headings.scss
friendly-business/style-editor.css
friendly-business/style-editor.scss
friendly-business/style-rtl.css
friendly-business/style.css

This change will update the friendly business theme to pull in the header styles into the editor through the style-editor.scss file. This means that when using the full site editing plugin, you will see almost a one to one representation of the header design in the editor vs the front end:
To test this:
* Install the friendly business theme locally
* Paste the following into the editor: https://codepen.io/apeatling/pen/VJNZVJ and update/publish the header template.
* Confirm that you see a two column header that matches the screenshot above, and this looks identical on the front end of the site.
* Confirm that with the full site …

Update the Friendly Business theme to support FSE header

---

friendly-business/sass/site/header/_site-header.scss
friendly-business/sass/typography/_headings.scss
friendly-business/style-editor.css
friendly-business/style-editor.scss
friendly-business/style-rtl.css
friendly-business/style.css
professional-business/sass/site/header/_site-header.scss
professional-business/sass/typography/_headings.scss
professional-business/style-editor.css
professional-business/style-editor.scss
professional-business/style-rtl.css
professional-business/style.css

This change will update the professional business theme to pull in the header styles into the editor through the style-editor.scss file. This means that when using the full site editing plugin, you will see almost a one to one representation of the header design in the editor vs the front end:
To test this:
* Install the professional business theme locally
* Paste the following into the editor: https://codepen.io/apeatling/pen/VJNZVJ and update/publish the header template.
* Confirm that you see a two column header that matches the screenshot above, and this looks identical on the front end of the site.
* Confirm that with the full …

Update the Professional Business theme to support FSE header

---

calm-business/sass/site/header/_site-header.scss
calm-business/sass/typography/_headings.scss
calm-business/style-editor.css
calm-business/style-editor.scss
calm-business/style-rtl.css
calm-business/style.css
sophisticated-business/sass/site/header/_site-header.scss
sophisticated-business/sass/typography/_headings.scss
sophisticated-business/style-editor.css
sophisticated-business/style-editor.scss
sophisticated-business/style-rtl.css
sophisticated-business/style.css

This change will update the calm business theme to pull in the header styles into the editor through the style-editor.scss file. This means that when using the full site editing plugin, you will see almost a one to one representation of the header design in the editor vs the front end:
To test this:
* Install the calm business theme locally
* Paste the following into the editor: https://codepen.io/apeatling/pen/rEbvMN and update/publish the header template.
* Confirm that you see a header that matches the screenshot above, and this looks identical on the front end of the site.
* Confirm that with the full site editing plugin …

Update the Calm Business theme to support FSE header

---

sophisticated-business/sass/site/header/_site-header.scss
sophisticated-business/sass/typography/_headings.scss
sophisticated-business/style-editor.css
sophisticated-business/style-editor.scss
sophisticated-business/style-rtl.css
sophisticated-business/style.css

This change will update the Sophisticated Business theme to pull in the header styles into the editor through the style-editor.scss file. This means that when using the full site editing plugin, you will see almost a one to one representation of the header design in the editor vs the front end:
To test this:
* Install the Sophisticated Business theme locally
* Paste the following into the editor: https://codepen.io/apeatling/pen/VJNZVJ and update/publish the header template.
* Confirm that you see a two column header that matches the screenshot above, and this looks identical on the front end of the site.
* Confirm that with the …

Update the Sophisticated Business theme to support FSE header

---

modern-business/style-editor.css
modern-business/style-editor.scss

- Make the post content block 100% width. As a result, the post content block takes up the same area that the post editor container takes up without the post content block. This is important because the theme styles do alignment of blocks based on the style of outer 
- Allow nested blocks inside the post content block to maintain the default alignment styles for top level blocks. Previously, they were targeted as 2nd level blocks, and were thus being set to a much wider width.
I did this by targeting `.wp-block[data-type="a8c/post-content"]` because we need to set the width of the outer block container. Additionally, I needed to override the default block alignment styles for 2nd level blocks inside the , so I used `.wp-block[data-type="a8c/post-content"] .wp-block` to target those. I …

Full Site Editing: Fix post content nested block alignment on modern business

---

modern-business/footer.php
modern-business/functions.php
modern-business/header.php
modern-business/inc/fse-template-data.php

This adds required functionality to support rendering FSE header and
footer on all site pages (static and dynamic). It's also includes the
data population functionality, which has now been removed from the plugin
and will be delegated to each theme for maximum flexibility.
This PR requires its FSE counterpart PR to work properly. Please follow the testing instructions provided there: https://github.com/Automattic/wp-calypso/pull/34640

Modern Business: add FSE support

---

redhill/sass/style-child-theme-editor.scss
redhill/style-editor.css
redhill/style-rtl.css

- Fixes the editor fonts so that they appear in the editor the same way they do on the frontend.
- This was achieved by adding some “Extra” css to the child-theme editor stylesheet.
- Also recompiles the RTL stylesheet to match with changes to master
**Before**
**After**
This issue was discovered by @thomasguillot via Slack.

Redhill: Fix fonts in editor to match the frontend

---

modern-business/inc/fse-template-data.php
modern-business/sass/site/footer/_site-footer.scss
modern-business/style-editor.css
modern-business/style-editor.scss
modern-business/style-rtl.css
modern-business/style.css

This updates the modern business theme to support the footer in the editor and the correct styles. The footer includes a visual separator block, and the navigation block.
To test:
1. Activate the modern business theme from this branch
2. Delete all templates and template parts from the menus (Page Template, and Header, Footer).
3. Delete the "modern-business-fse-template-data" entry in the wp-options table.
4. Switch to a different theme, and then back to modern business.
5. Check that the footer looks like it does above, and works correctly on the front end of the site.
6. Disable the FSE plugin and check that you see equivalent to this in the footer (this message will be added to the dynamic footer in a separate PR):
Issue for reference: …

Update the Modern Business theme to support FSE footer

---

_dsgnsystm/sass/layout/_structure.scss
_dsgnsystm/style-rtl.css
_dsgnsystm/style.css

Increase the gap so that it has a clear separation.
Before:
After:

_dsgnsystm: Add more vertical space between posts

---

modern-business/footer.php
modern-business/header.php
modern-business/sass/site/footer/_site-footer.scss
modern-business/style-editor.css
modern-business/style-rtl.css
modern-business/style.css

Shows the default site info line after the footer template part
content. Also adds header and footer tags to corresponding template
parts to bring them closer to overall theme's structure.
Fixes https://github.com/Automattic/wp-calypso/issues/34754
Fixes https://github.com/Automattic/wp-calypso/issues/34423
1. Enable latest versions of FSE plugin and Modern Business theme on your test site.
2. Verify that rendered pages show the following text after the FSE footer:
`[Site Name], Proudly powered by WordPress`

Full Site Editing: restore site info when rendering the footer

---

modern-business/footer.php

Remove code duplication and add a note about full site editing.
To test:
* Activate the theme with the full site editing plugin enabled.
* Confirm you see the following in the footer on the front end:
With FSE activated:
With FSE deactivated (plus any widgets above):

Update the Modern Business footer to remove code duplication

---

friendly-business/style-editor.css
friendly-business/style-editor.scss

This extends the changes proposed in https://github.com/Automattic/themes/pull/1072 to the friendly business theme. It also fixes header/footer alignment issues mentioned in the other PR which would affect themes with wide headers like this one.
1. Activate the friendly business theme from this PR.
2. Also activate FSE with this companion FSE plugin PR: https://github.com/Automattic/wp-calypso/pull/34691
3. Create a new page from the pages screen.
4. Select the "small business" template
5. The full width blocks (side by side text/picture) should extend to the edge of the screen.
6. The normal paragraphs should be narrower in the middle, and most of the stuff should be centered in the middle.
7. Ultimately, the style of the post content in the page editor with FSE should look identical to …

Fix block alignment in FSE context for friendly business

---

modern-business/footer.php
modern-business/sass/navigation/_menu-footer-navigation.scss
modern-business/sass/navigation/_menu-main-navigation.scss
modern-business/style-editor.css
modern-business/style-rtl.css
modern-business/style.css

Update Modern Business CSS to support the navigation block, and the fallback when a menu has not been created. The fallback is building a page list that utilizes the same CSS that the regular menu does:
Note that the main difference is the lack of down arrow icon to denote that there are submenus. This is highlight specific to the twenty nineteen / our business themes, and not possible to replicate on the fallback menu as it is currently implemented.
https://github.com/Automattic/wp-calypso/pull/34796

Update Modern Business to support the navigation block default menu fallback

---

modern-business/inc/fse-template-data.php

**DO NOT MERGE**: Requires https://github.com/Automattic/wp-calypso/pull/34797
We disabled alignment settings for the blocks, but the template content function here still has alignment in it. This produces a template conflict warning in the editor:
- Remove alignment attributes from template part blocks in `get_template_content`
1. Have the `master` copy of this theme running.
2. This is going to be odd, but use your local FSE environment for this. Make sure you have master up to date, and **comment out** a line of code. You can find it here: `/wp-calypso/apps/full-site-editing/full-site-editing-plugin/full-site-editing/editor/index.js`. You want to comment out the line `import './template-validity-override';`, and make sure that you have the FSE watch command running.
3. Go to a page in …

Fix a template conflict issue with modern business

---

varia/inc/style-wpcom.css

Since this is for WP.com only, it's a bit awkward to test :)
Before:
After:

Varia: Reduce gap between header and content when homepage title is hidden.

---

varia/sass/blocks/media-text/_editor.scss
varia/sass/blocks/media-text/_style.scss
varia/style-editor.css
varia/style-rtl.css
varia/style.css

Have links inherit the color only when the block (Media & Text or Paragrpah) are using a background color
This splits the commits at #1122 into two separate PRs. This one provides a fix for Varia.
Fixes #1113 for Varia

Varia: Revising #1122 again

---

varia/sass/blocks/_editor.scss
varia/sass/blocks/_imports.scss
varia/sass/blocks/button/_style.scss
varia/sass/blocks/image/_style.scss
varia/sass/blocks/posts-list/_editor.scss
varia/sass/blocks/posts-list/_style.scss
varia/style-editor.css
varia/style-rtl.css
varia/style.css

This PR adds a default styles and variables to the a8c Posts List block. 
- Optimize selector nesting
- Add style for `featured` span to match archives
- Add vertical spacing to match index/archives
- Add link color to meta data and clean up spacing
- Use small font-size in meta data'
- Also fixes a [responsive image bug](https://github.com/Automattic/themes/compare/varia_add_posts_list_block_support?expand=1#diff-480b74bc7d291227b08c24b6af8b67e4R13), originally reported here: #1085 
Fixes: #1097 
Once this PR is merged, we’ll need to re-build all child themes based on Varia, so that they _automatically_ adopt these new styles.

Varia: Add posts list block support

---

varia/sass/abstracts/_mixins.scss
varia/sass/abstracts/_responsive-logic.scss
varia/sass/blocks/cover/_style.scss
varia/sass/blocks/gallery/_style.scss
varia/sass/blocks/group/_style.scss
varia/sass/blocks/pullquote/_style.scss
varia/style-rtl.css
varia/style.css

Fixes responsive logic to prevent content/text from reaching the absolute edge of any container or viewport edge. Effects Group Block, Cover Block, Pullquote Block, and Gallery Blocks.
- Revises responsive logic Sass rules to allow for smarter padding on small screens. 
- Focuses the responsive logic on `.alignwide` and `.alignfull` since normal width have the correct width already. 
- Sets 50% max-width on `.alignright` and `.alignleft` Gallery Blocks.
- Try the Group Block, Cover Block, Pullquote Block, and Gallery Blocks and make sure the text contained within them never touches the edge of the screen or the widest edge of its parent container.
Found while testing locally.

Varia: Fix responsive logic for better mobile view

---

varia/sass/abstracts/_mixins.scss
varia/sass/blocks/spacer/_style.scss
varia/style-rtl.css
varia/style.css

This PR limits the spacer-block to a 16px height (to match mobile vertical margins). This might be a bit aggressive and may not expected, but it does greatly improve the scrolling experience on mobile for the templates I tried this with. When we need to, we can use empty new lines in text areas in our templates to `fake` a taller spacer area on mobile, if needed.
This PR also forces zero vertical margins on mobile screens, which is also aggressive (as it uses `!important`) but still necessary to maintain consistency. 
Discovered while testing locally.

Varia: Improve spacer blocks on Mobile

---

leven/sass/_config-child-theme-deep.scss
leven/sass/_extra-child-theme.scss
leven/style-rtl.css
leven/style.css
leven/template-parts/header/site-branding.php

- Adds an overwriting template for site-branding and move the site-logo to its own container
- Revising css-grid areas for more flexibility
- Makes sure the site-title and main-navigation have the same baseline
**Before:**
**After:**
Discovered by @ianstewart

Leven: Refactoring the header to be more flexible

---

modern-business/inc/fse-template-data.php

Require https://github.com/Automattic/wp-calypso/pull/34997
Remove the Group block from the default header and footer template parts created when activating Modern Business and Full Site Editing.
The Group block's only purpose was to apply the theme's header and footer classes to the template part wrapper.
This is avoided by moving the classes away from the Group block and to the actual Template Part block.
https://github.com/Automattic/wp-calypso/issues/34887

Modern Business: Apply theme classes to the FSE template part instead of to a Group block inside it

---

modern-business/functions.php

Editor color palettes require two parts to work:
- One in PHP where we define the colors names and codes, which is used by the editor.
- One in CSS where we assign styles to the classes automagically generated by the editor.
Modern Business only has the CSS part, while inheriting the PHP one from Twenty Nineteen.
This means that, for example, the Primary color is blue in the editor (as defined by [Twenty Nineteen `functions.php`](https://github.com/WordPress/twentynineteen/blob/e74d348ab9cfc6ad46bdf33f691611930c39e944/functions.php#L141-L171)), and pink on the front-end (as defined by [Modern Business CSS](https://github.com/Automattic/themes/blob/0afe9f26f9b91d3710fa5a9d32ac5b1d9a8210ce/modern-business/sass/blocks/_blocks.scss#L1045-L1098)).
* Add the `editor-color-palette` theme support …

Modern Business: Add editor palette support to the functions.php

---

modern-business/style-editor.css
modern-business/style-editor.scss

Previously, the block would jump around. This makes those consistent and makes sure that they are also applied during block focus.
**Before:**
**After:**
- Make sure site description styles are also applied to `:focus` of block
- Add line height to prevent the block from jumping around in the editor. The value (0.8em) is rounded up from the actual text size value (0.71111em) to make sure that the tops of characters do not get cut off.
- You'll want your local FSE setup to be good to go. 
- Map the theme location to your testing environment. Using docker, you can add it as a volume.
- Make sure you have the modern business theme activated.
- Open the site header template part editor
- Click into the site description block. The position of the text should not move whatsoever, even on the …

FSE: Add line height to site description block to prevent jump

---

modern-business/footer.php
modern-business/header.php
modern-business/inc/fse-template-data.php

Renames `wp_template_part` to `wp_template` and in general all occurrences of the word "part".
Fixes https://github.com/Automattic/wp-calypso/issues/35079
1. Follow the testing instructions available in https://github.com/Automattic/wp-calypso/pull/35080.

Modern Business: rename template parts to templates

---

modern-business/functions.php
modern-business/inc/fse-template-data.php

Previously our template parts data was hardcoded in the theme.
This has been updated so it is now fetched from the WordPress.com API.
Fixes https://github.com/Automattic/wp-calypso/issues/34924
1. Sandbox the public API.
2. Apply D31186-code to your sandbox.
3. Map this theme to your local Gutenberg Docker dev environment, in a similar fashion you do for FSE plugin: `{themes_repo_path}/themes/modern-business:/var/www/html/wp-content/themes/modern-business`
4. On your local test site, delete all of the Templates that were previously created.
5. Delete `modern-business-fse-template-data` option if it was set on your site. Otherwise this would prevent data population here https://github.com/Automattic/themes/pull/1167/files#diff-8573df061382abec8228a31b5eb02880R84.
6. Activate Modern …

Modern Business: add remote template fetching for FSE

---

modern-business/inc/fse-template-data.php
modern-business/sass/site/header/_site-header.scss
modern-business/style-editor.css
modern-business/style-editor.scss
modern-business/style-rtl.css
modern-business/style.css

* Add a site logo placeholder to the FSE header template along with relevant editor and front end styles
* Build Modern Business theme and copy to  FSE test environment, and then follow test instructions at https://github.com/Automattic/wp-calypso/pull/35152
https://github.com/Automattic/wp-calypso/pull/35152
https://github.com/Automattic/wp-calypso/issues/35124

FSE: Modern business - add site logo placeholder to header template

---

modern-business/sass/navigation/_menu-main-navigation.scss
modern-business/style-editor.css
modern-business/style-rtl.css
modern-business/style.css

Since we set the order of footer/header elements (like nav) in Gutenberg, we don't want the stylesheet to override it. The order property was causing the footer nav menu in FSE to show up at very bottom of the page, even if the user changed its order.
- If the body has the `.fse-enabled` selector, reset the order property.
0. If the PR following has not been merged yet, pull the changes in https://github.com/Automattic/wp-calypso/pull/35209 and run it for FSE in your local install.
1. Pull this PR and make sure you have modern business mapped to your local install.
1. Edit the footer template. Move (or insert if you don't have it) the nav menu block to the top of the footer area.
2. Previously, the nav menu would have still shown up at the bottom of the footer. (See issue below.) Verify …

Modern business: Disable nav menu order if FSE is enabled

---

modern-business/style-editor.css
modern-business/style-editor.scss
modern-business/style-rtl.css
modern-business/style.css

Handle background color of editor for FSE. I thought one would just add `.editor-styles-wrapper`, but it turns out that Gutenberg automagically prefixes every selector inside the editor stylesheet! So to target the background of the editor, you actually use `body`. See more info on that [here](https://github.com/WordPress/gutenberg/blob/0ad0414e7a469254ef1ad105fdcf14248a986686/docs/designers-developers/developers/themes/theme-support.md#editor-styles). 
0. Use this FSE PR on your local setup: https://github.com/Automattic/wp-calypso/pull/35235
1. Pull this branch and make sure you have modern business mapped to your local setup.
2. Open the page editor and the template editor.
3. The background color of each should be `#fff` as set by the theme.
4. Change the background property to …

Modern Business: Set editor background color for FSE

---

varia/sass/blocks/media-text/_editor.scss
varia/sass/blocks/media-text/_style.scss
varia/style-editor.css
varia/style-rtl.css
varia/style.css

This add consistant vertical margins to all elements (now the block takes anything). Also it makes slight adjustment in the padding around the text column.
Fixes #1226 
Before:
After:

Varia: Add consistant vertical margins to elements in Media & Text block

---

modern-business/style-editor.css
modern-business/style-editor.scss

* Removes the 100% width alignment on site-logo figure which is stopping site logo centre aligning on smaller screens
* Checkout this patch, rebuild the modern-business theme and copy to FSE test environment
* When editing a page check that the site logo remains centre aligned in the header template block even on small screens.
**before**
**after**
Fixes https://github.com/Automattic/wp-calypso/issues/35245

FSE - remove 100% in figure to allow centre alignment on smaller screens

---

modern-business/sass/site/header/_site-header.scss
modern-business/style-editor.css
modern-business/style-editor.scss
modern-business/style-rtl.css
modern-business/style.css

Adjust the `alignfull` blocks width and positioning when rendered in the header template part to be properly full-width.
| | Before | After |
| - | - | - |
| Template Editor | ![Screenshot 2019-08-12 at 17 36 06](https://user-images.githubusercontent.com/2070010/62881627-1af33a00-bd28-11e9-9fc6-2645d6cd971b.png) | ![Screenshot 2019-08-12 at 17 32 14](https://user-images.githubusercontent.com/2070010/62881651-2ba3b000-bd28-11e9-878d-5cbb455023f0.png) |
| Page Editor | ![Screenshot 2019-08-12 at 17 34 14](https://user-images.githubusercontent.com/2070010/62881681-3d855300-bd28-11e9-9159-c0a33c54d894.png) | ![Screenshot 2019-08-12 at 17 31 59](https://user-images.githubusercontent.com/2070010/62881732-555cd700-bd28-11e9-8f17-24f9b364cfd0.png) |
| Front End | ![Screenshot 2019-08-12 at 17 36 …

FSE / Modern Business: Fix full width blocks in the header template part

---

modern-business/sass/blocks/_blocks.scss
modern-business/style-editor.css
modern-business/style-editor.scss
modern-business/style-rtl.css
modern-business/style.css

* Add css to left align the footer separator and nav menu to match the editor styling
* Build modern business and apply to FSE test environment
* Check that the the horizontal alignment of any block added to the footer matches across the page view, template edit view and the front end.
* Check that side padding is adding correctly on smaller screens to stop blocks being pushed hard against the edge
**notes:** 
* This issue occurred in both local and WP.com Simple sites. I have tested in Sandboxed simple site  - feel free to double check the fix in both also.
* Vertical alignment is still not perfect between these views, but close!
**Before**
**After**
https://github.com/Automattic/wp-calypso/issues/35389

Modern Business: FSE - fix footer alignment in front end

---

friendly-business/package-lock.json
friendly-business/style-editor.css
friendly-business/style-editor.scss
modern-business/package-lock.json
modern-business/style-editor.css
modern-business/style-editor.scss

Affects friendly business and modern business. Also renamed one or two things to "template" from "template part".
Note that the only changes I made were in *.scss files. The .css and package lock files are autogenerated.
1. Make sure you have both modern business and friendly business mapped to your local FSE setup
2. Make sure you have FSE active on your this site.
3. Pull this branch.
4. Activate the modern business theme.
5. Open the page editor and make sure the styles look correct. If the new selector is failing, things would be very messed up, like paragraphs in post content extending the full width of the screen.
6. Inspect the post content block and verify the style is getting applied correctly:
7. Inspect a block nested inside the post content block and verify the style is …

FSE: Use new classnames instead of data-type selectors

---

varia/footer.php
varia/header.php

As it was done for Modern Business, add the Full Site Editing template parts to the header and footer of the Varia theme.
They should be also inherited by the Varia children themes, such as Maywood, unless they overwrite the `header.php` and `footer.php` files.
* Apply D31833-code and sandbox the API.
* Apply https://github.com/Automattic/wp-calypso/pull/35698 on an FSE site.
* On that site, change theme from Modern Business to Varia.
* Edit a page and make sure the template parts are still there in the editor.
* Check edit.php?post_type=wp_template and make sure that there are new Header and Footer template parts (although, virtually identical to the Modern Business ones).
* View a page in the front end. It should have the FSE Header and Footer instead of the original Varia template …

Full Site Editing: Add the Header and Footer template parts to the Varia front end

---

varia/sass/blocks/latest-posts/_editor.scss
varia/sass/blocks/latest-posts/_style.scss
varia/sass/blocks/utilities/_editor.scss
varia/sass/blocks/utilities/_style.scss
varia/style-editor.css
varia/style-rtl.css
varia/style.css

- Adds more styles to better support changes to the Latest Posts blog. 
- Supports both grid and list views in both the editor and the frontend. 
- Fix text colors when latest posts block is nested in a cover block or any other block with the `.has-background` utility class. 
- _Does not_ remove underline from links, for better out-of-the-box a11y support. Child themes can easily opt-out of this with one line: `a { text-decoration: underline; }. 
Fixes: #1296

Varia: Add support for improved latest-posts block for Gutenberg 6.3

---

brompton/sass/_config-child-theme-deep.scss
coutoire/sass/_config-child-theme-deep.scss
exford/sass/_config-child-theme-deep.scss
hever/sass/_config-child-theme-deep.scss
leven/sass/_config-child-theme-deep.scss
morden/sass/_config-child-theme-deep.scss
redhill/sass/_config-child-theme-deep.scss
rockfield/sass/_config-child-theme-deep.scss
stow/sass/_config-child-theme-deep.scss
stratford/sass/_config-child-theme-deep.scss
varia/sass/blocks/cover/_config.scss
varia/sass/blocks/cover/_editor.scss
varia/sass/blocks/cover/_style.scss
varia/sass/child-theme/_config-child-theme-deep.scss
varia/style-editor.css
varia/style-rtl.css
varia/style.css

- Set default Cover Block colors to `background: #000` and `color: #FFF`. 
- Remove `calc()` from Cover Block height so we get `height: 480px` instead of `height: calc(15 * 32px)`.
- Update Cover Block config file to include background and foreground color overrides for easier child-theming
- Updates the `$config-cover` array in starter child-theme to include the new colors variables. 
- Updates the `$config-cover` array for all launched Varia child themes to prevent errors when recompiling after this merges.
Fixes: #1274

Varia: Update Cover Block default background-color and text color 

---

varia/footer.php
varia/header.php
varia/sass/full-site-editing/_editor.scss
varia/style-editor.css
varia/style-editor.scss

* Add the header and footer styles to `style-editor.scss`.
* Add the `.entry-content` class to the header and footer when in FSE context.
* Add some styles overrides for the FSE blocks in the header template.
* Adjust the Template block paddings.
* Stop `display: flex;` the footer to avoid incorrect positioning of the footer blocks.
* Add a responsive version of the main navigation, as featured in Varia and most Varia-based themes.
Please head over https://github.com/Automattic/wp-calypso/pull/35821

Varia: Add basic styling support for Full Site Editing

---

maywood/functions.php
modern-business/functions.php
varia/functions.php

* Add add_theme_support( 'full-site-editing') to each of the FSE themes so this can be used instead of a whitelist in the FSE plugin
Testing instructions at https://github.com/Automattic/wp-calypso/pull/35856

FSE: add fse theme support flag

---

maywood/sass/_full-site-editing-editor.scss
maywood/style-editor.css
varia/sass/full-site-editing/_editor.scss
varia/style-editor.css

Adjust the Content block vertical margin in the editor to look as close as possible to the front end.
- Varia contains the defaults for all the Varia-based themes.
- The bottom margin is not exactly the same as the front end.
This is because in the front end there is the "Edit" link in that space. I think it's not worthy to go pixel perfect in this case, and so I've just picked the multiple of 32 (for the sake of it) that looked as close as possible in Maywood.
- I've added a z-index to the Content block.
This is needed because the page title frame (or, if the title was hidden, any other block's toolbar etc.) could appear _behind_ the header Template block.
- As you might notice from the screenshot, the header spacing in Maywood is not as close as it should have been.
I've decided instead …

Full Site Editing / Varia, Maywood: Adjust the Content block vertical margins

---

maywood/sass/_full-site-editing.scss
maywood/style-rtl.css
maywood/style.css
varia/sass/full-site-editing/_imports.scss
varia/style.css

Change the default footer layout from `flex` to `block` in order to let the editor properly position and align all blocks inside the Footer template.
As a byproduct, the site info (e.g. "MAYWOOD, A WordPress.com Website.") is not inlined with the footer navigation menu as shown in the [Maywood demo](https://maywooddemo.wordpress.com/).
This is unavoidable, unless we want to add the site info as FSE block, and let the user move it as they see fit.
| | Editor | Front End |
| - | - | - |
| Before | ![Screenshot 2019-09-02 at 15 09 09](https://user-images.githubusercontent.com/2070010/64121764-ad22b700-cd97-11e9-8868-156ffa037f66.png) | ![Screenshot 2019-09-02 at 15 09 33](https://user-images.githubusercontent.com/2070010/64121863-df341900-cd97-11e9-8de3-ad729273ca25.png) |
| After | …

Full Site Editing / Varia, Maywood: Let the Editor Align the Footer Blocks

---

maywood/sass/_full-site-editing-editor.scss
maywood/style-editor.css
varia/style-rtl.css

| Front End | Editor Before | Editor After |
| - | - | - |
| ![Screenshot 2019-09-02 at 18 41 05](https://user-images.githubusercontent.com/2070010/64129429-d3565000-cdb3-11e9-8361-aef07a0f7ec1.png)|  ![Screenshot 2019-09-02 at 18 41 14](https://user-images.githubusercontent.com/2070010/64129417-ba4d9f00-cdb3-11e9-84b7-9f68dec9ac0c.png) | ![Screenshot 2019-09-02 at 18 54 14](https://user-images.githubusercontent.com/2070010/64129432-d8b39a80-cdb3-11e9-9f39-9bc68c2acd41.png) |
Tracked in https://github.com/Automattic/wp-calypso/issues/35870

Full Site Editing / Maywood: Add responsive style to the FSE blocks

---

maywood/sass/_full-site-editing-editor.scss
maywood/sass/_full-site-editing.scss
maywood/style-editor.css
maywood/style-rtl.css
maywood/style.css
varia/sass/full-site-editing/_editor.scss
varia/sass/full-site-editing/_imports.scss
varia/style-editor.css
varia/style-rtl.css
varia/style.css

* Change how the SCSS targets the Navigation block in Full Site Editing after the changes in https://github.com/Automattic/wp-calypso/pull/35998.
* Make the footer menu items padding consistent.
Note: some CSS changes here are unbuilt leftovers from other commits. Please only review the SCSS files.
Instructions and screenshots: see https://github.com/Automattic/wp-calypso/pull/35998
Requires https://github.com/Automattic/wp-calypso/pull/35998
Tracked by https://github.com/Automattic/wp-calypso/issues/35870

Full Site Editing / Varia, Maywood: Update the navigation menu 

---

maywood/style-rtl.css
maywood/style.css
varia/sass/full-site-editing/_imports.scss
varia/style-rtl.css
varia/style.css

* On FSE sites with FSE enabled, center the site info element after the footer template.
Note: some CSS changes here are unbuilt leftovers from other commits. Please only review the SCSS files.
Tracked by Automattic/wp-calypso#35870

Full Site Editing / Varia, Maywood: Center the site info

---

varia/search.php

Varia: Fix search page title alignment

---

varia/inc/template-tags.php

Assuming this wasn't intentional, this PR intends to fixes #1374 
**Before:**
**After:**

Varia: Show full size featured image in single view

---

maywood/sass/_full-site-editing.scss
maywood/style-rtl.css
maywood/style.css
varia/inc/style-editor-wpcom.css
varia/inc/wpcom.php

On WPCOM, Varia adds an option, which defaults to true, to hide the page title of the homepage.
I didn't know about it, and my tests on a local install of course didn't have this option.
* Add the `.hide-homepage-title` class to the block editor body as well.
* Enqueue a new stylesheet on the block editor that hides the homepage title and reposition the Post Content block.
* Restore the header's bottom padding on the front end's homepage when the page title is hidden.
| | Before | After |
| - | - | - |
| Editor | ![Screenshot 2019-09-06 at 16 05 42](https://user-images.githubusercontent.com/2070010/64438567-3e5b9b80-d0c0-11e9-9847-7f7b0eee7290.png) | ![Screenshot 2019-09-06 at 15 45 02](https://user-images.githubusercontent.com/2070010/64438430-005e7780-d0c0-11e9-9b4f-b8572c114888.png) | …

Full Site Editing / Varia, Maywood: Fix incorrect content positioning when the homepage title is hidden

---

maywood/sass/_extra-child-theme.scss
maywood/sass/_full-site-editing-editor.scss
maywood/sass/_full-site-editing.scss
maywood/style-editor.css
maywood/style-rtl.css
maywood/style.css
varia/sass/full-site-editing/_editor.scss
varia/style-editor.css

Themes apply some styles overrides to blocks inside Cover, for example changing the color and adding a text shadow.
* Make sure the FSE blocks (Site Title, Site Description, and Navigation Menu) look consistently when inserted inside and outside a Cover block.
* When inside a Cover block, change the color of Site Title and Site Description blocks to white, and add a text shadow. Remove the link underline from Site Title and Navigation Menu.
| | Before | After |
| - | - | - |
| Editor | <img width="943" alt="Screenshot 2019-09-24 at 11 15 10" src="https://user-images.githubusercontent.com/2070010/65506292-8a357f80-decb-11e9-8af5-3ba9a7a537d8.png"> | <img width="957" alt="Screenshot 2019-09-24 at 11 44 32" src="https://user-images.githubusercontent.com/2070010/65506297-8d307000-decb-11e9-84a …

Varia, Maywood: Fix FSE blocks style when inside a Cover block

---

varia/sass/blocks/separator/_editor.scss
varia/sass/blocks/separator/_style.scss
varia/style-editor.css
varia/style-rtl.css
varia/style.css

Fixes #1429
**Before**
**After**

Varia: Make sure separator is always visible with background colour

---

varia/sass/blocks/_editor.scss
varia/sass/blocks/group/_editor.scss
varia/style-editor.css

Fixes #1394 
This PR intends to change the behaviour of the full-width block inside a group block with a background to match with the front-end.
Also, it changes the padding for a group block with a background to match with the front-end.
**Before:**
**After:**

Varia: Change nested full-width block width inside group block

---

varia/sass/blocks/cover/_editor.scss
varia/sass/blocks/cover/_style.scss
varia/style-editor.css
varia/style-rtl.css
varia/style.css

Fixes #1435 
**After:**
_(The separator in the screenshot above should be fixed in #1430)_
**Testing instructions:**
1. Have a cover block with a very light overlay colour
2. Verify the text colour is in a dark colour that are set in `/sass/blocks/utilities/_style.scss`

Varia: Make sure elements inside cover block is always visible

---

varia/sass/blocks/quote/_editor.scss
varia/sass/blocks/quote/_style.scss
varia/style-editor.css
varia/style-rtl.css
varia/style.css

Varia: Remove unnecessary paddings from quote block

---

varia/sass/blocks/image/_style.scss
varia/style-rtl.css
varia/style.css

Fixes #1442 
**After:**
The size matchs in both editor and front end.

Varia: Remove auto width for image

---

varia/sass/blocks/_editor.scss
varia/sass/blocks/list/_editor.scss
varia/sass/blocks/list/_style.scss
varia/style-editor.css
varia/style-rtl.css
varia/style.css

Fixes #1441.  This should fix #1372 as well.
**After**
This makes the list item indented to inside, but it's much easier to read. Eventually, we'd want to introduce a new spacing config for lists with `em` unit so it works relatively with the font size.

Varia: Change list style position and indentation

---

varia/functions.php

After some further discussion, we decided to go in the opposite of the direction of the solution suggested in #1452 for a couple of reasons: 
1. A featured image on a Page is _not_ currently displayed anywhere in Varia based themes. Some users may have had featured images on Pages before switching to a Varia, so if we add support their sites may be disrupted with new featured images that they’ll have to remove page-by-page. 
2. We want to ultimately push customers toward editing with Gutenberg more directly and right now they’re isn’t a _direct_ way to control how or when they appear. 
More background info here: https://github.com/Automattic/themes/issues/1443#issuecomment-536743360
- Remove featured image support for Pages and only allow them for Posts.
#1452 
Fixes #1443 #1461

Varia: Remove featured image support for Pages

---

varia/sass/blocks/_editor.scss
varia/sass/blocks/image/_editor.scss
varia/sass/blocks/image/_style.scss
varia/style-editor.css
varia/style-rtl.css
varia/style.css

- Center image block by default in the editor.
- Corrects caption placement on small, resized image blocks.
- This is a temporary solution that allows images to display consistently between the editor and the frontend. The permanent solution needs to happen in Gutenberg. See here: https://github.com/WordPress/gutenberg/issues/13684
**Editor** | **Frontend**
------------ | ------------
Fixes #1407

Varia: Center image block by default.

---

shawburn/functions.php
shawburn/sass/_extra-child-theme.scss
shawburn/style-rtl.css
shawburn/style.css

Fixes #1449 
<table>
<tr>
<td>Before (Desktop):
<br><br>
</td>
<td>After (Desktop):
<br><br>
</td>
</tr>
</table>
<table>
<tr>
<td>Before (Mobile):
<br><br>
</td>
<td>After (Mobile):
<br><br>
</td>
</tr>
</table>
@iamtakashi To fix this issue, I've introduce a new `body_class` called `has-no-social-menu` to remain backwards compatibility.
And `npm run build` resulted in many additional CSS statements, which I've excluded to keep this PR clean. You mentioned that there's work in progress to automate the generation of child theme styles anyway. Therefore, I haven't shipped these unrendered changes with this PR.

FIX #1449: Solve primary menu display issue

---

alves/sass/_config-child-theme-deep.scss
balasana/sass/_config-child-theme-deep.scss
barnsbury/sass/_config-child-theme-deep.scss
dalston/sass/_config-child-theme-deep.scss
exford/sass/_config-child-theme-deep.scss
mayland/sass/_config-child-theme-deep.scss
maywood/sass/_config-child-theme-deep.scss
redhill/sass/_config-child-theme-deep.scss
rivington/sass/_config-child-theme-deep.scss
varia/sass/child-theme/_config-child-theme-deep.scss

- Adds `config-separator.width` variable to the base Varia child-theme variables array so it gets copied into new child-themes properly.
- Adds a width variable to the `config-separator` array for various child-themes to prevent potential compiling errors.
- Add `config-footer.font.line-height` default variable to Redhill.
Fixes: #1519

Varia + various child-themes: Add missing config variables

---

varia/sass/blocks/utilities/_style.scss
varia/style-rtl.css
varia/style.css

Fixes #1511
**Before**
**After**

Varia: Make sure centre aligned image in classic block is centred

---

exford/sass/_extra-child-theme.scss
exford/style-rtl.css
exford/style.css

Fixes #1416 
**Before:**
**After:**

Exford: Make sure sub-menu item is one line in Safari

---

varia/inc/template-functions.php
varia/sass/components/content/_entry-content.scss
varia/style-rtl.css
varia/style.css
varia/template-parts/content/content.php

- Adds a filter to add a “Continue reading ->” link to excerpts and full-post content when using the read-more block or the read-more classic comment.
**Note:** 
This change should be _non-destructive_, so all Varia child-themes can be re-compiled on this PR or on master branch after this is approved and committed. 
Fixes: #1576

Varia: Add `Continue reading ->` link filter for excerpts and read more blocks.

---

varia/functions.php

- Sets the _custom-logo_ `flex-height` and `flex-width` parameters to true so that customers are not forced to crop their logo and/or manually remove the crop area. 
- Customers can still crop their logos if they choose to.
- This change may require some logos to be resized manually before uploading to the customizer.
**Note**
- This change should be tested against a site that already has a logo setup with the previous logo size settings to make sure there’s no disruption when/if this change gets deployed.
Fixes: #1488

Varia: Restore the “Skip cropping” option to custom-logo setup.

---

maywood/sass/_extra-child-theme.scss
maywood/sass/_full-site-editing-editor.scss
maywood/sass/_full-site-editing.scss
maywood/sass/style-child-theme.scss
maywood/style-editor.css
maywood/style-rtl.css
maywood/style.css
varia/footer.php
varia/header.php
varia/sass/full-site-editing/_editor.scss
varia/sass/full-site-editing/_imports.scss
varia/style-editor.css
varia/style-rtl.css
varia/style.css

After adding the style attributes to all FSE blocks, I've realized that we are giving the user enough freedom that reusing the default theme classes makes things unnecessarily harder.
Once removing the theme classes, we can also remove a lot of now superfluous overrides.
I have tested this as thoroughly as possible, but in the end I think these are some relatively simple specs to test against.
This is what I've used in my tests. Feel free to reuse it, mix and match it, or try something else.
**Default header**
```html
<div class="wp-block-image size-large fse-site-logo"><figure class="aligncenter size-large is-resized"><img src="https://fsemaywooddemo.files.wordpress.com/2019/09/maywood-logo-e1569858169507.png" alt="maywood-logo" class="wp-image-25" width="188" height="134" …
```

Full Site Editing: Stop using theme classes for template parts

---

balasana/sass/_extra-child-theme.scss
balasana/sass/style-child-theme-woocommerce.scss
balasana/style-rtl.css
balasana/style-woocommerce-rtl.css
balasana/style-woocommerce.css
balasana/style.css

- Reverts the menu-toggle display to its original appearance when WooCommerce is _not_ activated.
- When WooCommerce _is_ activated, there isn’t enough horizontal space to display the site-title, the menu-toggle and the mini-cart-toggle on a single line at all times. When the viewport gets too narrow, the two toggle buttons have to move to their own line. Again, this only happens when WC is active. 
Fixes: #1637

Balasana: Revert menu display on mobile.

---

maywood/style-editor.css
maywood/style.css
varia/sass/full-site-editing/_editor.scss
varia/sass/full-site-editing/_imports.scss
varia/style-editor.css
varia/style.css

Fix a regression on Maywood, that caused `alignwide` and `alignfull` Navigation Menu blocks not having the expected width.
| Before (`alignwide`) | After (`alignwide`) |
| - | - |
| <img width="1132" alt="Screenshot 2019-11-11 at 20 24 42" src="https://user-images.githubusercontent.com/2070010/68618538-7a94e900-04c1-11ea-97b6-eb14ebee623e.png"> | <img width="1131" alt="Screenshot 2019-11-11 at 20 24 28" src="https://user-images.githubusercontent.com/2070010/68618550-81236080-04c1-11ea-83cf-a02692049954.png"> |

Varia, Maywood: Fix FSE Navigation Menu width when alignwide or alignfull

---

exford/functions.php
exford/sass/_full-site-editing-editor.scss
exford/sass/_full-site-editing.scss
exford/sass/style-child-theme-editor.scss
exford/sass/style-child-theme.scss
exford/style-editor.css
exford/style-rtl.css
exford/style.css
shawburn/sass/_full-site-editing.scss

This PR basically copies the Full Site Editing overrides created for Maywood into Exford.
It reuses the Maywood template parts, so they don't look exactly the same as the [Exford demo site](https://exforddemo.wordpress.com/).
Part of https://github.com/Automattic/wp-calypso/issues/37429
[Exford demo site](https://exforddemo.wordpress.com/) header for reference:
FSE header in the template part editor, right after applying this PR, without making any changes to the blocks:
FSE header in the editor and in the front end after changing the blocks attributes to make it look like the demo:
Note: I know the vertical margins are wider than the demo site, but it's a case of having the cake and eating it too.
Narrow margins make for a very poor editing experience in Gutenberg, and since we need the …

Exford: Add Full Site Editing Support

---

varia/sass/full-site-editing/_editor.scss
varia/style-editor.css

This change updates block margins to that header and footer template parts render close or identical to how they render when viewed when editing a page.
This will improve consistency when using full site editing, and also allow us to compress excess margins on blocks like the social icons block.
The main thing to test is Maywood, since this is the only live FSE theme. Apply this change to Varia, and then test Maywood to make sure that the header renders correctly when editing a page, and also renders correctly when editing the header template part.

Varia: Update margins to match in template editor view and main page view

---

varia/sass/full-site-editing/_editor.scss
varia/sass/full-site-editing/_imports.scss
varia/style-editor.css
varia/style.css

Varia by default adds large margins to child blocks inside of columns. This makes spacing in header and footers that use columns problematic. This removes these large margins and just adds a small bottom margin that lines up with the amount of margin we see in most template-first themes.
To test, check out this branch and rebuild the css in maywood. Check that the header and footer still render correctly.

Varia: Limit the margins on child blocks inside columns in template parts

---

hever/package-lock.json
hever/sass/_extra-child-theme.scss
hever/sass/_full-site-editing-editor.scss
hever/sass/_full-site-editing.scss
hever/sass/style-child-theme-editor.scss
hever/sass/style-child-theme.scss
hever/style-editor.css
hever/style-rtl.css
hever/style.css
varia/sass/full-site-editing/_editor.scss
varia/style-rtl.css

Add CSS column and block margin changes to Varia so that columns can be used to layout header and footer template parts more accurately.
To test:
1. Run a copy of WordPress locally with the Full Site Editing plugin installed, and Gutenberg plugin installed.
2. Install the hever and varia theme from this PR
3. Activate hever, and the two plugins
4. Create a new page and use the Hever homepage template, confirm that you see the header template as it appears in the visual above. Confirm this works correctly on the front end.

Hever: Add FSE support. 

---

morden/header.php
morden/languages/morden.pot
morden/package-lock.json
morden/package.json
morden/sass/_full-site-editing-editor.scss
morden/sass/_full-site-editing.scss
morden/sass/style-child-theme-editor.scss
morden/sass/style-child-theme.scss
morden/style-editor.css
morden/style-rtl.css
morden/style.css
varia/style-editor.css

* Added FSE support to Morden.
Note: since Morden has a multi-column header like Alves, I've checked out this branch off `add/alves-fse-support` to obtain the new Varia columns fixes.
They help a bit, but definitely not enough. Unfortunately working with the Columns block is just very wonky.
| Template | Page | Front End |
| - | - | - |
| <img width="1191" alt="Screenshot 2019-11-28 at 16 38 51" src="https://user-images.githubusercontent.com/2070010/69822277-dd92b980-11fd-11ea-9a9f-6f1861c81e41.png"> | <img width="1167" alt="Screenshot 2019-11-28 at 16 39 07" src="https://user-images.githubusercontent.com/2070010/69822280-e1bed700-11fd-11ea-8d05-9070d824a160.png"> | <img width="1177" alt="Screenshot 2019-11-28 at 16 39 18" src="https://user-images.githubusercontent.com/2070010/69822285-e42 …

Morden: Add Full Site Editing support

---

varia/sass/vendors/_jetpack.scss
varia/style-editor.css
varia/style-rtl.css
varia/style.css

Adds the same vertical margin logic used in `.entry-content` to content within the Layout Grid. 
**Before**|**After**
------------|------------
- Fixes #1672

Varia: Add vertical margins to blocks inside Jetpack’s Layout Grid block.

---

varia/sass/blocks/list/_editor.scss
varia/sass/blocks/list/_style.scss
varia/style-editor.css
varia/style-rtl.css
varia/style.css

- Allow list-item `li` text and bullets to respect text-alignment rules in the editor and frontend when it makes sense.
- Applies to both unordered `ul` and ordered `ol` lists whenever a text-align utility class is added to them.
- Also applies to core widget blocks like archives, categories and other lists that support text alignment options. 
**Before:**
**After:**
**Editor After:**
Fixes: #1597

Varia: Adds support for left, center and right aligned lists.

---

varia/inc/template-functions.php

- Remove "Post Type" from Projects Archive title 
- Add post-type singular name.
- Custom post type archives are _one-dimensional_ so there’s no need to point to a description with a  `:`.
Custom post type archive titles before: 
**Archives: Projects**, **Archives: Testimonials**, or **Archives: _Post type singular-name_**
Custom post type archive titles after: 
**Project Archives**, **Testimonial Archives**, or **_Post type singular-name_ Archives**
#1655

Varia: Remove "Post Type" from Projects Archive title

---

varia/functions.php

The skip-link-focus-fix involves custom JavaScript which is not allowed in AMP (in this way). In any case, the AMP framework has internalized this IE11 a11y fix per https://github.com/ampproject/amphtml/issues/18671 so there is no reason to add it on AMP pages.

Varia: Skip skip-link-focus-fix in AMP

---

button-2/editor-blocks.css

Fixes #1728 
<table>
<tr>
<td>Before:
<br><br>
</td>
<td>After:
<br><br>
</td>
</tr>
</table>

Button-2: Fix gallery block styles

---

independent-publisher-2/functions.php

If post word less than 250 words. Theme show 0 Minutes read time 0 is not plural.
Before:
_nx() function issue it assumes 0-0.9 to the plural and only 1 to single. I fixed it if the time less than 1 I explicitly set to 1.
After:
https://github.com/Automattic/themes/issues/699

Independent Publisher 2:  if post word less than 250 words  post show 0 minutes time to read solved.

---

button-2/blocks.css
button-2/editor-blocks.css
button-2/style.css

Fixes #1725 
<table>
<tr>
<td>Before:
<br><br>
</td>
<td>After:
<br><br>
</td>
</tr>
</table>

Button-2: Center image caption on frontend

---

varia/header.php

Starting from WordPress 5.2 a new function is added – `wp_body_open()` – that is used to trigger a `wp_body_open` action. The function should be placed inside of the <body> tag immediately after it is opened.

Add ‘wp_body_open’ hook.

---

dalston/functions.php
redhill/functions.php

This PR applies the fix from #1565 to Dalston & Redhill, which provide their own logo size settings that was overriding the fix in Varia.
- Removes the sizing constrains from custom logo to prevent too small images from getting scaled up.
- Fixes **Dalston** 
- Fixes **Redhill** 
**Before** | **After**
------------|------------
Forced cropping and low-quality scaled image.|Optional cropping & full-size high-quality image.
- Fixes: https://github.com/Automattic/themes/issues/1287
- #1565 
- #1363 (was fixed in #1565)

Multiple Varia Child Themes: Fix custom-logo support to prevent scaling up too small images.

---

mayland/functions.php
mayland/sass/_config-child-theme-deep.scss
mayland/style-editor.css
mayland/style-rtl.css
mayland/style-woocommerce-rtl.css
mayland/style-woocommerce.css
mayland/style.css

Simply removing the duplicate colors might cause disruptions for customers who have selected one of the two `#000000` colors in their editor content. As an alternative solution, I changed the Black color to `#010101` which isn’t perfect black but it’s close enough to _not_ cause an obvious disruption.
The difference is virtually indistinguishable as you can see here: 
- Change duplicate `#000000` theme color to `#010101` to fix key prop console errors.
- Replaces some instances of `black` and `white` keyword colors with their hex color equivalents to help distinguish between theme-specific colors, and similarly named general colors that come from Varia.
- Recompiles all stylesheets with the color change.
Fixes: #1659

Mayland: Fix key prop warning in Editor.

---

apostrophe-2/style.css
canard/style.css
gazette/style.css
illustratr/style.css
libretto/style.css
publication/style.css
rebalance/style.css
sketch/style.css

Pinterest links have dozens and dozens of TLDs, not just `.com` ones. Jetpack countered this in the last update by allowing any TLD to display the icon (Automattic/jetpack#11252). Themes should probably do the same, so I've tested this on Rebalance and Illustratr, and this should allow the Pinterest icon to display. 
There's quite a few things which should probably be updated with these social icons, for example, Path shut down a while ago. But that's a PR for another day, and there's a report of this specific issue already. 
Fixes #673

Multiple Themes: Fix Pinterest Icons Not Displaying

---

dyad-2/js/global.js

> The script function adjustPosts() in global.js, meant to apply the class “too-short” to the wrapper div, will ALWAYS apply this class, no matter the length of the content because the wrapper auto-adjusts itself to the exact height of that content. Which in turn will cause the “if smaller than or equal to” be true on all occasions.
• The above fix actually came from a user, but it seems to do the trick.
Fixes: #133 
Notice the `.too-short` class at the end of the class list at the bottom of this screenshot.
That class properly goes away after the fix is applied since the fade is no longer needed on short paragraphs. The fading is also gone here but its tough to see on the screenshot.

Dyad 2: Fix fade over short posts on blog page

---

shoreditch/css/blocks.css
shoreditch/css/editor-blocks.css
shoreditch/functions.php
shoreditch/inc/style-wpcom.css
shoreditch/inc/wpcom-colors.php
shoreditch/inc/wpcom.php
shoreditch/style.css
shoreditch/woocommerce-rtl.css
shoreditch/woocommerce.css

Fixes #1768
<table>
<tr>
<td>Before:
<br><br>
</td>
<td>After:
<br><br>
</td>
</tr>
</table>
<table>
<tr>
<td>Before:
<br><br>
</td>
<td>After:
<br><br>
</td>
</tr>
</table>
<table>
<tr>
<td>Before:
<br><br>
</td>
<td>After:
<br><br>
</td>
</tr>
</table>

Shoreditch: Make default color AA/AAA compliant

---

independent-publisher-2/style.css

Fixes #428
<table>
<tr>
<td>Before:
<br><br>
</td>
<td>After:
<br><br>
</td>
</tr>
</table>

Independent Publisher 2: Fix publication date issue

---

ixion/style.css

Fixes #1819 
<table>
<tr>
<td>Before:
<br><br>
</td>
<td>After:
<br><br>
</td>
</tr>
</table>

Ixion: Fix footer widget background color issue

---

ixion/blocks.css

Super minor edit of replacing that accidental full stop with a comma as mentioned in the issue (great spot!), but confirmed it fixes #635. Also confirmed this was just a one-off error and other styles use commas as expected.

Ixion: Fix Medium Grey Button

---

publication/blocks.css

Fixes #1828
<table>
<tr>
<td>Before:
<br><br>
</td>
<td>After:
<br><br>
</td>
</tr>
</table>

Publication: Adjust overlapping Blog Posts Block

---

varia/sass/blocks/button/_editor.scss
varia/sass/blocks/button/_style.scss
varia/sass/blocks/utilities/_style.scss
varia/style-editor.css
varia/style-rtl.css
varia/style.css

This PR updates the button style editor styles so that they work alongside Gutenberg 7.9. That release changed the button markup, and now the `.wp-block-button__link` class is applied on the same element as `.wp-block-button`. 
To test, please make sure you're running Gutenberg 7.9. This PR is essentially a mirror of https://github.com/Automattic/themes-workspace/pull/75/.
--
Before: 
After:

Varia: Fix button styles to work alongside Gutenberg 7.9

---

hever/functions.php

Using a `+` instead of a space here will cause the font name to be doubly encoded (as `PT%2BSans`), resulting in an error 400 when loading from Google Fonts.
@josephscott kindly validated the fix by testing on his sandbox.
Fix Google Font loading. Validate by checking in DevTools that it no longer produces an error 400 when attempting to load the font CSS.

Fix incorrect font name

---

scratchpad/editor-blocks.css

Fixes #1866
<table>
<tr>
<td>Before:
<br><br>
</td>
<td>After:
<br><br>
</td>
</tr>
</table>

Scratchpad: Fix list view in editor

---

altofocus/assets/stylesheets/editor-blocks.css

Related #1866
<table>
<tr>
<td>Before:
<br><br>
</td>
<td>After:
<br><br>
</td>
</tr>
</table>

AltoFocus: Fix list view in editor

---

apostrophe-2/css/editor-blocks.css

Related #1866
<table>
<tr>
<td>Before:
<br><br>
</td>
<td>After:
<br><br>
</td>
</tr>
</table>

Apostrophe 2: Fix list view in editor

---

canard/editor-blocks.css

Related #1866
<table>
<tr>
<td>Before:
<br><br>
</td>
<td>After:
<br><br>
</td>
</tr>
</table>

Canard: Fix list view in editor

---

ixion/editor-blocks.css

Related #1866
<table>
<tr>
<td>Before:
<br><br>
</td>
<td>After:
<br><br>
</td>
</tr>
</table>

Ixion: Fix list view in editor

---

rebalance/editor-blocks.css

Related #1866 
<table>
<tr>
<td>Before:
<br><br>
</td>
<td>After:
<br><br>
</td>
</tr>
</table>

Rebalance: Fix list view in editor

---

maywood/sass/_extra-child-theme.scss
maywood/sass/style-child-theme-editor.scss
maywood/style-editor.css
maywood/style-rtl.css
maywood/style.css

As suggested in #1837, this PR changes Maywood's behavior so that it only applies a text shadow to inner blocks if there's a background image in the color block.
Before: 
After:

Maywood: Only apply cover image text shadow if there's a background image or video.

---

apostrophe-2/css/blocks.css
independent-publisher-2/css/blocks.css
ixion/blocks.css
libre-2/css/blocks.css
radcliffe-2/assets/css/blocks.css

This PR assigns a `max-width` to the inner wrappers for the Cover and Group blocks. Doing so makes sure that inner blocks take up the proper width by default. This is not complete solution for Group block support in those themes, but it should mostly fix #1848. 
Themes included: 
- Apostrophe 2
- Independent Publisher 2
- Ixion
- Libre 2
To test, try out the Alves and Barnsbury homepage layouts in the themes above.
---
Before:
After:
Before:
After:
Before:
After:
Before:
After:

[Multiple Themes] Assign a max-width to containers in group and cover blocks. 

---

radcliffe-2/assets/css/blocks.css

Fixes #1941 
<table>
<tr>
<td>Before (left aligned):
<br><br>
</td>
<td>After (left aligned):
<br><br>
</td>
</tr>
</table>
<table>
<tr>
<td>Before (right aligned):
<br><br>
</td>
<td>After (right aligned):
<br><br>
</td>
</tr>
</table>

Radcliffe 2: Fix Social Icons Block alignment

---

varia/sass/vendors/woocommerce/elements/_password-strength-meter.scss
varia/style-woocommerce-rtl.css
varia/style-woocommerce.css

Varia: Fix CSS interpolation issue in password-strength-meter style

---

hever/style-woocommerce-rtl.css
hever/style-woocommerce.css

Hever: Fix Interpolation issue in password-strength-meter style

---

exford/style-woocommerce-rtl.css
exford/style-woocommerce.css

Exford: Fix Interpolation issue in password-strength-meter style

---

dalston/style-woocommerce-rtl.css
dalston/style-woocommerce.css

Dalston: Fix Interpolation issue in password-strength-meter style

---

barnsbury/style-woocommerce-rtl.css
barnsbury/style-woocommerce.css

Barnsbury: Fix Interpolation issue in password-strength-meter style

---

balasana/style-woocommerce-rtl.css
balasana/style-woocommerce.css

Balasana: Fix Interpolation issue in password-strength-meter style

---

alves/style-woocommerce-rtl.css
alves/style-woocommerce.css

Alves: Fix Interpolation issue in password-strength-meter style

---

shawburn/style-rtl.css
shawburn/style.css

Shawburn: Fix Interpolation issue in comment-meta style

---

maywood/style-woocommerce-rtl.css
maywood/style-woocommerce.css

Maywood: Fix Interpolation issue in password-strength-meter style

---

coutoire/style-woocommerce-rtl.css
coutoire/style-woocommerce.css

Coutoire: Fix Interpolation issue in password-strength-meter style

---

maywood/style-rtl.css
maywood/style.css

Maywood: Fix Interpolation issue in comment-meta style

---

alves/style-rtl.css
alves/style.css

Alves: Fix Interpolation issue in comment-meta style

---

balasana/style-rtl.css
balasana/style.css

Balasana: Fix Interpolation issue in comment-meta style

---

barnsbury/style-rtl.css
barnsbury/style.css

Barnsbury: Fix Interpolation issue in comment-meta style

---

coutoire/style-rtl.css
coutoire/style.css

Coutoire: Fix Interpolation issue in comment-meta style

---

dalston/style-rtl.css
dalston/style.css

Dalston: Fix Interpolation issue in comment-meta style

---

exford/style-rtl.css
exford/style.css

Exford: Fix Interpolation issue in comment-meta style

---

hever/style-rtl.css
hever/style.css

Hever: Fix Interpolation issue in comment-meta style

---

varia/sass/components/comments/_comments.scss
varia/style.css

Fixes #2009
Varia Theme: Fix comment avatar size for AMP pages.
Before on iPad AMP | After on iPad AMP
------------ | -------------
Before on iPad Non AMP | After on iPad Non AMP
------------ | -------------

Varia: Fix comment avatar image/position size on AMP pages

---

balasana/style-rtl.css
balasana/style.css

Fixes #2009
Balasana Theme: Fix comment avatar size for AMP pages.
|    ![image](https://user-images.githubusercontent.com/12055657/82036698-07b03900-96c3-11ea-9415-f52a8040a52d.png) |   ![image](https://user-images.githubusercontent.com/12055657/82036725-10087400-96c3-11ea-86a4-71b87337ff2e.png) |
|   ![image](https://user-images.githubusercontent.com/12055657/82036742-172f8200-96c3-11ea-8f48-288402be8eec.png) |  ![image](https://user-images.githubusercontent.com/12055657/82036772-1f87bd00-96c3-11ea-9c19-3dbf995d8f5c.png) |

Balasana: Fixes Comment avatar on amp pages

---

alves/style-rtl.css
alves/style.css

Fixes #2009
Alves Theme: Fix comment avatar size for AMP pages.
| ![image](https://user-images.githubusercontent.com/12055657/82035793-da16c000-96c1-11ea-85ca-d587b285f274.png) |  ![image](https://user-images.githubusercontent.com/12055657/82036239-76d95d80-96c2-11ea-8c92-200e9f332955.png)|
|   ![image](https://user-images.githubusercontent.com/12055657/82035835-e733af00-96c1-11ea-9ec5-f846ea8d5374.png)    |  ![image](https://user-images.githubusercontent.com/12055657/82036265-7fca2f00-96c2-11ea-9065-7cc8605467d7.png)|

Alves: Fixes Comment avatar on amp pages

---

hever/style-rtl.css
hever/style.css

Fixes #2009
Hever Theme: Fix comment avatar size for AMP pages.
|  ![image](https://user-images.githubusercontent.com/12055657/82038401-4e069780-96c5-11ea-81da-fad9fe4599d6.png)|  ![image](https://user-images.githubusercontent.com/12055657/82038418-5232b500-96c5-11ea-9239-3b622e4ec1e2.png)|
|   ![image](https://user-images.githubusercontent.com/12055657/82038428-565ed280-96c5-11ea-9635-f23bdc871704.png) |  ![image](https://user-images.githubusercontent.com/12055657/82038440-5bbc1d00-96c5-11ea-83bd-24725d5963f9.png)|

Hever: Fixes Comment avatar on amp pages

---

maywood/style-rtl.css
maywood/style.css

Fixes #2009
Maywood Theme: Fix comment avatar size for AMP pages.
|  ![image](https://user-images.githubusercontent.com/12055657/82038605-9625ba00-96c5-11ea-954c-fa66c73b570f.png) |   ![image](https://user-images.githubusercontent.com/12055657/82038614-9a51d780-96c5-11ea-8eca-e95bc8c4b76e.png)|
|   ![image](https://user-images.githubusercontent.com/12055657/82038636-a3db3f80-96c5-11ea-86bf-215bfa6b05aa.png)|   ![image](https://user-images.githubusercontent.com/12055657/82038648-a9388a00-96c5-11ea-86fa-45a180fed80d.png) |

Maywood: Fixes Comment avatar on amp pages

---

exford/style-rtl.css
exford/style.css

Fixes #2009
Exford Theme: Fix comment avatar size for AMP pages.
|   ![image](https://user-images.githubusercontent.com/12055657/82038170-f49e6880-96c4-11ea-9506-4c9625c4f9d3.png) |  ![image](https://user-images.githubusercontent.com/12055657/82038182-f8ca8600-96c4-11ea-8588-dbae1f63bb14.png) |
|   ![image](https://user-images.githubusercontent.com/12055657/82038196-fd8f3a00-96c4-11ea-92b7-eb79bd99b040.png)|   ![image](https://user-images.githubusercontent.com/12055657/82038206-0122c100-96c5-11ea-84b5-a0fc1389376d.png)|

Exford: Fixes Comment avatar on amp pages

---

shawburn/style-rtl.css
shawburn/style.css

Fixes #2009
Shawburn Theme: Fix comment avatar size for AMP pages.
|   ![image](https://user-images.githubusercontent.com/12055657/82038811-e9980800-96c5-11ea-8a9b-83217cb55758.png)|   ![image](https://user-images.githubusercontent.com/12055657/82038832-eef55280-96c5-11ea-8250-23eb203c83f1.png) |
|   ![image](https://user-images.githubusercontent.com/12055657/82038846-f3217000-96c5-11ea-9c5e-95f1ef24b1d0.png) |   ![image](https://user-images.githubusercontent.com/12055657/82038861-f9175100-96c5-11ea-8815-ec3084dc5fde.png) |

Shawburn: Fixes Comment avatar on amp pages

---

coutoire/style-rtl.css
coutoire/style.css

Fixes #2009
Coutoire Theme: Fix comment avatar size for AMP pages.
|   ![image](https://user-images.githubusercontent.com/12055657/82037888-96718580-96c4-11ea-8086-626cf23df4ed.png) | ![image](https://user-images.githubusercontent.com/12055657/82037908-9cfffd00-96c4-11ea-8e17-aaefef6bd2df.png) |
|  ![image](https://user-images.githubusercontent.com/12055657/82037920-a1c4b100-96c4-11ea-9aa1-d1180d862b66.png) |  ![image](https://user-images.githubusercontent.com/12055657/82037938-a5f0ce80-96c4-11ea-86d2-4f8d07a529ae.png) |

Coutoire: Fixes Comment avatar on amp pages

---

dalston/style-rtl.css
dalston/style.css

Fixes #2009
Dalston Theme: Fix comment avatar size for AMP pages.
|    ![image](https://user-images.githubusercontent.com/12055657/82037510-0fbca880-96c4-11ea-8ef4-0ec2fb62279c.png)|   ![image](https://user-images.githubusercontent.com/12055657/82037527-14815c80-96c4-11ea-9df6-087d67aee4cc.png) |
|   ![image](https://user-images.githubusercontent.com/12055657/82037561-1fd48800-96c4-11ea-9d83-3fd09a626844.png) |   ![image](https://user-images.githubusercontent.com/12055657/82037573-2531d280-96c4-11ea-9d1c-9c693fca0718.png) |

Dalston: Fixes Comment avatar on amp pages

---

barnsbury/style-rtl.css
barnsbury/style.css

Fixes #2009
Barnsbury Theme: Fix comment avatar size for AMP pages.
|   ![image](https://user-images.githubusercontent.com/12055657/82037141-8c9b5280-96c3-11ea-976f-48a6cee8719e.png) |   ![image](https://user-images.githubusercontent.com/12055657/82037165-9329ca00-96c3-11ea-8351-69758aaf185e.png)|
|   ![image](https://user-images.githubusercontent.com/12055657/82037179-991fab00-96c3-11ea-8ebb-52248a8cc3a3.png) |  ![image](https://user-images.githubusercontent.com/12055657/82037197-a046b900-96c3-11ea-9af1-137ea0fc4dac.png) |

Barnsbury: Fixes Comment avatar on amp pages

---

varia/sass/components/comments/_comments.scss
varia/style-rtl.css
varia/style.css

Varia: Fix Interpolation issue in comment-meta style

---

apostrophe-2/css/blocks.css
independent-publisher-2/css/blocks.css
ixion/blocks.css
libre-2/css/blocks.css
radcliffe-2/assets/css/blocks.css

Fixes #2076
Unsets the max-width and margin rules for nested blocks (except when they're inside of a full-width group block).
Todo: 
Notes: 
- The styles here are a little broader than are actually necessary to fix the problem in #2076. That one seems to deal _only_ with the Media & Text block, but the same problem that causes that exists for all nested blocks. This PR aims to solve that for everything in one go. When testing, check some of the other page templates, and you'll (hopefully) see things improve too.
- A few of these use some `!important` rules on full-width Video embeds. These will likely remain broken with this fix, unless I push some additional changes.

Multiple Themes: Fix nested wide/full blocks

---

seedlet/classes/class-seedlet-custom-colors.php
seedlet/functions.php

Addresses part of #2136. 
Fixes all of the WARNING messages thrown by the Theme Check plugin: 
- WARNING: More than one text-domain is being used in this theme. This means the theme will not be compatible with WordPress.org language packs. The domains found are seedlet, en
- WARNING: Found a translation function that is missing a text-domain. Function esc_html__, with the arguments This color combination may be hard for people to read. Try using a brighter background color and/or a darker foreground color.
-  WARNING: Found a translation function that is missing a text-domain. Function __, with the arguments seedlet
As well as one RECOMMENDED item: 
- RECOMMENDED: Possible variable $variable found in translation function in seedlet/classes/class-seedlet-custom-colors.php. Translation …

Seedlet: Fix text domain/translation errors

---

seedlet/classes/class-seedlet-custom-colors.php

Fixes part of https://github.com/Automattic/themes/issues/2136. 
> REQUIRED: Found a Customizer setting called "seedlet_$variable[0]" in seedlet/classes/class-seedlet-custom-colors.php that did not have a sanitization callback function. Every call to the add_setting() method needs to have a sanitization callback function passed.
Since these are supposed to be hex colors, This PR uses the global [`sanitize_hex_color`](https://developer.wordpress.org/reference/functions/sanitize_hex_color/) check.

Add a sanitize callback for the custom colors function.

---

alves/functions.php

Fixes #2146 by syncing up the custom colors logic with the code used in Coutoire and Rivington.
Previously, sites using Alves that had not previously tried out custom colors had their colors all appear black. The issue when away once users tried a different palette, or tried a different palette and then reverted back to the default. 
Before: 
After:

Alves: Fix custom colors logic

---

seedlet/header.php

Fixes part of https://github.com/Automattic/themes/issues/2136.
> REQUIRED: Could not find wp_body_openaction or function call at the very top of the body just after the opening body tag. See: [wp_body_open](https://developer.wordpress.org/reference/functions/wp_body_open/)
Adds a `body_open` function just after the body tag. This is what `_s` does. 
@allancole is there a reason this wasn't there originally?

Seedlet: Add body_open function

---

seedlet/functions.php

As per [notes here](https://github.com/Automattic/themes/issues/2136#issuecomment-645608804), this PR removes the conditional logic that checks whether or not to load the primary menu javascript. 
This currently throws up errors in the Theme Check plugin, so we'll remove for now and look into other ways of doing this.

Remove conditional logic to hide navigation scripts.

---

rivington/inc/wpcom-colors.php
rivington/inc/wpcom-editor-colors.php
rivington/style-editor.css
rivington/style-rtl.css
rivington/style.css

#1966 and #1944 made some changes to foreground color rules when a preset background color was selected. This led to existing sites changing appearance, even when custom colors were not active. 
This PR restores some of those rules, in order to restore the previous appearance. It also modifies the custom color rules to properly override these changes. 
**If this looks right, we should apply these same changes to Varia as well as to Coutoire and Alves. I can spin up PRs for those after this one lands.**
The following screenshots were taken with the Rivington default homepage.
Before (Default Colors)
After (Default Colors)
---
Before (Custom Colors)
After (Custom Colors)

Restore foreground color rules

---

shawburn/sass/_extra-child-theme.scss
shawburn/style-rtl.css
shawburn/style.css

Fixes #2063
This PR adjusts the margins for non-aligned button blocks so that they don't extend offscreen, causing horizontal scrolling. It also centers the button within the page to match the editor styles. 
1. Switch to Shawburn
2. View the default Shawburn homepage layout. 
3. Ensure that the button is centered, and that there's no horizontal scrolling on the page at breakpoints >1200px. 
Before: 
After: 
Here's a screenshot of the editor appearance for reference too:

Shawburn: Reset the non-aligned button block appearance

---

alves/inc/wpcom-editor-colors.php
alves/style-editor.css
alves/style-rtl.css
alves/style.css
coutoire/inc/wpcom-colors.php
coutoire/inc/wpcom-editor-colors.php
coutoire/style-editor.css
coutoire/style-rtl.css
coutoire/style.css
varia/sass/blocks/utilities/_editor.scss
varia/sass/blocks/utilities/_style.scss
varia/style-editor.css
varia/style-rtl.css
varia/style.css

Follows the mold of #2153 to restore foreground color rules to Varia, Coutoire, and Alves. Each needed slightly different edits to `wpcom-colors.php` and `wpcom-editor-colors.php` to get it working, but in general it's basically the same change everywhere:
- Restore the original text color rules when there are no custom colors active.
- In the color annotations, ensure that those color rules are properly overridden when custom colors _are_ active. 
I tested various combinations of block colors, but was a little conservative about my updates — I mostly made sure that I was fixing what was needed for the Rivington homepage to work properly in each of these themes, without touching too many other things.

Varia/Coutoire/Alves: Restore foreground color rules

---

rockfield/functions.php
rockfield/sass/_extra-child-theme.scss
rockfield/style-rtl.css
rockfield/style.css

Addresses: #2038 
Fix sticky header for rockfield theme on the AMP page.
In non-AMP mode, the JavaScript is used to calculate dynamic margin for the content wrapper as this JS is removed in the AMP page the content is not visible because of header. This PR adds a sticky position to the site header.
Sticky header Before on the AMP page.
Sticky header after on the AMP page.

Rockfield: Fix sticky header on AMP page

---

stratford/functions.php
stratford/sass/_extra-child-theme.scss
stratford/style-rtl.css
stratford/style.css

Fixes: #2038
Fix sticky header for Stratford theme on the AMP page.
In non-AMP mode, the JavaScript is used to calculate dynamic margin for the content wrapper as this JS is removed in the AMP page the content is not visible because of header. This PR adds a sticky position to the site header.
Sticky header Before on the AMP page (before fixes).
Sticky header after on the AMP page (after fixes).

Stratford: Fix sticky header on AMP page

---

coutoire/functions.php
coutoire/sass/_extra-child-theme.scss
coutoire/style-rtl.css
coutoire/style.css

Fixes: #2038
Fix sticky header for the Coutoire theme on the AMP page.
In non-AMP mode, the JavaScript is used to calculate dynamic margin for the content wrapper as this JS is removed in the AMP page the content is not visible because of header. This PR adds a sticky position to the site header.
Sticky header Before on the AMP page (before fixes).
Sticky header after on the AMP page (after fixes).

Coutoire: Fix sticky header on AMP page

---

varia/sass/blocks/latest-posts/_style.scss
varia/style-rtl.css
varia/style.css

Fixes https://github.com/Automattic/themes/issues/2045
If the **Latest Posts** block is set to Grid view and the column number is high like 5/6, the post titles are overlapping in both AMP & non-AMP versions. This PR aims to fix this by wrapping the post titles.
**"Latest Posts" block in Grid view in AMP Paired browsing mode (Before Fix)**
**"Latest Posts" block in Grid view in AMP Paired browsing mode (After Fix)**

Varia: Fix overlapping issue in latest post block

---

seedlet/assets/css/style-editor.css
seedlet/assets/sass/base/_editor.scss
seedlet/assets/sass/base/_reset.scss
seedlet/assets/sass/blocks/blog-posts/_style.scss
seedlet/assets/sass/components/comments/_comments.scss
seedlet/assets/sass/components/entry/_header.scss
seedlet/assets/sass/components/entry/_meta.scss
seedlet/assets/sass/components/footer/_footer-branding.scss
seedlet/assets/sass/components/footer/_footer-navigation.scss
seedlet/assets/sass/components/header/_header-branding.scss
seedlet/assets/sass/components/header/_primary-navigation.scss
seedlet/assets/sass/components/header/_social-navigation.scss
seedlet/assets/sass/components/pagination/_style.scss
seedlet/style-rtl.css
seedlet/style.css

Fixes #2140.
Seedlet was missing custom focus styles. This PR adds those in, using the design in the original design comps. 
It also cleans up the active styles.
Still todo: 
- ~~Add the 2px bottom border on hover/focus.~~
Before (Default browser focus styles):
After:

Seedlet: Add focus styles

---

seedlet-blocks/block-template-parts/header.html
seedlet-blocks/style.css

The site title now comes with an alignment control, so there's no need to center-align it via CSS.
Should look the same before & after:

Seedlet Blocks: Center-align the site title

---

seedlet-blocks/experimental-theme.json
seedlet-blocks/functions.php
seedlet-blocks/style-editor.css
seedlet-blocks/style.css

Adds basic global styles support for colors and font sizes to Seedlet Blocks. It accomplishes this by: 
- Adding an `experimental-theme.json` file, [using the spec here](https://developer.wordpress.org/block-editor/developers/themes/theme-json/). 
- It adds presets for the colors and font sizes used in the theme. 
- It adds CSS to the editor and to the front-end to map the Seedlet variables to the ones generated by `experimental-theme.json`. 
At this point, nothing at all should change visibly when this patch is applied. 😄 
To verify this is working, modify one of the values in `experimental-theme.json`, and verify that the update is reflected in the editor and on the front end.

Seedlet Blocks: Add basic global styles support

---

seedlet/header.php
seedlet/languages/seedlet.pot

This PR addresses #2192.
To test, check out this PR and verify that the `submenu` aria-label still exists on the WooCommerce navigation element.

Seedlet: address missing translations for aria-labels in header.php

---

seedlet-blocks/block-templates/home.html
seedlet-blocks/block-templates/index.html
seedlet-blocks/block-templates/singular.html

Updates the Seedlet block template parts and post content in templates to full width. Previously these were constrained to standard width which prevented us from recreating full page layouts, causing issues like this one https://github.com/Automattic/wp-calypso/issues/43640.
@ockham added this capability in core in https://github.com/WordPress/gutenberg/pull/23488 so now we can update the theme to use that.
1. Run latest version of Gutenberg master locally.
2. Map this branch of Seedlet blocks theme to your local install.
3. Delete any existing templates or template parts that you might have saved.
4. Make sure that demo templates experiment is turned off.
5. Open the site editor.
6. Verify that post content and template parts have full width by default.

Seedlet blocks: update template parts to full width

---

seedlet/assets/css/style-editor.css
seedlet/assets/sass/blocks/group/_editor.scss

The Seedlet blocks parent theme was declaring padding on group block which was interfering with full width display in site editor.
Before:
After:

Seedlet blocks: fix group block padding in site editor

---

seedlet/assets/css/ie.css
seedlet/assets/css/style-editor.css
seedlet/assets/css/variables-editor.css
seedlet/assets/sass/abstracts/_config.scss
seedlet/assets/sass/blocks/heading/_config.scss
seedlet/assets/sass/blocks/image/_style.scss
seedlet/assets/sass/blocks/subscription/style.scss
seedlet/assets/sass/components/comments/_comments.scss
seedlet/assets/sass/components/header/_primary-navigation.scss
seedlet/assets/sass/elements/_blockquote.scss
seedlet/assets/sass/elements/_config.scss
seedlet/assets/sass/elements/_media.scss
seedlet/style-rtl.css
seedlet/style.css

This PR addresses #2205.
The main change to consider is that it adds a new `--global--letter-spacing` variable that defaults to `normal`, and sets all variables associated with letter spacing to it. These were previously undefined, thus resulting in a `normal` value anyways. 
Compiling the styles should output the IE styles without warnings.

Seedlet: Define all unused CSS variables

---

seedlet/assets/css/style-editor.css
seedlet/assets/sass/blocks/utilities/_editor.scss

Varia child themes (and many others like [Mayland](https://github.com/Automattic/themes/blob/master/mayland/style-editor.css#L1190) and [Redhill](https://github.com/Automattic/themes/blob/master/redhill/style.css#L2597))  have a few classes built-in that help to control the spacing. This PR introduces the same spacing override classes to seedlet and seedlet-blocks. 
Addresses #2191
1. Checkout this branch
2. Zip the seedlet and seedlet-blocks theme to upload to a `jurassic.ninja` website (for a mac `zip -r seedlet.zip seedlet && zip -r seedlet-blocks.zip seedlet-blocks`)
3. [Import both themes](https://wordpress.com/support/themes/uploading-setting-up-custom-themes/) into a WordPress [jurassic.ninja site](http://jurassic.ninja/create?gutenberg)
4. Activate the `seedlet-blocks` theme
5. …

Seedlet: Add support for spacing overrides

---

seedlet-blocks/style-editor.css
seedlet/assets/css/style-editor.css
seedlet/assets/sass/blocks/utilities/_editor.scss
seedlet/style-rtl.css

This PR removes the margins for full-width blocks in Seedlet.
The Seedlet frontend has [styling](https://github.com/Automattic/themes/blob/master/seedlet/style.css#L613-L621) that removes top and bottom margins from full-width blocks within entry content. The `.entry-content` class, however, does not exist in the block editor. In order to implement the same behavior in the editor, we target full-width blocks by leveraging the the `[data-align="full"]` selector.
One thing to note is that the selectors to remove margins are different between `seedlet` and `seedlet blocks`. This is meant to accommodate full site editing. We don't want to remove the margins for _all_ full width blocks in the site editor (otherwise the header, content, and footer would have no spacing between them)
Fixes …

Remove full width block margins in the editor

---

seedlet-blocks/block-template-parts/footer.html
seedlet-blocks/block-template-parts/header.html
seedlet-blocks/block-templates/index.html
seedlet-blocks/block-templates/singular.html

Fixes #2240. 
Currently, the header in Seedlet Blocks uses a `site-header` class, to bring in some top and bottom margins from the original Seedlet theme. This isn't fully editable (or discoverable) in the site editor, so this PR removes that class and uses spacer blocks in the `header.html` template instead. 
This should have no effect on the header layout whatsoever, as the spacer blocks and native margins mimic what the `site-header` class did before. 
This PR does the same thing for the `site-footer` class too. In that case, it'll get just a little bit more margin than it did before this PR, because of the way Seedlet applies auto-margins. But that doesn't seem like a dealbreaker. 👍 
Theoretically, we shouldn't need those classnames for any semantic reasons, since these group blocks …

Seedlet Blocks: Use spacer blocks instead of css margins for the site header and footer

---

seedlet/functions.php

Fixes #2265. [Seedlet already supports this](https://github.com/Automattic/themes-workspace/pull/44), but custom line height has turned into an opt-in rather than a default. 
Before:
After:

Seedlet: Opt in to line custom-line-height

---

hever/functions.php

Using `display=swap` allows text to show up right away while waiting for the font to load, then swaps once it is finished.
You can see the type of difference this can make: https://www.webpagetest.org/video/compare.php?tests=200708_64_a5c3e57fdad44be3f5e98a618c78aca6%2C200708_7Y_27106d14550289c4ccc296ee0d819bbd&thumbSize=200&ival=100&end=visual

Use display=swap for Google Fonts

---

seedlet/assets/css/ie.css
seedlet/assets/css/style-editor.css
seedlet/assets/sass/base/_editor.scss
seedlet/assets/sass/base/_reset.scss
seedlet/assets/sass/blocks/cover/_editor.scss
seedlet/assets/sass/blocks/cover/_style.scss
seedlet/assets/sass/blocks/media-text/_editor.scss
seedlet/assets/sass/blocks/media-text/_style.scss
seedlet/assets/sass/blocks/paragraph/_editor.scss
seedlet/assets/sass/blocks/paragraph/_style.scss
seedlet/style-rtl.css
seedlet/style.css

- When using a custom background color that changes the text color (e.g. picking a black background sets the text white), only change the link color if it's not specified by the block.
- Remove the override that only worked for blocks with `p` as root element (e.g. the Paragraph block).
- Add a missing fallback color for the `--wp--style--color--link` variable.
This change originates from a [discussion in Gutenberg](https://github.com/WordPress/gutenberg/pull/23945#discussion_r455596699), where we noticed that the theme's style specificity was getting in the way with the link colors on non-Paragraph blocks.
The missing fallback color was throwing a `postcss-css-variable` working when building the theme style.
The `--wp--style--color--link` variable is defined by Gutenberg, and it's …

Seedlet: Allow all blocks with a link color to override the text color value set by custom background colors

---

seedlet-blocks/block-template-parts/header.html

Updates the site-title block used in the header to use `textAlign` for the text alignment attribute.
**Background**
FSE blocks in core have been updated so that text alignment settings will be saved under the `textAlign` attribute instead of `align`.  This was for compatibility and clarity since the `align` hook uses this attribute to save block alignment settings. The site-title block seems to be the only block used in seedlet Template and Template Parts that was effected.
As a result this attribute was not being set and the header looked like:
After this update:

Seedlet Blocks - Update header site title block text alignment attribute

---

ibis/functions.php
ibis/style-editor.css

This PR has a few fixes.
- Correctly loads the Editor Styles for Ibis _after_ the Seedlet ones. Props @alaczek for pointing me in the right direction with her debuggin'.
- Adds some of the new front-end styles to the editor styles. Layout and fonts'll match now.
- Fixes a typo in the code I stole from Mayland. :)

Ibis: Editor Style and Font Fixes

---

seedlet-blocks/functions.php

These styles should load _after_ the parent theme in order to correctly override the parent. Hence the priority. I'm not sure if it'll have a noticeable effect on the Editor? I only noticed this when I stole this code to work on the Ibis theme. Worth fixing if only for future code, ahem, borrowers, like myself.
Ref:
https://github.com/Automattic/themes/pull/2313/files#diff-0140ea09b827571eed7227805bc9a4d3R28

Seedlet Blocks: Load theme setup with correct priority

---

dalston/functions.php

As JS <script> tags cannot be used in AMP version unless they are for loading AMP components. In order for a page to be served as AMP, the custom JS codes must be removed from the page. In this case the enqueue_block_assets hook is used to load the block scripts in both admin and frontend which is causing validation errors. This PR checks for whether is on AMP endpoint and if not then enqueues the Block scripts.
Fixes #2230

Dalston: Enqueue Block Scripts only in non-AMP

---

seedlet-blocks/block-template-parts/header.html

Replace static paragraph text in header template part with newly introduced Site Tagline block from core.
1. Use a local wp-env instal with latest Gutenberg version and Site Editor experiment enabled.
2. Map this branch to your themes folder and enabled the Seedlet blocks theme.
3. Open the Site Editor and verify that site tagline appears in the header.

Seedlet blocks: replace paragraph with Site Tagline block in header

---

seedlet/assets/css/ie.css
seedlet/assets/sass/structure/_vertical-margins.scss
seedlet/style-rtl.css
seedlet/style.css

This PR adds `wp-block-template-part` to the list of parents that should provide children with the default top/bottom margins for blocks. This is primarily a change for use in Seedlet Blocks, but the change itself has been made in Seedlet to avoid repeating styles unnecessarily. 
Template parts appear to provide their own wrapper now on the front end: 
---
Before (Seedlet Blocks default header, front-end): 
After:

Seedlet/Seedlet Blocks: Add default top/bottom margins to items within template parts

---

seedlet/assets/js/primary-navigation.js

Fixes an issue where if the theme contains no primary or woo nav, a JS error is thrown. 
**To test**
- Activate Seedlet and remove all menus
- Open the console and ensure that no errors are thrown

Seedlet: fix primary nav js bug

---

seedlet/assets/js/primary-navigation.js
seedlet/header.php

This PR fixes a regression introduced in #2305, where the woocommerce cart was not appearing on desktop. 
**Before**
**After**

Seedlet: fix woocommerce cart bug

---

seedlet/header.php

This PR removes the tabindex value from the skip link in the header.
Positive tabindex values are not allowed in themes: https://make.wordpress.org/themes/handbook/review/accessibility/required/#not-allowed

Seedlet: remove positive tabindex from skiplink

---

seedlet/assets/css/ie.css
seedlet/assets/css/style-editor.css
seedlet/assets/sass/abstracts/_config.scss
seedlet/assets/sass/base/_editor.scss
seedlet/assets/sass/base/_reset.scss
seedlet/assets/sass/components/entry/_config.scss
seedlet/assets/sass/components/entry/_content.scss
seedlet/assets/sass/components/entry/_header.scss
seedlet/assets/sass/components/entry/_meta.scss
seedlet/assets/sass/components/footer/_footer-navigation.scss
seedlet/assets/sass/components/header/_config.scss
seedlet/assets/sass/components/header/_header-branding.scss
seedlet/assets/sass/components/header/_primary-navigation.scss
seedlet/assets/sass/components/pagination/_style.scss
seedlet/assets/sass/vendors/jetpack/blocks/blog-posts/_editor.scss
seedlet/style-rtl.css
seedlet/style.css

This PR adds a visual hover indicator for all links, [addressing this feedback](https://themes.trac.wordpress.org/ticket/85664#comment:17):
> But the contrast ratio between the default state and the hover state for several links, 
> that are missing a text decoration, is not enough.
> 
> #333 and #3C8067 only has a contrast ratio of 2.69:1
> 
> The easiest way to indicate the different link states is with a text decoration, and not only rely on color.
> For example if a link is not underlined in its default state, you can add an underline for the hover state.
> Or a border, outline, box shadow, background color etc.
[Based on further clarification](https://themes.trac.wordpress.org/ticket/85664#comment:19), it sounds like all link hover states need a visual indication of change in …

Seedlet: Add a visual hover indicator for all links

---

seedlet/assets/css/ie.css
seedlet/assets/sass/components/footer/_footer-branding.scss
seedlet/assets/sass/components/footer/_footer-navigation.scss
seedlet/style-rtl.css
seedlet/style.css

Cleans up the appearance of the footer menu, for both desktop and mobile screens.
Desktop 
Before|After
---|---
Mobile
Before|After
---|---

Seedlet: Clean up footer navigation

---

seedlet/functions.php

This PR addresses #2391.
Previously, the theme looked to see if `colors_manager` theme mod had been set to determine the presence of wpcom color annotations plugin. This would fail the condition if the colors hadn't been altered yet. 
This fix checks for the existence of the class at all h/t @jeffikus.
**To test**
- Proxy seedletdemo.wordpress.com and verify two panels appear
- Check out this PR onto your sandbox
- Verify that only the color annotations panel appears

Seedlet: fix two custom color panels loading on wpcom

---

seedlet/assets/css/ie.css
seedlet/assets/css/style-editor.css
seedlet/assets/sass/blocks/latest-posts/_editor.scss
seedlet/assets/sass/blocks/latest-posts/_style.scss
seedlet/functions.php
seedlet/inc/block-patterns.php
seedlet/inc/block-styles.php
seedlet/style-rtl.css
seedlet/style.css

This provides an "Alternating Grid" block style to match up with the original theme design. It displays posts in an alternating grid on desktop, but keeps them stacked and left aligned on tiny screens. 
It also displays the exact same way whether or not you have the "Grid" setting set up for the Latest posts block.

Seedlet: Add Alternating Grid block style for the Latest Posts block

---

seedlet/assets/css/ie.css
seedlet/assets/css/style-editor.css
seedlet/assets/sass/vendors/jetpack/blocks/blog-posts/_editor.scss
seedlet/assets/sass/vendors/jetpack/blocks/blog-posts/_style.scss
seedlet/inc/block-styles.php
seedlet/style-rtl.css
seedlet/style.css

Followup to https://github.com/Automattic/themes/pull/2399. This PR adds an alternating grid block style to the Automattic Blog Posts block as well. Looks & works basically the same. 
This PR also removes the erroneous [double underline](https://cloudup.com/cb5lAfepVxi) that was showing up for post meta in the Blog Posts block.

Add Alternating Grid block style to the Blog Posts block.

---

seedlet/style.css

Adds auto-loading-homepage tag so that the headstart homepage creation feature works on WordPress.com
Adds auto-loading-homepage tag to main stylesheet.

Adds headstart auto loading homepage tag

---

seedlet/404.php
seedlet/archive.php
seedlet/footer.php
seedlet/header.php
seedlet/image.php
seedlet/index.php
seedlet/page.php
seedlet/search.php
seedlet/single.php
seedlet/template-parts/content/content-page.php
seedlet/template-parts/content/content.php
seedlet/template-parts/footer/footer-widgets.php

This PR addresses the following Theme Review accessibility [feedback](https://themes.trac.wordpress.org/ticket/85664#comment:23): 
- The UL items inside the nav, in items_wrap, should not have the navigation role:
- Aside must not be contained in another landmark ("Aside is used for the widget area inside the footer landmark")
- The role="main" should be placed on the `main` element only, one per document
The one thing I'm unsure of is whether to remove the `aria-label` completely from the `ul` in the nav:
https://github.com/Automattic/themes/blob/b3c4428a023a737c0e23b37fde8058d7130ab8ce/seedlet/header.php#L61

Seedlet: fix landmark roles

---

seedlet/functions.php

This PR adds custom units support to Seedlet. 
To test: Add a cover block, and verify that you're able to change the unit for the min-height control. 
Before: 
After:

Seedlet: Add custom units support

---

seedlet/assets/css/ie.css
seedlet/assets/sass/style.scss
seedlet/style-rtl.css

Follow up to #2405. This needs to be added to the sass files so it won't get overwritten later on.

Seedlet: Add headstart auto-loading-homepage tag to SASS files

---

seedlet/functions.php

Fixes #2386 by removing the `is_ie` variable in favor of the global `is_IE` variable exposed by WordPress here: https://github.com/WordPress/WordPress/blob/001ffe81fbec4438a9f594f330e18103d21fbcd7/wp-includes/vars.php#L107

Seedlet: Use WordPress global to detect IE support

---

seedlet/inc/wpcom.php

This PR addresses #2416. 
This moves Seedlet's default editor palette de-registration into the conditional that verifies the presence of a custom color palette loaded via the colors plugin.
**To Test**
- Check out this PR onto your sandbox
- Spin up a fresh site on wpcom
- Activate Seedlet
- Open up a post and verify that the default Seedlet palette is loaded

Seedlet: de-register default editor palette correctly

---

seedlet/assets/css/ie.css
seedlet/assets/css/style-editor.css
seedlet/assets/sass/blocks/cover/_editor.scss
seedlet/assets/sass/blocks/cover/_style.scss
seedlet/assets/sass/blocks/utilities/_style.scss
seedlet/style-rtl.css
seedlet/style.css

Today, Seedlet's background color rules sometimes override text color when it is applied to button text. 
To test this: 
1. Create a cover block OR a group block, and set its background to one of the default palette colors. 
2. Inside that block, add a button block that uses theme palette colors for the text and background. 
3. Observe that it appears as intended in the editor. 
4. On the front end however, notice that the text color is not correct. 
This PR ensures that custom text color always override the background-imposed colors. 
Editor: 
Frontend (Before):
Frontend (After):

Seedlet: Correct nested color rules

---

seedlet/inc/block-styles.php

Fixes #2423.
Adds missing translation functions to `block-styles.php`.

Seedlet: Add translation functions to block-styles.php

---

seedlet/assets/css/ie.css
seedlet/assets/sass/style.scss
seedlet/style-rtl.css
seedlet/style.css

This PR adds a few extra [theme tags](https://make.wordpress.org/themes/handbook/review/required/theme-tags/) for Seedlet: 
- `block-styles` (because it includes block styles)
- `block-patterns` (because it includes block patterns)
- `wide-blocks` (because it supports wide & full alignments)

Seedlet: Add additional gutenberg-related theme tags

---

alves/style-rtl.css
alves/style.css
balasana/style-rtl.css
balasana/style.css
barnsbury/style-rtl.css
barnsbury/style.css
brompton/package-lock.json
brompton/style.css
coutoire/style.css
dalston/style.css
exford/style.css
hever/style.css
leven/style.css
mayland/style.css
maywood/style.css
morden/style.css
redhill/style.css
rivington/style.css
rockfield/style.css
seedlet/style-rtl.css
shawburn/style.css
stow/style.css
stratford/style-rtl.css
stratford/style.css
varia/package.json
varia/rebuild-child-themes.sh

This adds a shell script to make it easy to rebuild all Varia child themes in one go.
Just run `npm run children`

Add a rebuild tool for varia themes

---

coutoire/functions.php
coutoire/sass/_config-child-theme-deep.scss
coutoire/sass/style-child-theme.scss
coutoire/style-editor.css
coutoire/style-rtl.css
coutoire/style.css

Added the bold font weight inside functions.php `coutoire_fonts_url` function because we only had 400 and 400i for Garamond. 
I also had to default the headings to a weight of 400 for the `bolder` rule to pick up the correct weight.
#2415

#2415 Coutoire: Fixed missing bold font on headings 

---

alves/package.json
balasana/package.json
barnsbury/package.json
brompton/package.json
coutoire/package.json
dalston/package.json
exford/package.json
hever/package.json
leven/package.json
mayland/package.json
maywood/package.json
morden/package.json
redhill/package.json
rivington/package.json
rockfield/package.json
shawburn/package.json
stow/package.json
stratford/package.json
varia/rebuild-child-themes.sh

In https://github.com/Automattic/themes/pull/2461 I only updated the version number in the style.css not in the package.json. This adds a line to also update the package.json version. They should now be in sync.

Fix version numbers for Varia child themes

---

alves/package.json
balasana/package.json
barnsbury/package.json
brompton/package.json
coutoire/package.json
dalston/package.json
exford/package.json
hever/package.json
leven/package.json
mayland/package.json
maywood/package.json
morden/package.json
redhill/package.json
rivington/package.json
rockfield/package.json
shawburn/package.json
stow/package.json
stratford/package.json
varia/package.json

@MaggieCabrera pointed out that we need to build varia based themes twice to get the RTL styles built. This is because the build script runs the jobs in parallel. This changes the script to run the jobs in series, which means that the RTL job happens after the CSS is built and you only need to run the build once.
To test:
- Make a change to a varia based theme
- run `npm run build`
- confirm that the style.css and style-rtl.css files change.

Varia: Make the build jobs sequential

---

seedlet/assets/css/ie-editor.css
seedlet/package.json

This PR fixes the same issue as #2469. It also recompiles the IE editor styles that apparently hadn't been checked in.
To test:
- Make a change to Seedlet
- Run `npm run build`
- Confirm that the style.css, style-rtl.css, and ie.css files change.

Run build sequentially and recompile IE styles.

---

pique/style.css

This removes some CSS selectors that were breaking galleries. It looks like this was added in 30932-wpcom-themes, to centre align the content when there is only one column, but it seems to work regardless of these lines. I have also tested in IE11.
Before:
After:
Fixes #2371

Fixes galleries in Pique

---

seedlet/assets/css/ie.css
seedlet/assets/sass/components/header/_primary-navigation.scss
seedlet/style-rtl.css
seedlet/style.css

The flash was caused by the buttons changing state faster than the menu was disappearing. First I thought about having the buttons change state with the same transition time as the menu but their state changes instantly because the property affected is display: none;
So I thought having the Menu button over the actual menu but behind the close button would do the trick and avoid the flickering with a minimal change.
#2382

#2382 swaped the z-index of the menu buttons to avoid flash

---

seedlet/functions.php

Fixes #2464
Declare support for HTML5 navigation widgets.
This feature was added in WordPress 5.5.
For reference: https://make.wordpress.org/core/2020/07/09/accessibility-improvements-to-widgets-outputting-lists-of-links-in-5-5/
https://github.com/Automattic/themes/issues/2464

Seedlet: Declare support for HTML5 navigation widgets

---

seedlet/inc/wpcom-colors.php
seedlet/inc/wpcom-customize-preview.js
seedlet/inc/wpcom-editor-colors.php
seedlet/style.css

I noticed an issue in Seedlet in the dark color scheme:
In the dark color scheme some of the contrast isn't very strong:
Rather than creating more selectors to deal with this, this PR proposes that we just update the CSS variables for this color scheme.
To test, apply this patch to your wpcom sandbox, set the site to Seedlet and then open the customizer.
When you switch to the dark color, you should see text with higher contrast, like this:
Also check that this looks the same when you edit the homepage.

Seedlet: Update the color annotations

---

photos/blocks.css

Fixes #2057. 
Setting `height: auto` makes the audio block disappear in Chrome. The audio block has a built-in height by default, so it shouldn't need this rule anyway. 
Before: 
After:

Photos: Fix invisible audio block

---

spearhead/variables.css

Without this the sub menus don't align correctly

Update the primary-nav--padding to use a px variable so that the types match

---

seedlet/assets/css/ie.css
seedlet/assets/sass/blocks/gallery/_style.scss
seedlet/style-rtl.css
seedlet/style.css

The margin value for galleries was affecting the responsive style for full width galleries and causing a scroll. I omitted the margin in the case where the gallery is full width so that the `.alignfull` rules will apply to them.
Create a full width gallery and check that you can't scroll horizontally on mobile. The gallery should be full width.
Closes #2471

fix for mobile scroll on alignfull galleries

---

spearhead/package.json

In the same way that we added source maps to Seedlet, we should add them to Spearhead.

Add sourcemaps to Spearhead

---

gazette/style.css

Changed height of post thumbnail to auto, since the width is already 100%, I don't see a reason why the height should be 100%
Closes #2504

Gazette: changed height to post-thumbnail

---

spearhead/variables.css

Update dark mode colors with the following values to improve contrast _(for accessibility reasons)_:
`#080b11` for background
`#b2b2b2` for the foreground _(body text)_
`#f00048` for the accent color
As proposed [here](https://github.com/Automattic/themes/issues/2538#issuecomment-703129124)
Furthermore, updated entry header color to white: `--global--color-foreground-light`
| BEFORE  | AFTER |
| ------------- | ------------- |
| ![before_spearhead_contrast](https://user-images.githubusercontent.com/29238672/95466350-e44f9880-0999-11eb-9d10-849dfc46e143.png) | ![after_spearhead_contrast](https://user-images.githubusercontent.com/29238672/95466388-ec0f3d00-0999-11eb-98c8-54eb872a5cd3.png) |
#2538

#2538: Spearhead: Dark mode contrast

---

spearhead/functions.php
spearhead/inc/block-patterns.php

This PR addresses the following notice: 
```
Notice: WP_Block_Patterns_Registry::unregister was called incorrectly. 
Pattern "seedlet/latest-posts-alternating-grid" not found. 
Please see Debugging in WordPress for more information. (This message was added in version 5.5.0.) in /Users/maggie/A8c/repos/wp/wp-includes/functions.php on line 5225
```
The unregister calls are not working at the moment and I'm not sure why. Perhaps a child theme cannot unregister a block pattern from its parent theme? This removes them for now.

Spearhead: fix unregister block pattern bug

---

seedlet/inc/wpcom-colors-utils.php
seedlet/inc/wpcom-customize-preview.js

This moves the colorline functions into the theme, so that we don't have to use the library, which isn't on Atomic sites.
To test:
- Check out this branch and move the files to your sandbox
- Switch color pallettes in the customizer
- Check that the colors work on the front end too.

Seedlet: Define colorline functions in the theme

---

seedlet/archive.php
seedlet/inc/template-tags.php
seedlet/index.php
seedlet/search.php
seedlet/single.php
spearhead/functions.php

This PR addresses #2594. 
Previously in Seedlet, the post navigation was hardcoded into the template. This PR makes the following changes: 
- Refactors Seedlet's post navigation into a template tag so it can be overwritten in a child theme.
- Overwrites the template tag in Spearhead (disabling previous / next links). 
- Rename's Seedlet's post _pagination_ template tag function to be consistent with the actual WP function it calls, and updates its use respectively in the templates
Test
- Go to a post in Spearhead and confirm the Previous/Next links are gone.
- Go to a post and category / archive page in Seedlet and confirm the pagination and navigation work as they did before.

Spearhead + Seedlet: make it possible to remove the previous / next post navigation (#2594)

---

dyad-2/style.css

Updated styles on Dyad 2 to fit with the new marketing bar.
* Update your sandbox with the contents of this PR.
* Modify the following file on your sandbox:
`https://opengrok.a8c.com/source/xref/trunk/wp-content/blog-plugins/marketing-bar.php`
* If your site is older than 2018-05-16 change this line:
`const SHOW_MARKETING_BAR_FOR_BLOGS_REGISTERED_ON_OR_AFTER = '2018-05-16';`
* If modulo of your user id is not 7, change the `!===` to `==`
`if ( is_user_logged_in() && 7 !== (int) $blog_owner % 10 ) {`
Dyad 2 with wp admin bar:
https://d.pr/i/YojCOL
Dyad 2 without wp admin bar:
https://d.pr/i/3ujg5Y
#2629

Dyad 2: fixed menu to work with marketing bar

---

independent-publisher-2/functions.php

#2444 
#2454 
This addresses a few issues with Independent Publisher 2. Specifically captions and embeds.
Before: https://llamaeatsagiraffe.wordpress.com/331-2/
After: https://business-plan.blog/sample-page/
I used Code Snippets to test the block style function.
```
// Add support for Block Styles.
add_theme_support( 'wp-block-styles' );
```

Add Block Style to Independent 2

---

seedlet/archive.php
seedlet/inc/customizer.php
seedlet/index.php

This PR partially addresses #2652. 
It adds a toggle to the customizer, allowing users to show a summary (excerpt) or full post when the home page is set to display Latest Posts. It adds the same toggle for archive pages. Much of the implementation was borrowed from TT1. 
Note the default is set to "Full Post", as to not interfere with the current Seedlet behavior.
Screen recording: https://cloudup.com/cZE1PEpx_VJ
**To Test**
- Check out this PR and visit the Customizer > Excerpt Settings in Seedlet or Spearhead
- Change the option to show a Summary instead of Full Post
- Verify the excerpt is shown

Seedlet: add customizer toggle for excerpts on home and archive pages

---

spearhead/search.php

D51300-code introduce a typo. `seedlet_the_posts_navigation()` does not exist but `seedlet_the_post_navigation()` [does](https://github.com/Automattic/themes/search?q=seedlet_the_post_navigation).
It's causing the following error report on wpcom-alerts:
```
Uncaught Error: Call to undefined function seedlet_the_posts_navigation()
```

Spearhead: update posts navigation function name

---

spearhead/variables.css

At some point in development some padding variables were added to the 'dark mode' media query block duplicating values that were since changed.
Rather than bringing these into sync these padding-related values are being removed from the dark mode query.
There shouldn't be any testing necessary, or any that would be obvious; no change is expected.
#2718

Remove padding attributes from Dark Mode variables

---

spearhead/functions.php

This is my attempt at showing the audio block on the excerpt of a post. 
To test:
* Create a post and add an audio block
* Set the home page and/or archive pages to show only summary of posts
* The audio block should show up after the content of the post
Also note that:
* If there is no other content but the audio block, the block should show up on the excerpt
* If there is multiple blocks on the post (audio or otherwise) the only block that should show up on the excerpt is the first audio block from the post.
* If no audio block is present the excerpt should look just like before.
Fixes #2578

Spearhead: show audio block on the excerpt

---

.gitignore

This PR updates the gitignore to exclude files of type `.rej` that can be passed back and forth between wpcom.

Ignore rej files.

---

spearhead/variables.css

Fixes #2743. 
Spearhead just needed to declare the variables that global styles hooks into.

Spearhead: Add Global Styles CSS variables

---

seedlet/inc/wpcom-colors-utils.php

This PR addresses #2737. 
Currently, some of our code that converts RGB to HSL causes a php warning to be output to a style tag where the CSS variable overrides are set:
This would result in invalid style rules, thus custom colors picked via the customizer would not appear.
**To test**
- Activate Spearhead
- Check out this PR onto your sandbox
- Change an individual color from the default palette
- Verify that the color is changed in the view, and that no warnings are generated in the style tag `id="custom-colors-css"`

Spearhead: fix custom colors
